### ISSUE TITLE
When a presentation starts via "Play from current slide" any content add-ins _not_ on the initial slide in PowerPoint for Mac don't get the `ActiveViewChanged` event

### ISSUE THREAD

**Issue by koralcem** [OfficeDev/office-js#102]
In PowerPoint for Mac (version 16.11.1, build 180319) the user can start the presentation in a couple different ways:
* From the "Slide Show" ribbon tab, the "Play from Start" button
* From the "Slide Show" ribbon tab, the "Play from Current Slide" button
* The "Slide Show" button on the status bar, next to the zoom slider

When the last two methods are used, any content add-ins that are on slides that *aren't* the slide that the presentation starts on never get the `ActiveViewChanged` event.

## Expected Behavior
When a presentation starts, with either method, all slides should get the `ActiveViewChanged` event.

## Current Behavior
* If a presentation is started via the "Play from Start" button, all slides get the `ActiveViewChanged` event. But ...
* If a presentation is started via the "Play from Current Slide" button or the "Slide Show" button on the status bar, only the initial slide gets the `ActiveViewChanged` event.

## Steps to Reproduce
1. Create a PowerPoint content add-in that:
    * Initially just displays a plain white background
    * Uses `addHandlerAsync` to register a handler for the `ActiveViewChanged` event and provide a `handler` function to be called when done
    * In the `handler` function check the value of `activeView` and, if it's `read`, change your background to red. You should now have a content add-in that shows white when the slide is first inserted and turns red when you enter a presentation
1. Create a new deck in PowerPoint for Mac
1. Insert 3 slides
1. Insert the add-in created above on all 3 slides
1. Select your first slide
1. From the "Slide Show" ribbon tab, click the "Play from Current Slide" button
1. Note how your first slide is red
1. Advance to your second slide
1. Observe how it's still white; it was never notified that the presentation started. The same is true for the third slide.

If you start again with a fresh deck, repeat the steps, but click the "Play from Start" button instead in step 6, you'll see that all your slides are red during your presentation.

## Context
We're developing an add-in whose behavior differs between editing a slide and during a presentation. We'd like to show the author of the slides a certain view where they can edit their content, but display a "finalized" or "live" view to the audience during a presentation. Everything works fine if the user starts the presentation using the "Play from Start" button. When they use the "Play from Current Slide" button, the slide they start on is also fine. But all _other_ slides still show their "edit mode" view, which doesn't look professional.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: PowerPoint
* Office version number: 16.11.1, build 180319
* Operating System: macOS 10.13.4
* Browser (if using Office Online): N/A; not in browser

**Comment by koralcem** [comment]
FYI: The issue template mentions creating a sample in https://aka.ms/script-lab, but that address resolves to the Microsoft home page.

**Comment by Zlatkovsky** [comment]
@koralcem , re. the link not working:  apologies for that, it's supposed to be https://aka.ms/scriptlab, without the hyphen.
This has been fixed now (https://github.com/OfficeDev/office-js/pull/103)
For the actual PPT issue, will leave the bug open for someone to take a look.

**Comment by JuaneloJuanelo** [comment]
@koralcem the issue you describe is a bug in PPT for MAC. THanks so much for reporting this. A fix will most probably ship on the update happening Aug 2019. (tracked with 3468440)

**Comment by adetayoadeyemi** [comment]
Any update on this issue??
I'm here September 2019

**Comment by kbrandl** [comment]
@adetayoadeyemi according to the internal work item that @JuaneloJuanelo [sites above](https://github.com/OfficeDev/office-js/issues/102#issuecomment-507862067), this issue has been fixed. I'm therefore going to label this issue as 'fixed' and close it; please do comment here if you continue to observe this issue. Thanks!

**Comment by adetayoadeyemi** [comment]
issue not fixed, my project was created with Yo Generator 4 days ago, last update was 10 days ago, pretty sure I did not miss it

**Comment by kbrandl** [comment]
@adetayoadeyemi thanks for the update; I'll reopen this issue and remove the 'fixed' label. @JuaneloJuanelo can you please comment here to indicate when this fix will be available to customers, and what version of PowerPoint they'll need to be running in order to get the fix? Thanks!

**Comment by adetayoadeyemi** [comment]
Thanks, waiting for response from @JuaneloJuanelo

**Comment by JuaneloJuanelo** [comment]
@adetayoadeyemi  i think this issue was released on december, do you still see the issue in the latest updates for Mac? 
Closing as i tested on my end and could not repro.

**Comment by koralcem** [comment]
I indeed can no longer repro on PowerPoint for Mac, version 16.36 (20041300). Specifically, if I start a presentation with each of the three methods originally mentioned, all slides after the first are notified that the presentation started.

Thanks everyone!
