### ISSUE TITLE
Add-in memory leak in Outlook Desktop Edge Web Viewer

### ISSUE THREAD

**Issue by xyc** [OfficeDev/office-js#1069]
## Expected Behavior

No memory leaks

## Current Behavior
Memory leaks when opening and closing emails in new window

## Steps to Reproduce, or Live Example

1. Open Outlook desktop app and login
2. Open an email, and open a pinnable add-in
3. Open Task Manager
4. Double click an email in the inbox, wait for it to open in a new window and wait for the pinnable add-in to load
5. Close the new window
6. Repeat Step 4 and 5 multiple times
7. The memory usage of "Desktop App Web Viewer" keep growing at a significant rate.

## Context
The memory usage of "Desktop App Web Viewer" grows to an extent that it might freeze Outlook or reaches add-in memory limit and crashes ultimately, rendering add-ins unusable.

## Your Environment

* Platform: PC Desktop
* Host: Outlook
* Office version number: 16.0.12718.20004
* Operating System: Windows 10.0.18362 Build 18362
* Browser (if using Office Online): [Edge Webview](https://developer.microsoft.com/en-us/outlook/blogs/microsoft-edge-webview-for-office-add-ins/)

**Comment by ElizabethSamuel-MSFT** [comment]
@xyc Sorry that you hit this issue and thanks for raising it.

@jargil Can you take a look?

Thanks.

**Comment by mixtmeta** [comment]
We are also experiencing similar issues with multiple add ins (from the store and our own developed in house). This issue seems to leave many DAWV processes hanging/orphaned and eventually results in an Outlook crash. Is there any update on this ticket?

**Comment by bhanes2046** [comment]
> We are also experiencing similar issues with multiple add ins (from the store and our own developed in house). This issue seems to leave many DAWV processes hanging/orphaned and eventually results in an Outlook crash. Is there any update on this ticket?

We are also experiencing the same issue with only one user for now. We use a smartcloud connect salesforce add in on outlook and when the add in is open in an email we see the desktop app web viewer growing in processes and taking up much of the memory usage.

**Comment by croicu** [comment]
Adding @Ling<mailto:lingz@microsoft.com> and @Sudheer<mailto:Sudheer.Maremanda@microsoft.com>. Bug https://microsoft.visualstudio.com/OS/_workitems/edit/26315558 currently tracks the issue om the Edge side.

Thanks,
Alex

________________________________

**Comment by bhanes2046** [comment]
any updates on this?

**Comment by smaremanda** [comment]
@bhanes2046 - we are looking into this issue. we will keep you posted on the progress,

**Comment by chrisecorcoran** [comment]
@smaremanda do you have any updates on this? Our customer support team receives a number of tickets on this every week.

**Comment by splinter** [comment]
To all those having this issue: Are you using Angular2?

**Comment by JuaneloJuanelo** [comment]
Updates: there is a fix released as part of a Windows update, see details [here](https://support.microsoft.com/en-us/help/4566116/windows-10-update-kb4566116).

Please try it and let us know outcomes.

**Comment by swasti1994** [comment]
This issue is still reproducible even after applying [August 2020](https://support.microsoft.com/en-us/help/4566116) Patch for a few of our users.

**Comment by JuaneloJuanelo** [comment]
Followed up offline with @swasti1994  and his scenario is different. @swasti1994  please open a separate issue for your scenario. thanks!
