### ISSUE TITLE
Calling getOoxml returns vague RichApi.Error

### ISSUE THREAD

**Issue by DannyHinshaw** [OfficeDev/office-js#1097]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I tried to get another issue to be reopened (https://github.com/OfficeDev/office-js/issues/998#issuecomment-607394484) but since it's been almost two weeks now I am creating this issue. 

This issue seems to have been triggered by a Word update, as it wasn't until I updated Word that it started failing (unfortunately I don't have the previous version numbers).

The issue is that 
## Expected Behavior
Calling `getOoxml` method should return an xml object to be parsed and not an Error.

## Current Behavior
Trying to call `getOoxml` method returns vague error `RichApi.Error: GeneralException`. Can no longer access the xml at cursor position.

## Steps to Reproduce, or Live Example
Here's a repo for reproducing the error. It's just the Yeoman Word React TypeScript generated app with the `range.getOoxml` codes snippet from the official OfficeJS documentation inserted to the button click handler.
https://github.com/DannyHinshaw/test-word-context

To reproduce:

1. Sideload the addon
2. Add a simple bar chart and move cursor to the chart title text.
3. Click the button in the Add-On and see in console the errors.

## Context
Our Word addon needs to be able to check the xml of the current cursor position to make sure it's not on any elements that have bugs around content control insertion (charts, textboxes etc).

## Your Environment
Word for Mac:
16.35 (20030802)

MS Word for Office 365 MSO (Windows 10):
16.0.12624.20348 (64-bit)

**Comment by JuaneloJuanelo** [comment]
@DannyHinshaw  thanks for creating this issue. 
I was able to repro this issue, this sounds like a bug. we are tracking internally with  but 4124423.

i have a question, though, i see that in your code you are trying to get the OOXML of the selection, can you please describe in more detail your scenario, for instance what are you doing with the OOXML from the chart title selected? thanks!

**Comment by DannyHinshaw** [comment]
@JuaneloJuanelo thank you for your reply.

Honestly, what we are doing is sort of a workaround for other Word API issues. Basically, we have an addon where users insert citations, but we found that on certain special elements (like in the title of a chart) when we try to insert a content control it replaces the entire element with it. So one way we have found to prevent that is by using the `getOoxml` method before inserting a content control to check and make sure that we aren't on a special element, and block the user from inserting if it is. In Word desktop `getOoxml` returns nothing (`undefined` I believe, maybe `null`) when the cursor isn't on a special element (or so it used to), so if it returns xml we use that as a red flag to block insertion of content controls. Of course, this doesn't work in Word online where that method _always_ returns xml.

**Comment by JuaneloJuanelo** [comment]
ok that makes sense. GetOOXML is quite expensive specially in Online, but i understand this is actually the only way to validate what you are looking for. do you see this behavior only on charts? I wonder about the commonality of the scenario.

**Comment by JuaneloJuanelo** [comment]
@DannyHinshaw this issue is fixed and in the process to be rolled out. It will be included in the next insiders fast release. Build 16.0.13123.20006 + , i think it should be out in a couple of weeks, can you test it there and let us know outcomes? it should not fail now.
thanks!

**Comment by marcotonani** [comment]
With big size documents (around 100mb) and layered images the getOoxml API is still failing and returning a vague error message.
https://github.com/OfficeDev/office-js/issues/998
Could you please give us an update about it?
