### ISSUE TITLE
setSelectedDataAsync doesn't place the cursor at the end of the added text in outlook web

### ISSUE THREAD

**Issue by amiram** [OfficeDev/office-js#1108]
In outlook web, adding text with setSelectedDataAsync doesn't place the cursor at the end of the added text.
## Expected Behavior

When using setSelectedDataAsync to add text, the cursor should be at the end of the added text.
## Current Behavior

When using setSelectedDataAsync to add text, the cursor is placed at the start of the added text.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Online
* Operating System: Windows and Linux
* Browser (if using Office Online): Chrome

**Comment by exextoc** [comment]
Hello, thanks for reporting this issue. We could reproduce this issue on our end and have added this to our backlog. Unfortunately we dont have any timelines to share this with you.

**Comment by barisbikmaz** [comment]
@exextoc Why is the issue closed when it is not fixed?
We still face this issue on Outlook for Web.

**Comment by exextoc** [comment]
This issue is on our backlog. We unfortunately have no timelines to share at this point

**Comment by lynneosmith** [comment]
This issue is causing a problem for us as well. We are trying to let our users insert individual elements of a report. This is causing undesirable behavior as the user has to keep repositioning the cursor. Also, this problem only occurs on web Outlook. The cursor is correctly placed at the end of the inserted content on desktop Outlook as described. We are trying to add html and see this problem consistently. If you replace the code in ScriptLab "Set selected data" with the following, you will see that in Ourlook on the web, the cursor is left at the beginning of the inserted content and on Outlook on the desktop, the cursor is left at the end of the content. Please reopen this issue and consider resolving.

$("#set-selected-data").click(setSelectedData);

function setSelectedData() {
  Office.context.mailbox.item.setSelectedDataAsync(
    '<h1>This is a heading element</h1>',
    { coercionType: Office.CoercionType.Html },
    function (asyncResult) {
      if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
        console.log("Selected text has been updated successfully.");
      } else {
        console.error(asyncResult.error);
      }
    }
  );
}

**Comment by lynneosmith** [comment]
The html above actually just single quotes around a heading inside an h1 tag. You can replicate this behavior with any simple html.

**Comment by JuaneloJuanelo** [comment]
FYI folks we have a high bug volume and have not been able to get to this one, however our team is re-triaging this bug and hopefully soon we can get the fix out. thanks for your patience.

**Comment by amiram** [comment]
@JuaneloJuanelo Thanks. We really need that. Is there any chance you'll make this lib open-source so we can help with bugs too?

**Comment by mwickens** [comment]
Any update on this @JuaneloJuanelo? We just rolled out new templates functionality in Emailgistics and this issue is affecting our customers...  Thanks.

**Comment by exextoc** [comment]
We have fixed the bug and the fix should be available in build 20220420054 or later.

**Comment by lynneosmith** [comment]
Our web version of Outlook is currently at 16.0.16816.41004. Not sure if the build number you specified is in this build ver?
I tried the following code in ScriptLab and the problem still occurs.

[SampleCode.txt](https://github.com/OfficeDev/office-js/files/12401803/SampleCode.txt)
