### ISSUE TITLE
getAttachmentContentAsync fails with CORS error in OWA with Chrome

### ISSUE THREAD

**Issue by jlevenssfdc** [OfficeDev/office-js#1119]
We are experiencing frequent but intermittent behavior with the getAttachmentContentAsync api.  It fails with CORS error(s) in OWA.

'https://outlook.office365.com/owa/<redactedUserId>/service.svc/s/GetAttachmentDownloadToken?redirect=/owa/<redactedUserId>/service.svc/s/GetFileAttachment<removed>k.&isDownload=true&animation=true&asDataUri=true' (redirected from 'https://attachments.office.net/owa/<redactedUserId>/service.svc/s/GetFileAttachment?<removed>&isDownload=true&animation=true&asDataUri=true') from origin 'https://outlook.office365.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled

## Expected Behavior
getAttachmentContentAsync should not fail

## Current Behavior
getAttachmentContentAsync fails

## Steps to Reproduce, or Live Example
- Install this [addin](https://32b3g.csb.app/OutlookManifest.xml)
- Send an email with attachments
- Open the email with attachments in OWA from sent items
- Open the add-in
- Click the "Get Attachments Only" button

It's possible it will take multiple attempts to recreate but please persist and you should get the failure.  If you need any additional data about the request or response (i.e a cross origin header value)

## Context
We need the attachment content available on the client-side.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: OWA
* Office version number: o365
* Operating System: OSx / Ubuntu
* Browser (if using Office Online): Chrome

**Comment by exextoc** [comment]
@jlevenssfdc Thank you for providing all the details to help us repro the bug. After trying multiple times we are still unable to repro this bug at our end. Can you help with following questions:
1. Does it happen for any specific type of attachments?
2. How often do you see this issue like ones in 5 times or more?
3. Is it possible for you to share sample attachment if it's happening for particular attachments?
4. Does is start happening after few minutes of Add-in being open?

**Comment by jlevenssfdc** [comment]
@exextoc 

1. I've not identified a specific type of attachment
2. Before answering this I ran 10x tests and encountered the error on each one.  I can provide a test account if that would help.
3. Where would you like the files?
4. When it happens, it's immediately.  Add-in has not been open for more than a few seconds.

In testing, are your requests directed towards the same resources as are referenced here with the redirect?

**Comment by exextoc** [comment]
@jlevenssfdc 
Yes, it would help if you could share test account and files. Can you share the details via email at AdeleV@M365x834167.OnMicrosoft.com .
No my requests are not being directed to this resource. 
Before the above mentioned call there should be one more request with GetFileAttachment. Can you shared the request and response for that over the mail as well.

**Comment by jlevenssfdc** [comment]
@exextoc just wanted to make sure you got the email

**Comment by exextoc** [comment]
@jlevenssfdc  We received the email and we are looking into the issue. Thanks for sharing the details.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding getAttachmentContentAsync. We can reproduce the issue reported. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by exextoc** [comment]
Internal tracking id: OutlookWeb:84910

**Comment by clavx** [comment]
The same thing is happening. Here's the information I found out.

In OWA, the `GetAttachmentDownloadToken` is called every 5 minutes. If the `GetAttachmentDownloadToken` is called 3 times after attaching a file, the `getAttachmentContentAsync()` API to get the content of the attachment will fail.

Steps to reproduce:
1. Create a new email or open a draft email
2. Attach the *file (A)*
3. Attach the *file (B)* after the *GetAttachmentDownloadToken (X)* has been called once
4. After the *GetAttachmentDownloadToken (X)* has been called twice:
When calling the `getAttachmentContentAsync()` API to get the content of the *attachment (A)*, the *GetAttachmentDownloadToken (Y)* fails with HTTP status code 401 and the content cannot be obtained.
If you call the `getAttachmentContentAsync()` API to get the content of the *attachment (B)*, you can get the content successfully.
5. After the *GetAttachmentDownloadToken (X)* has been called once:
When calling the `getAttachmentContentAsync()` API to get the content of the *attachment (B)*, the *GetAttachmentDownloadToken (Y)* fails with HTTP status code 401 and the content cannot be obtained.

- (X)
  ```
  HTTP 200
  //outlook.office.com/owa/service.svc?action=GetAttachmentDownloadToken&UA=0&EP=1&app=Mail&n=<sequence>
  ```
- (Y)
  ```
  HTTP 302
  //attachments.office.net/owa/<User>/service.svc/s/GetFileAttachment?id=<FileId>&owa=outlook.office.com&scriptVer=20200907002.05&X-OWA-CANARY=<XSS>&token=<token>&isDownload=true&animation=true&asDataUri=true
  HTTP 401
  //outlook.office.com/owa/<User>/service.svc/s/GetAttachmentDownloadToken?redirect=%2fowa%2f<User>%2fservice.svc%2fs%2fGetFileAttachment%3fid%3d<FileId>%26owa%3doutlook.office.com%26scriptVer%3d20200907002.05%26X-OWA-CANARY%3d<XSS>%26isDownload%3dtrue%26animation%3dtrue%26asDataUri%3dtrue
  ```

Estimated impact:
All emails with attachments  (both drafts and read emails)

Workaround:
Select another email and then come back to it.
However, the same thing recurs after 10-15 minutes.

Context:
Our add-ins use the On-Send feature to retrieve attachments.
This issue means that if you attach an attachment and then take more than 10 to 15 minutes to compose the email, you will not be able to retrieve the contents of the attachment.
Currently the issue cannot be detected on the JavaScript side, so we hope that some kind of response can be made.

**Comment by exextoc** [comment]
Hey @clavx ,

Thanks for the elaborate repro steps. We are investigating this issue and working on a fix.

**Comment by Diegoescalonaro** [comment]
Hi guys. Any update on this? I'm having the same problem

**Comment by bconners1005** [comment]
@exextoc Has this come up as a fix on the roadmap yet?  I am developing a system to use this and to tell them "if it does not work wait 15 minutes or do a full refresh" to fix the problem.

**Comment by pauljereb** [comment]
we seem to have the same problem, not only in OWA though, getAttachmentContentAsync() is not working (anymore?).

**Comment by exextoc** [comment]
Hey,

A fix for the issue has been checked in should be available now. We are now unable to reproduce this issue any more. Can you all confirm the same?

**Comment by clavx** [comment]
I have confirmed the information reported above.
All were resolved.
Thank you for your response.

**Comment by skyhawk92** [comment]
At first it seemed ok for me, but now I am still getting CORS issue on GetAttachmentDownloadToken.
Usually it works for me for about 5 calls to get attachment then it starts failing.

**Comment by jlevenssfdc** [comment]
In testing this using the above add-in / steps I'm not seeing anymore token requests.  If that's the nature of the fix/change please advise, otherwise I'm going to continue to test until I see a few successful token requests.  Thanks!

-- edit: after a short interval I see the token request being made while idle.  The issue should be resolved as it looks to have been removed in lieu of a separate mechanism for making a token available.

**Comment by jlevenssfdc** [comment]
@exextoc We started getting reports of this same issue again.  Request to get the token is failing b/c of CORS.  I thought that request was removed from the flow as the fix?  Any idea on if there has been a regression recently?  Thanks!

**Comment by exextoc** [comment]
There is no such known regression, Also we are not able to repro at our end. Can you please share more details on it?
