### ISSUE TITLE
cell.value = "" returns an error on Typescript.

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#1143]
In TypeScript when I try

let cell = ...// Word.TableCell
cell.value = "" 

I get an (Invalid Argument, If I remember correctly) error. 

But when I use Word.TableRow.insertCells(...), and give "" as part of cells it works. 

I think cell.value = "" should work, and should not raise an error. If it is supposed to raise an error, it should be written in the documentation.

This is tested in Office 365.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2553e9af-d73a-c2dd-319c-af4369671885
* Version Independent ID: 592cc1bf-3043-0c0c-6b00-35d7f41c0a2d
* Content: [Word.TableCell class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/word/word.tablecell?view=word-js-preview)
* Content Source: [docs/docs-ref-autogen/word/word/word.tablecell.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/word/word/word.tablecell.yml)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by MandytMSFT** [comment]
I can repro this issue on word desktop, but word online works fine. @jeremy-msft  could your team have a look ? 
My repro gist: https://gist.github.com/MandytMSFT/a155ac1b139363846e7b63e49ef05a8a

**Comment by hjkim-MSFT** [comment]
Fixed in 16.0.12928.10000 build.

**Comment by hengchengfei** [comment]
still throw error.
![1](https://user-images.githubusercontent.com/3182964/147445163-25047fc5-9e4e-4e36-a428-992f3ccb625c.png)

**Comment by AbidRahman-MSFT** [comment]
Hey @hengchengfei - this issue has been fixed for Office versions greater than 16.0.12928 on M365 subscriptions. The bug will continue to occur on Office 2019 and Office 2016 versions. 

Please use `Word.TableRow.insertCells(...)` to achieve the same workflow on older versions of Office.
