### ISSUE TITLE
Download is disallowed in Google chrome browser

### ISSUE THREAD

**Issue by KantilalJadav** [OfficeDev/office-js#1221]
## Expected Behavior
IFRAME should be allow download in google chrome browser.

## Current Behavior
We have developed outlook add-in for calendar. which will download all appointments from users calendar to excel. We have tested our add-in in all major browsers (IE-11, Firefox-77 and Chrome-83). In IE and Firefox add-in working as expected but Chrome is disallowed to download.

We are getting following message in google chrome console:
Download is disallowed. The frame initiating or instantiating the download is sandboxed, but the flag ‘allow-downloads’ is not set. See https://www.chromestatus.com/feature/5706745674465280 for more details.

So, as per above given links if we inspect the element and update the attribute "sandbox" of the IFRAME with value "allow-downloads" then it is working fine. 
 
As we know that add-in is loading in IFRAME tag, So is there any steps/resolution to update the attribute "sandbox".

**Comment by exextoc** [comment]
We are already aware of this issue and have fixed this. It will take ~1 Weeks for 100% rollout. Please try again next week.

**Comment by KantilalJadav** [comment]
Thanks for such a valuable response.

**Comment by KantilalJadav** [comment]
Great, issue has been resolved.
Thank you.

**Comment by sergez** [comment]
The issue is still reproduced on:
 - Exchange Server 2016 CU 18;
 - Exchange Server 2019 CU 7;
