### ISSUE TITLE
Outlook: emailAddress property returns LegacyExchangeDN format

### ISSUE THREAD

**Issue by clavx** [OfficeDev/office-js#1250]
The emailAddress property of Office.From is returned in LegacyExchangeDN format instead of SMTP email address.

## Expected Behavior

The Office.From emailAddress property is set to the SMTP email address.

Office.EmailAddressDetails interface
https://docs.microsoft.com/en-us/javascript/api/outlook/office.emailaddressdetails?view=outlook-js-1.8#emailaddress

## Current Behavior

The Office.From emailAddress property is set to LegacyExchangeDN.

## Steps to Reproduce, or Live Example

1. Open sent or received mail
2. Select "Resend This Message..." in the File menu
3. Run "Get from (Message Compose)" using Script Lab for Outlook

## Context

Our Office add-in use the SMTP email address to distinguish the sender.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Office 365 ProPlus Version 2006 (Build 13001.20266 Click-to-Run)
* Operating System: Windows 10 Pro, version 1903
* Browser (if using Office Online): Microsoft Edge 44.18362.449.0

**Comment by lindalu-MSFT** [comment]
@clavx Can you please provide your files or screen shots so we can test your repro steps?

**Comment by exextoc** [comment]
Hey @clavx ,

Are you seeing this issue only on Outlook for Windows (Desktop)?

Can you also provide the email that you are getting and that you are expecting?

**Comment by clavx** [comment]
@lindalu-MSFT 

<img src="https://user-images.githubusercontent.com/58804032/86246271-b3670700-bbe5-11ea-99b7-8f4eb0a4ee2d.gif" width="600" />

@exextoc 

> Are you seeing this issue only on Outlook for Windows (Desktop)?

Yes, this occurs in Outlook for Windows (Desktop).

> Can you also provide the email that you are getting and that you are expecting?

Where should I provide it?

**Comment by exextoc** [comment]
I am able to repro this issue *only* if you use the "resend" feature in Outlook. I have opened a bug on the backlog of the product team, but I have no timelines to share at this time. 

Does this match your repro steps? (You only repro this if you resend the email?) 

Is this a normal scenario for your customers/app users? (resending emails from sent items?)

**Comment by clavx** [comment]
> Does this match your repro steps? (You only repro this if you resend the email?)

Yes, it does.

> Is this a normal scenario for your customers/app users? (resending emails from sent items?)

Yes, our customers/app users are resending emails from sent items.

Our Office Add-in uses the On-Send function.

**Comment by exextoc** [comment]
Thanks for the info. We have added this issue to our backlog to address it. Unfortunately, we don't have any timelines to share.

**Comment by clavx** [comment]
@exextoc 
How do I get the SMTP email address from the LegacyExchangeDN?
I would like to know if there is an alternative because it has a significant impact on our add-in.

**Comment by clavx** [comment]
@exextoc 
The bug that the value of the emailAddress property of the Office.From cannot be obtained correctly has not been fixed yet.

We have now confirmed the following behavior:
- When using Resend feature for an email that goes into the outbox after it is sent, the FROM value is retrieved correctly.
- If you quit and restart Outlook and then use the Resend feature on the same email, you will get an incorrect value (LegacyDN).
- Tested version: Version 2011 (Build 13426.20274)

I would like to track the status, will it be posted here after the bug fix is completed?

**Comment by exextoc** [comment]
(Internal Tracking Office:4264741) Unfortunately, I don't have any updates to report, this thread will be updated when the fix happens. It is still on the product team's backlog at this time.

**Comment by JuaneloJuanelo** [comment]
Hey @clavx  we just had a conversation in the team about this issue. Can you please share more details about your scenario and how frequently you find the need to use the resend the feature among your customer base? btw feel free to ping me directly juanbl@microsoft.com to dive into your case. thanks!

**Comment by clavx** [comment]
@JuaneloJuanelo Thank you for your reply.

Our customers have indicated that they use the resend feature in the following cases:
Case 1: They are using it to create emails that are slightly different from the text of the previous email.
For example: creating daily, weekly, and monthly reports
Case 2: When I want to edit and reuse the email text, address and attachments sent by others, I change the From address to my own and resend it.
In case of forwarding, I have to reenter the entire address, but in case of resending, the address is set, so I use the resend function.

In our Outlook add-in, we get the domain of the From address, check the other destinations, and warn if it is a different domain.
Therefore, users who use the resend feature are not able to check the domain correctly and are warned even if they are all on the same domain.

**Comment by clavx** [comment]
@exextoc 
I checked the current status, and this issue no longer occurs except in the Semi-Annual Enterprise Channel.

Am I correct in assuming that this has been fixed? Is there any update?

Work
- Current Channel: Version 2104 (Build 13929.20372)
- Monthly Enterprise Channel: Version 2103 (Build 13901.20516)

Not working (still has issue)
- Semi-Annual Enterprise Channel: Version 2008 (Build 13127.21624)

**Comment by exextoc** [comment]
We have fixed the bug and the fix should be available in build 16.0.13727.10000 or later. When an updated build is available depends on the release channel a customer is on.

**Comment by exextoc** [comment]
I apologize, that due to complications with this fix, the Monthly Channel is indeed fixed for 13727 and later, but the Semi-Annual Enterprise Channel, is NOT fixed in 16.0.13801.XXXXX. It is scheduled to be fixed in the SAC build AFTER 13801.

**Comment by clavx** [comment]
Thank you for letting me know.

**Comment by Ravi060990** [comment]
@exextoc , following up to check the status of this fix for SAEC ? My customer is experiencing the same issue for all migrated mailboxes when they reply to emails from sent items and have on premises mailboxes under TO, CC on Version 2102 (Build 13801.20864) .  Thanks!

**Comment by exextoc** [comment]
Thanks for following up.  The fix will be in the next SAC-T release, sometime in January 2022.

**Comment by clavx** [comment]
@exextoc 
This issue seems to have regressed in Version 2204.
Could you please investigate it?

Confirmed on the Current Channel:
* Works:
  * Version 2203 (Build 15028.20228)
* Does not work:
  * Version 2204 (Build 15128.20178)
  * Version 2204 (Build 15128.20224)

**Comment by clavx** [comment]
@exextoc any updates on this?
We have received inquiries related to this issue.
