### ISSUE TITLE
Word: Office.context.ui.displayDialogAsync is not working in IE 11

### ISSUE THREAD

**Issue by salmanansari-gep** [OfficeDev/office-js#1255]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

We are trying to preview some data in display popup using Office.context.ui.displayDialogAsync, this is working fine in Chrome browser but not working in IE 11

## Expected Behavior
Dialog popup should be open

## Current Behavior
When we click on buttons to open displayDialogAsync having displayInIframe property as true, popup is not getting open
This is working fine in Chrome browser

In Browser console below error message is occurring

"TypeError: Unable to get property 'split' of undefined or null reference 
at getHostnamePortionForLogging (https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:26:14971)
at OSF.DDA.WAC.Delegate.openDialog (https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:26:278651)
at Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:26:80700)
at value (https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:26:255047)"

## Steps to Reproduce, or Live Example
Upload manifest.xml and click on button to open dialogbox

## Code Sample

openDialog() {
        Office.context.ui.displayDialogAsync(window.location.origin + "/src/Dialog.html?oloc=549",
            { height: 50, width: 50, displayInIframe: true }, this.dialogCallback);
    }

## Context
We are try to open dialog box to extend some function for word Add Ins

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.0.13029.41000
* Operating System: Online
* Browser (if using Office Online): Internet Explorer 11

**Comment by seandevenish** [comment]
We are encountering this issue also, including when displayInIframe: false. We have terminal server clients attempting to use our add-in (which uses IE)... we regret ever trying office js for an enterprise app!!

**Comment by fkranenburg** [comment]
We have the same problem. This did work correctly before. This issue should be fixed soon!

**Comment by Petryxasport** [comment]
Issue is relevant also for Chrome! Any news around this?

Issue in another thread was closed without parameter **displayInIframe: true** 
Example below still have problem on Chrome as well:
Office.context.ui.displayDialogAsync(url,
{ height: 50, width: 50, displayInIframe: true }, this.dialogCallback);
}

**Comment by smaremanda** [comment]
@Petryxasport - can you please update this thread with the latest repro steps? Will help our engineering team to debug the issue. thanks!

**Comment by Petryxasport** [comment]
@smaremanda The issue was relevant on Friday 100%. Today everything works on all browsers. This request should be closed.
