### ISSUE TITLE
Outlook Desktop, Outlook for Mac, setSelectedDataAsync produces incorrect formatting for lists

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1510]
In an Outlook add-in for compose mode, we use the Office JS API to fill in email fields. The setSelectedDataAsync method inserts HTML with incorrect markup, the last item in a bulleted or numbered list is inserted as a paragraph instead of a list item.

## Expected Behavior
The setSelectedDataAsync method should work as expected.

## Current Behavior
The setSelectedDataAsync method ignores markup, the last item in a bulleted or numbered list is inserted as a paragraph.

## Steps to Reproduce, or Live Example
Create a new email in Outlook Desktop or Outlook for Mac and execute the code below.

`function setSelectedDataAsyncTest() {`
`  Office.context.mailbox.item.body.setSelectedDataAsync('<ul><li>A</li><li>B</li><li>C</li></ul>', { coercionType : 'html' }, (asyncResult) => {`
`    if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {`
`    }`
`  });`
`}`

Pay attention to the last list item C, it is inserted as a separate paragraph.

* Additional details:
  1. Everything works fine in Outlook Online.

## Your Environment
* Platform: PC desktop, Mac
* Host: Outlook
* Office version number: Outlook Version 2011 (build 13426.20234), Outlook for Mac Version 16.43 (20110804)
* Operating System: Windows 10 version 20H2, macOS Big Sur Version 11.0.1

* Browser (if using Office on the web): 

## Useful logs
- [ x ] Screenshots
![ol-desktop-list-issue](https://user-images.githubusercontent.com/28924916/99533610-37643480-29b7-11eb-841c-a2f6ebdda9cd.png)
![ol-mac-list-issue](https://user-images.githubusercontent.com/28924916/99533629-3df2ac00-29b7-11eb-8a19-c21813b4094a.png)

**Comment by exextoc** [comment]
@DmitryKostochko We can reproduce the issues, while we investigate the root cause.
Can you append `<br />` or any other tag to your content as a work around?

    function setSelectedDataAsyncTest() {
        Office.context.mailbox.item.body.setSelectedDataAsync(
             '<ul><li>A</li><li>B</li><li>C</li></ul><br />', 
             { coercionType : 'html' }, (asyncResult) => {
             if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {}
         });
    }

**Comment by DmitryKostochko** [comment]
@exextoc, thank you for a quick turnaround!

>> Can you append <br /> or any other tag to your content as a work around?

Sorry, we cannot modify the content.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding setSelectedDataAsync() API. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by fiftydegrees** [comment]
Hi @exextoc, the issue is still happening; is fixing this issue still in the roadmap?

**Comment by exextoc** [comment]
We have fixed the bug and the fix should be available in build 16.0.13708.10000 or later. When an updated build is available depends on the release channel a customer is on.

**Comment by fiftydegrees** [comment]
Unfortunately we can still experience the issue (macOS, Outlook version 16.58 build 22012401). Plese find enclosed a screencast of our product with the issue enabled (the ordered list is not preserved while we just get and set the body).

https://user-images.githubusercontent.com/5269843/150978313-03dd5a2a-cb55-49e0-9b3d-101978643eac.mp4

.
