### ISSUE TITLE
`Can't find variable: OfficeRuntime` for Word in iOS

### ISSUE THREAD

**Issue by els-ts** [OfficeDev/office-js#1521]
In our New Relic reporting tool we get this error:
`Can't find variable: OfficeRuntime` that comes from the iPad devices.

## Expected Behavior
No error being thrown.

## Current Behavior
`Can't find variable: OfficeRuntime` is thrown in  https://appsforoffice.microsoft.com/lib/1.1/hosted/word-ios-16.00.js

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: **iOS**
* Host [Excel, Word, PowerPoint, etc.]: **Word**
* Office version number: **unknown**
* Operating System: **iPadOS**
* Browser: **Safari 10-14**

**Comment by JiayuanL** [comment]
Hi @els-ts, thanks for reaching, could you please let us know what API are you using under OfficeRuntime object? Is your ios scenario newly enabled? Or is has been working but ran into issue recently? Thanks.

**Comment by frasparacio** [comment]
I'm experiencing the same problem under Outlook iOs Add-in. 
It is a new add-in, it is working correctly under desktop and web client.
I could get more info through ApplicationInsights on client and I'm having the same error "Can't find variable: OfficeRuntime" when I try to get an access token (OfficeRuntime.auth.getAccessToken)

Edit: I've updated my code not to use OfficeRuntime.auth that looks deprecated instead I'm using now Office.context.auth.getAccessTokenAsync but still no luck, looks like auth is undefined under iOS

**Comment by AbidRahman-MSFT** [comment]
Hey @frasparacio - you are correct. The Auth APIs are currently not supported for iOS. You can see the full list of supported platforms here: https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/identity-api-requirement-sets

The team is working on bringing auth scenarios to additional platforms, so stay tuned! Keep an eye on the developer blogs for updates: https://developer.microsoft.com/en-us/office/blogs/technology/add-ins/

**Comment by els-ts** [comment]
@JiayuanL - sorry for the long reply...

Unfortunately I cannot answer your questions as fully as I would like to, because the error is thrown in the script belonging to your domain and due to browsers safety restrictions I'm unable to get stack traces. This is the most common error we can see in our New Relic reports. We haven't yet found its origin in our code.

As far as our reports are reaching this shown around March 2020 (though there's a chance that this is just the limit our reports can reach).

This is all we can see about this error: 
![image](https://user-images.githubusercontent.com/47317754/106620604-a2121e80-6569-11eb-81a3-c9d7d0c9b514.png)

We're not using directly any of the OfficeRuntime API's and we're also not using Auth API in our add-in.

**Comment by AbidRahman-MSFT** [comment]
This has been fixed in version 13822.10000. We will keep the issue open until we can verify the fix in a production environment.

Note: If you go to https://appsforoffice.microsoft.com/lib/1.1/hosted/word-ios-16.00.js, you can check the current prod version (which is 13426.10000).

**Comment by els-ts** [comment]
Thank you 🤩 

I'll keep an eye on the version number and our metrics and let you know if something changed

**Comment by els-ts** [comment]
@AbidRahman-MSFT - as far as I understand, the current release has the version number `13903.10000`, which should include the fix, however we are still seeing this problem in our reports.

Is this just the case that it haven't been yet released to all users or there's some more calls to this API in your code?

**Comment by els-ts** [comment]
I suppose, that this issue have been fixed 🎉   I can confirm that since the 1st of April we have no error reports regarding this message.

Thank you all for taking care of it 🏆
