### ISSUE TITLE
Office.context.ui.messageParent not working on Mac in desktop excel

### ISSUE THREAD

**Issue by reidbill** [OfficeDev/office-js#1843]
When I call Office.context.ui.messageParent from an async dialog, the message is never received. This only fails on the Mac in Excel desktop. The code works fine in windows desktop excel, windows web excel (Edge, Chrome, Firefox) and Mac Web Excel (Safari, Chrome).

## Expected Behavior

I expect the message to be received in the Parent (task pane app) running within excel

## Current Behavior

Nothing happens, I debug into the code in the dialog and step over
Office.context.ui.messageParent(true),
but the code in the parent that receives the message does not execute.

## Steps to Reproduce, or Live Example
It is easy enough to reproduce, 
in our webapp, we call 
Office.context.ui.displayDialogAsync(
      dlgUrl,
      { promptBeforeOpen: false, height: height, width: width },
      (result) => {
        // this function is a callback in case the dialog doesn’t open (result.value === undefine and then there should be a result.error
        if (result.value) {
          this.prefsDialog = result.value;
          this.prefsDialog.addEventHandler(Office.EventType.DialogMessageReceived, () => {
            this.closeDialog(onClose);
          });
        } else {
          // error handling goes here
        }
      }
    );

the dlgUrl is the same as our webapp, but with a query param like &dlg=prefsDlg
Then inside index.tsx, we check for the param and if present, show the dialog
const dt: DialogTemplate = DialogTemplate.getInstance();
dt.showDialog(dialogType.prefDialog);

inside the prefDialog we have a cancel button that calls
messageParent(true) so we can close the dialog, but that message is not received in the parent.
Only on Mac Desktop

## Context

user is unable to save or close dialog with the buttons we provide

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Only fails on Mac desktop excel
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: mac desktop Excel version is 16.46 (21021202)
* Operating System: Big Sur 11.2.3
* Browser (if using Office on the web): ______

**Comment by honxmsft** [comment]
Hi, can you try this on your Mac again? The team closed the flight causing this problem. It should work now.

**Comment by reidbill** [comment]
This is still a problem for us. I updated Excel on the Mac to 16.48 (21041102) and cleared out the cache following instructions here, https://docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache and I am still not getting the message in the parent. Is there anything else I need to do?

**Comment by pkkj** [comment]
Hi. I am not able to repro this issue under Excel Mac. 

You may run a simple test in your environment to identify whether the API is working correctly. I create a very simple test add-in and you can find the manifest here:
https://pkkj.github.io/manifest/TwoWayMessageDialogTest.xml
Please read the source code to ensure that you trust the code of the add-in before side loading it: 
https://pkkj.github.io/agavetest/dialog-taskpane.html
In this test add-in, you could click "LaunchDialog" to launch the dialog. It's similar to your scenario that it re-uses the taskpane's URL as dialog URL, with a URL parameter. Clicking "SendMessageToParent" will send a message to the parent's textbox. If the text box is empty, the parent will close the dialog (like your add-in). 

Thanks.

**Comment by reidbill** [comment]
Can you send me a link to the source for your addin? Yours is working so I'd like to see what we are doing differently to make ours fail only on mac desktop. thanks

**Comment by reidbill** [comment]
nevermind, it is all contained in the .html file I can view it via the debugger window

**Comment by reidbill** [comment]
I see the problem. On Excel desktop for the mac, you can't send a boolean value in the message. I changed true to "true" for my message and it worked. The docs say you can send either a boolean or a string so you might want to leave this open to fix or change the docs. booleans do work everywhere else.

**Comment by lliu113** [comment]
@reidbill - happy to hear the issue is now resolved! We will work to update the documentation, thanks for flagging this. I'm going to go ahead and close this issue, feel free to reactivate if you have any additional questions/feedback.

**Comment by pkkj** [comment]
It seems it's OK to send a boolean. I modify my test add-in mentioned in my previous thread. Now if you click the "SendMessageToParent" without input, it will send "true" to the parent. And parent will close the dialog if it receives "true". The taskpane also outputs the type of the message from the child in the text area, to verify that it's a boolean type.

Thanks
