### ISSUE TITLE
getAttachmentContentAsync() returns '7000' error in "New Outlook" 16.49 for macOS Big Sur

### ISSUE THREAD

**Issue by eat-sleep-code** [OfficeDev/office-js#1871]
The `getAttachmentContentAsync()` method can't get the attachment value. This bug appears only in “New Outlook” for macOS Bug Sur.   

---

**This is essentially the same as the issue [here](https://github.com/OfficeDev/office-js/issues/1610).    In the comments of this issue, it indicated that this was part of Requirement Set 1.8.   However, it does not yet appear to be resolved**   

---

[This document](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets) indicates that 1.8 is included in the latest release.

However, if I set the manifest file to have `DefaultMinVersion` and `MinVersion` of **1.8** and install the module, it indicates it has installed successfully but then immediately disappears from the list.   If I set the manifest file to have `DefaultMinVersion` and `MinVersion` of 1.7, it indicates it has installed successfully and continues to remain visible.   However, the `getAttachmentContentAsync()` does not work in 1.7.

## Expected Behavior
Attachment successfully loaded, base64 can be obtained from result.value.content.

## Current Behavior
Attachment not loaded:
code: 7000
message: "You don't have sufficient permissions for this action."
name: "Permission Denied"

## Steps to Reproduce, or Live Example
1. On a Mac, running Big Sur 11.3.1 with Outlook 16.49 (21050901), switch to "New Outlook"
2. Paste code:
```
const firstAttachment = Office.context.mailbox.item.attachments[0];

Office.context.mailbox.item.getAttachmentContentAsync(
    firstAttachment.id,
    {},
    function(result) {
      console.log(result);
    }
);
```
3. Select an email with at least one attachment.
4. Open add-in.
5. View console.

## Context
We have a custom add-in that does not function in new Outlook for Mac.   Asking users to switch to the legacy Outlook is going to be prone to folks insisting they have even if they haven't and then the add-in won't work.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Outlook 16.49 (21050901)
* Operating System: macOS Big Sur 11.3.1

## Useful logs
![](https://user-images.githubusercontent.com/43299774/105628087-8741fa80-5e43-11eb-982e-4f1118e2cd36.png)

**Comment by eat-sleep-code** [comment]
Adding the following code to my add-in results in the defined error being thrown:

```
if (Office.context.requirements.isSetSupported('Mailbox', '1.8') == false) {
    console.error('Requirement set 1.8 is not supported!');
}
```
So, the documentation indicating that 1.8 is part of the new UI appears to be incorrect -- as is the prior posting that it would be supported in March 2021.

**Comment by exextoc** [comment]
@eat-sleep-code This issue is fixed now. Can you please check and confirm? If the issue still repros, please provide the diagnostics ID by clicking on Help->Collect Diagnostics.

**Comment by eat-sleep-code** [comment]
@exextoc Unfortunately, I am still having the issue.   Diagnostics ID: BBDJCXK3

**Comment by eat-sleep-code** [comment]
@exextoc  Do you need any further information from me?

**Comment by exextoc** [comment]
Hi @eat-sleep-code can you please try restarting and then try this again? This issue is fixed but you may need to restart before the changes are picked.

**Comment by eat-sleep-code** [comment]
@exextoc I have restarted Outlook, also rebooted the whole Mac as just applied the latest macOS patch, still the same errors occurring.

macOS Big Sur 11.4 (20F71)
Outlook: 16.49 (21050901)

I still see `Requirement set 1.8 is not supported` from my above debug console output.

**Comment by eat-sleep-code** [comment]
@exextoc  Would it be helpful to see the manifest file to see if there is something wrong there?

**Comment by exextoc** [comment]
> @exextoc Would it be helpful to see the manifest file to see if there is something wrong there?

Yes please help us with the manifest.

**Comment by eat-sleep-code** [comment]
@exextoc  See below, from our local development instance:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="MailApp">
	<!-- Begin Basic Settings: Add-in metadata, used for all versions of Office unless override provided. -->
	<!-- IMPORTANT! Id must be unique for your add-in, if you reuse this manifest ensure that you change this id to a new GUID. -->
	<Id>9dc75167-df18-43c3-884f-0e3a67bf8b6c</Id>
	<!--Version. Updates from the store only get triggered if there is a version change. -->
	<Version>0.1.6</Version>
	<ProviderName>connerc</ProviderName>
	<DefaultLocale>en-US</DefaultLocale>
	<!-- The display name of your add-in. Used on the store and various places of the Office UI such as the add-ins dialog. -->
	<DisplayName DefaultValue="BY Email Templates- DEV" />
	<Description DefaultValue="Create formatted Emails from Marketo Designs" />
	<!-- Icon for your add-in. Used on installation screens and the add-ins dialog. -->
	<IconUrl DefaultValue="https://localhost:3000/assets/icon-32.png" />
	<HighResolutionIconUrl DefaultValue="https://localhost:3000/assets/icon-80.png" />
	<!--If you plan to submit this add-in to the Office Store, uncomment the SupportUrl element below-->
	<SupportUrl DefaultValue="https://localhost:3000/support.html" />
	<!-- Domains that will be allowed when navigating. For example, if you use ShowTaskpane and then have an href link, navigation will only be allowed if the domain is on this list. -->
	<!--<AppDomains>
		<AppDomain>AppDomain1</AppDomain>
		<AppDomain>AppDomain2</AppDomain>
		<AppDomain>AppDomain3</AppDomain>
	</AppDomains>
	-->
	<!--End Basic Settings. -->
	<Hosts>
		<Host Name="Mailbox" />
	</Hosts>
	<Requirements>
		<Sets>
			<Set Name="Mailbox" MinVersion="1.7" />
		</Sets>
	</Requirements>
	<FormSettings>
		<Form xsi:type="ItemRead">
			<DesktopSettings>
				<SourceLocation DefaultValue="https://localhost:3000/index.html" />
				<RequestedHeight>250</RequestedHeight>
			</DesktopSettings>
		</Form>
	</FormSettings>
	<Permissions>ReadWriteItem</Permissions>
	<Rule xsi:type="RuleCollection" Mode="Or">
		<Rule xsi:type="ItemIs" ItemType="Message" FormType="Read" />
	</Rule>
	<DisableEntityHighlighting>false</DisableEntityHighlighting>
	<VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
		<Requirements>
			<bt:Sets DefaultMinVersion="1.7">
				<bt:Set Name="Mailbox" />
			</bt:Sets>
		</Requirements>
		<Hosts>
			<Host xsi:type="MailHost">
				<DesktopFormFactor>
					<!-- Location of the Functions that UI-less buttons can trigger (ExecuteFunction Actions). -->
					<FunctionFile resid="Commands.Url" />
					<!-- Message Read -->
					<ExtensionPoint xsi:type="MessageComposeCommandSurface">
						<!-- Use the default tab of the ExtensionPoint or create your own with <CustomTab id="myTab"> -->
						<OfficeTab id="TabDefault">
							<!-- Up to 6 Groups added per Tab -->
							<Group id="msgReadGroup">
								<Label resid="GroupLabel" />
								<!-- Launch the add-in : task pane button -->
								<Control xsi:type="Button" id="msgReadOpenPaneButton">
									<Label resid="TaskpaneButton.Label" />
									<Supertip>
										<Title resid="TaskpaneButton.Label" />
										<Description resid="TaskpaneButton.Tooltip" />
									</Supertip>
									<Icon>
										<bt:Image size="16" resid="Icon.16x16" />
										<bt:Image size="32" resid="Icon.32x32" />
										<bt:Image size="80" resid="Icon.80x80" />
									</Icon>
									<Action xsi:type="ShowTaskpane">
										<SourceLocation resid="Taskpane.Url" />
									</Action>
								</Control>
								<!-- Go to http://aka.ms/ButtonCommands to learn how to add more Controls: ExecuteFunction and Menu -->
							</Group>
						</OfficeTab>
					</ExtensionPoint>
					<!-- Go to http://aka.ms/ExtensionPointsCommands to learn how to add more Extension Points: MessageRead, AppointmentOrganizer, AppointmentAttendee -->
				</DesktopFormFactor>
			</Host>
		</Hosts>
		<Resources>
			<bt:Images>
				<bt:Image id="Icon.16x16" DefaultValue="https://localhost:3000/assets/icon-16.png" />
				<bt:Image id="Icon.32x32" DefaultValue="https://localhost:3000/assets/icon-32.png" />
				<bt:Image id="Icon.80x80" DefaultValue="https://localhost:3000/assets/icon-80.png" />
			</bt:Images>
			<bt:Urls>
				<bt:Url id="Commands.Url" DefaultValue="https://localhost:3000/commands.html" />
				<bt:Url id="Taskpane.Url" DefaultValue="https://localhost:3000/index.html" />
			</bt:Urls>
			<bt:ShortStrings>
				<bt:String id="GroupLabel" DefaultValue="BY Email Templates- DEV" />
				<bt:String id="TaskpaneButton.Label" DefaultValue="Create Email" />
			</bt:ShortStrings>
			<bt:LongStrings>
				<bt:String id="TaskpaneButton.Tooltip" DefaultValue="Opens a pane displaying all available properties." />
			</bt:LongStrings>
		</Resources>
	</VersionOverrides>
</OfficeApp>

```

**Comment by eat-sleep-code** [comment]
@exextoc Were you able to find any issues in the Manifest, or any indication why this is failing?

**Comment by exextoc** [comment]
Hey @eat-sleep-code ,

Sorry for the delay. Since your manifest does not contain a hosted endpoint we could not test it out. However, We have tested your original repro steps in Big Sur 11.4 with Outlook Version Outlook 16.49 (21050901) on New Outlook and it seems to work fine (the issue does not reproduce). We tried to replicate your scenario in an add-in with the same Mailbox permissions, but that too works as expected.

Also, running `Office.context.requirements.isSetSupported('Mailbox', '1.8')` on the setup above comes up as `true`.

Could you please host your add-in online and share your manifest if possible? Is there any way you could see if this is working for a different user?

**Comment by eat-sleep-code** [comment]
@exextoc : Two separate users, encountered same issue.  Do you have a method to send you the hosted endpoint information without sharing the information publicly with the world? :)

**Comment by exextoc** [comment]
Please email it to OutlookAddins@M365x693897.onmicrosoft.com.

**Comment by exextoc** [comment]
We are not able to reproduce this issue with the manifest shared . If the issue still repros , please provide the diagnostics ID by clicking on Help->Collect Diagnostics .Can you also try to install Script Lab and share code snippet to test API separately.

**Comment by eat-sleep-code** [comment]
16.50 became available on the current channel and appears to have fixed the issue. 

Awaiting for a colleague to confirm it is working for them too.

**Comment by exextoc** [comment]
Please reopen the issue if you still face the problem.
