### ISSUE TITLE
When debugging with the Edge DevTools the add-in reloads

### ISSUE THREAD

**Issue by LeonardoBSantos** [OfficeDev/office-js#1965]
I'm developing an excel add-in. Two days ago, I debugged in edge dev tools like the expected behavior. Today, the add-in is reloading 5 seconds after that I try to debug.

I tried the solution of this document:

[Troubleshooting Microsoft Edge issues](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)

First, I opened the registry editor and created a new key in "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\16.0" called "Wef". Then, I created a DWORD with the name: AlertInterval and the value: 00000000

So, I restarted the computer but the error still happens.

* Platform: PC Desktop
* Host: Excel
* Office version number: office 365 MSO (16.0.13929.20222) 64 bits
* Operating System: Windows 10
* Browser:  Edge Version 90.0.818.51 Up to date (with WebView 2)
 
## Expected behavior
Debug the Add-In with Devtools normally.

## Current behavior
The add-in is reloading 5 seconds after that I try to debug.

## Steps to reproduce
1. Sideload the Add-In on Excel desktop
2. Right-click button in the task pane
3. Inspect to open dev tools

## Useful logs
![reloading](https://user-images.githubusercontent.com/68254666/123889177-5488ba80-d92b-11eb-9dd7-689635f1c450.png)

**Comment by wh1t3cAt1k** [comment]
We're also experiencing the issue on Excel Desktop for Windows. 

On the Excel for Web side of things, we keep experiencing https://github.com/OfficeDev/office-js/issues/1975 , so in conjunction with this issue it means that our engineers are completely blocked from debugging the add-in at the moment.

**Comment by Dengshan2018** [comment]
Please try latest webview2 runtime version. The issue should be fixed 92.0.902.+. usually, webview2 runtime is auto updated. if not, please reinstall from https://developer.microsoft.com/en-us/microsoft-edge/webview2/

**Comment by wh1t3cAt1k** [comment]
Hi guys. I confirm it is fixed. Many thanks for the update and the fix!

**Comment by HelenNeigel** [comment]
Hi guys, looks like the issue is back:

Office version number: Microsoft® Excel® for Microsoft 365 MSO (16.0.14326.20782) 64-bit 
Operating System: Windows 10
Browser: Microsoft Edge Version 98.0.1108.62 (Official build) (64-bit)

**Comment by Dengshan2018** [comment]
@HelenNeigel, could you confirm the version of webview2 runtime (the version of msedgewebview2.exe)? though browser version and webview2 runtime version are same in most of cases.

**Comment by HelenNeigel** [comment]
Microsoft Edge WebView2 Runtime 98.0.1108.56

**Comment by Dengshan2018** [comment]
Thanks @HelenNeigel. I can't repro so far. any special steps or only repo on specific add-ins?

**Comment by HelenNeigel** [comment]
I experience the issue with other add-ins as well, for example Script Lab. I tried the suggested registry key, maybe some other settings should be updated?

**Comment by Dengshan2018** [comment]
@HelenNeigel , could you add the repro steps for Script Lab? I played with it. Didn't experience any add-in reload.

**Comment by HelenNeigel** [comment]
Please find attached video with Script Lab example - inspect elements or attach debugger open DevTools, the window is closed after 3-5 sec by itself.

https://user-images.githubusercontent.com/7814226/157154905-418f563c-4e77-4c4b-95b4-7bfd7144a271.mp4

**Comment by Dengshan2018** [comment]
@HelenNeigel , did you repro with the version of 99.0.1150.*?

**Comment by HelenNeigel** [comment]
Yes, the webview2 is of the newest version.
![image](https://user-images.githubusercontent.com/7814226/157159394-b69082a7-3909-4058-8524-5d8a9d8a5045.png)

**Comment by Dengshan2018** [comment]
I tried on a few different machines. I can't repro the refresh after launch devtool.
@HelenNeigel , did you repro the issue on different machines? There might be some important condition missing for the repro.

**Comment by Dengshan2018** [comment]
@HelenNeigel is there any crash dump for msedgewebview2.exe?

**Comment by HelenNeigel** [comment]
@Dengshan2018 I tried a different machine. All work there as expected. Not sure what causes the issue on my machine. I'll try to investigate. Thank you for your help.

**Comment by Dengshan2018** [comment]
@HelenNeigel thanks for the update. will see any more updates. or crash dump for msedgewebview2.exe
