### ISSUE TITLE
iOS Outlook add-ins - unrecoverable lock-up breaks all add-in usage (and maintenance)

### ISSUE THREAD

**Issue by gitcnd** [OfficeDev/office-js#2139]
The iOs Add-in UI has three logic errors:
1. The "manage add-ins" button is not shown while add-ins are "initializing" - making it impossible to remove add-ins without "initializing" them first.
2. If *any* add-in fails to load/initialize for any reason, *all* add-ins (and the manage option) are permanently blocked.
3. Add-ins installed in iOS do NOT show up as being installed when loading Outlook in a browser on my Macbook (so they cannot be removed that way either).

## Your Environment

* Platform: iPad 
* Host: Outlook
* Office version number: current (using the iOS app)
* Operating System: current
 
## Expected behavior
1. The "manage add-ins" button should *always* be available.
2. My add-in, and any others, should always work, even if any other add-in fails to load/initialize.

## Current behavior
1. button does not show until addins are "initialized".
2. no add-ins are available if any add-in load/initialize fails.

What is required:
1. Adjust the UI so that the "initializing" animation does NOT remove/obscure the mange icon
2. Adjust the logic so that any add-in load failures do not cause the animation to continue forever (while obscuring all icons)
3. *and* Adjust the loading logic so that some reasonable minimum time-out for loading is observed - I've left it for more than an hour several times, and it never ends.
4. Make sure the "Add-Ins for Outlook" window, under the "My add-ins" tab properly lists *ALL* the Add-Ins installed in our accounts, no matter what platform they were installed from, and allows (at least) their removal.  This must include Mobile add-ins, even when I'm not currently using a mobile platform.

## Steps to reproduce
1. on iPad's Outlook iOS app, open a mail, click the "...", and pick the add-in option at the top 
2. install 6 or more random add-ins (I forget which ones I picked - but it included MojiLaLa, Gfycat, Evernote, Report-Message, Report-Phishing, FedEx and a few others)
3. Use some of them
4. Go to a new email
5. Try to use them again
6. (step 5 failed for me) - close and re-open outlook
7. Try to use any add-in (fails every time for me)
8. Try to remove any add-in (blocked)

## example

<img width="289" alt="Screen Shot 2021-09-23 at 7 47 06 pm" src="https://user-images.githubusercontent.com/4301826/134487014-8bbeac3f-9526-47c8-9a10-aa67ec080cd5.png">

# Provide additional details
1. The add-ins worked the first time I tried after loading them.  They never worked anytime after that.
2. Gfycat did not work (blank screen) when I tried it.  This might be triggering the bugs?
3. MojiLaLa worked fine (1 time) right after Gfycat failed, then from there - blocked.

## Context
I'm attempting to work out why my add-in is not side-loading into iOS, so I tried loading some other add-ins to check if any of them work at all.  Thereupon, I hit this showstopper.

Note: my macbook OWA does *not* list the add-ins that I installed and used in iOS.  

I need the Add-Ins option in iOS to work again, so I can continue attempting to debug and sideload my app for testing, prior to submitting it to AppSource.

Note also: because I can no longer load the Add-Ins in iOS, I cannot remember exactly what the name of the button (that's not showing anymore) was called - I *think* it said "manage add-ins" - I'm not sure.  It's the icon that appears in the top-left corner when you click the "..." icon when reading an email.

**Comment by gitcnd** [comment]
Update.
I installed Outlook on my iPhone.  More bugs:-

1. No add-ins at all showed up when I logged in to my account on my iPhone
2. I uninstalled and reinstalled one of the add-ins (MojoLaLa) on both my iPhone and my Macbook (OWA)
3. After quitting and restarting Outlook on the iPhone - *all* the apps I had loaded on my iPad suddenly showed up.
4. on my iPhone, I uninstalled all of them
5. This did not fix my iPad (still blocks at "initializing" - even after I exit and re-start Outlook on it).

If you need the full list of apps I had installed - let me know. I did screenshots of everything.

**Comment by exextoc** [comment]
Thanks for reporting this. We are working on priority for the issue "Your add-ins are initialising" and addin sometimes not available after login. It will be helpful if you can provide us diagnostics log. The steps are:
1. Open the app
2. Open the mail drawer
3. Tap the Settings button
4. Tap Help & Feedback
5. Tap Collect Diagnostics
6. Tap Get Started
7. Tap Collect Logs
8. Wait for the collection to complete
9. Provide us incident ID.

A few clarification in the meantime. 
The initializing message is to get the details of all the addins enabled for the user. It. doesn't try to initialise the individual addins. 
Side loading of addins is currently not supported on mobile. You can Sideload it using Web outlook or Windows/Mac.
Once you have installed an addin, it will be automatically supported on all the supported platforms.

**Comment by gitcnd** [comment]
I'll do that tomorrow (it's late here).  FYI - Side-loading is not working in iOS: Android, Yes, but not iOS.  See https://github.com/OfficeDev/office-js/issues/2141

**Comment by gitcnd** [comment]
I rebooted my iPad - problem still present.
Incident ID is 565PTJMG

**Comment by exextoc** [comment]
We are going through the incident ID and working on providing a fix. Meanwhile, you can try to reset the account from settings -> Mail Account -> Reset Account

**Comment by gitcnd** [comment]
Can you please find and remove this bug?

There is *no way* to fix this problem at my end.  I've tried:
1. resetting the app from settings
2. deleting my mail account and re-adding it
3. resetting the app, *and* deleting my account, *and* uninstalling the outlook app, then re-installing, re-adding my account.

Nothing I try solves the problem.

If this is happening to me, now, it will be happening to other people as well, and will affect my customers in the future too most likely.

The problem seems only present on my iPad.  Outlook on my iPhone is OK.

**Comment by gitcnd** [comment]
I noticed, when resetting my app, that in the "Setting" screen, this is also a setting page labelled "Add ins" - this too locks up, the same as the add-in menu when clicking on the "..." from an email.

**Comment by exextoc** [comment]
We are working on this on priority and will update once fix will be available.

**Comment by exextoc** [comment]
Fix will be available to users after 2 weeks.

**Comment by exextoc** [comment]
Update: The fix is available. Request you to confirm this.

**Comment by readnotify** [comment]
I see no difference - my iPad is still locked-up.
I have force-closed outlook and re-opened - also still locked up.

How do we get the fix - do we need to update something manually ?

**Comment by gitcnd** [comment]
Still not working for me. What are the steps to apply the fix?

**Comment by exextoc** [comment]
Hey @gitcnd ,

Can you please check what the version of your Outlook for iOS is? This fix has been available since 4.2142.0 onwards. If possible, please try to add your accounts again to Outlook.
