### ISSUE TITLE
Unable to return error in dynamic array

### ISSUE THREAD

**Issue by djaeger-inercomp** [OfficeDev/office-js#2174]
I have been working with errors in custom functions for quite a while now, and since last week I always get a #VALUE error when the dynamic array that I return contains an Error.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2109 (Build 14430.20270), Microsoft 365 Apps for business
* Operating System: Windows 10 Version	10.0.19042 Build 19042
 
## Expected behavior
Dynamic array spills over some cells and shows error in cells where an error exists.

## Current behavior
The dynamic array does not spill over the cells and always shows a #VALUE error if an error exists in one of the cells of the dynamic array.

## Steps to reproduce
To reproduce the error: I created a custom function in the same way as here explained in the section "Handle errors when working with dynamic arrays":  https://docs.microsoft.com/ro-ro/office/dev/add-ins/excel/custom-functions-errors?view=office-js#the-customfunctionserror-object 

## Context
I am using dynamic arrays to print dates and prices next to each other, if on a certain date there exists no price, I want to print #NV in the cell.

**Comment by chiz-ms** [comment]
Thank you for reporting this issue regarding Custom Function Error. ADO#5493908 is opened in our backlog to track this issue.

**Comment by jiju-MS** [comment]
Could you share more details with us about this issue? we'd like to know whether you are working on shared-runtime Custom Function or not.

**Comment by djaeger-inercomp** [comment]
Yes I am using a shared runtime.

**Comment by djaeger-inercomp** [comment]
Hello,
The issue has now been fixed for quite some time, but since the newest Excel update I get the same error again.

**Comment by jiju-MS** [comment]
Hi, could you share the Excel version number which have this error with us? we check the recent excel and seems it works well

**Comment by djaeger-inercomp** [comment]
My current Excel Version is 2111 (Build 14701.20262)

**Comment by djaeger-inercomp** [comment]
Do you have any update on this issue?

**Comment by jiju-MS** [comment]
Hi, @djaeger-inercomp, could you update the excel to the latest version and try again? It should work on the latest version of excel. If still not, could you share the sample code of your scenario to us?

**Comment by djaeger-inercomp** [comment]
Hi, @jiju-MS, I updated Excel and it is still not working. I created a sample shared runtime project following the instructions in the docs and I added a custom function which returns a dynamic array containing errors, I created a public github repo which can be found here: https://github.com/DavidJaeger10/Excel-shared-runtime-add-in

**Comment by djaeger-inercomp** [comment]
The excel version I currently have is Version 2201 (Build 14827.20192)
My current windows version is: Windows 10 Pro, Version 21H2, Build 19044.1526

**Comment by djaeger-inercomp** [comment]
> Hi, @jiju-MS, I updated Excel and it is still not working. I created a sample shared runtime project following the instructions in the docs and I added a custom function which returns a dynamic array containing errors, I created a public github repo which can be found here: https://github.com/DavidJaeger10/Excel-shared-runtime-add-in

Did you try if this project works on your side?

**Comment by djaeger-inercomp** [comment]
Do you have an update on this issue?

**Comment by jiju-MS** [comment]
Hi, djaeger, the issue has been fixed on PROD and it should be working on the newer version of Excel. you can try your function with Scriptlab add-in to see whether is works(which is a play ground for Custom Function and API). it will return 1, #value and 3 as dynamic array like below:
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/49672568/163540045-93400bc1-a9f0-4594-8c80-6f233d9394a0.png)

**Comment by djaeger-inercomp** [comment]
Hello, jiju, I tried it with ScriptLab on Version 2203 but it still does not work

**Comment by grangeryy** [comment]
@djaeger-inercomp are you still seeing the error in your version?

**Comment by djaeger-inercomp** [comment]
Hi grangeryy, unfortunately this error is still present

**Comment by JinghuiMS** [comment]
Add @jiju-MS for awareness, please take care of this customer issue!

**Comment by jiju-MS** [comment]
Hey, Djaeger-inercomp, could you share the code you used in scriptlab about this issue? we can try it on our environment.

**Comment by djaeger-inercomp** [comment]
Hi @jiju-MS, the function that I use in Scriptlab is the following
![scriptlab](https://user-images.githubusercontent.com/77481781/182100488-79248c6b-3d90-4499-97c9-cff6b51eccd9.PNG)

**Comment by ayush-meghwani-28** [comment]
Hiello @djaeger-inercomp, thank you for reporting this and sorry for the delay in getting back to you!

I've investigated this thoroughly and tested across multiple machines on the latest Excel version and I want to report that the behavior is now working as expected. Arrays containing `CustomFunctions.Error` objects correctly spill with per-cell errors rather than showing `#VALUE!` on the entire cell.

Now could you try the following test functions in a **shared runtime** addin (see note below) and let me know if the issue still reproduces on your end?

```typescript
// Sync: should spill [1, #NUM!, 3] across 3 rows
/** @customfunction ARRAY_ERR_SYNC @returns {any[][]} */
function arrayErrSync(): any[][] {
  return [[1], [new CustomFunctions.Error(CustomFunctions.ErrorCode.invalidNumber)], [3]];
}

// Async: same as above but via Promise
/** @customfunction ARRAY_ERR_ASYNC @returns {Promise<any[][]>} */
async function arrayErrAsync(): Promise<any[][]> {
  return [[1], [new CustomFunctions.Error(CustomFunctions.ErrorCode.invalidNumber)], [3]];
}

// Mixed types: should spill ["hello", #N/A, 42]
/** @customfunction ARRAY_MIXED @returns {any[][]} */
function arrayMixed(): any[][] {
  return [["hello"], [new CustomFunctions.Error(CustomFunctions.ErrorCode.notAvailable)], [42]];
}

// All error types: 5-row x 2-col — col A = index, col B = error
/** @customfunction ARRAY_ALL_ERRORS @returns {any[][]} */
function arrayAllErrors(): any[][] {
  return [
    [1, new CustomFunctions.Error(CustomFunctions.ErrorCode.invalidValue)],
    [2, new CustomFunctions.Error(CustomFunctions.ErrorCode.notAvailable)],
    [3, new CustomFunctions.Error(CustomFunctions.ErrorCode.divisionByZero)],
    [4, new CustomFunctions.Error(CustomFunctions.ErrorCode.invalidNumber)],
    [5, new CustomFunctions.Error(CustomFunctions.ErrorCode.nullReference)],
  ];
}
```

Note: Please make sure you're testing with a shared runtime addin and for please create a minimal shared runtime addin for testing.
