### ISSUE TITLE
Firefox 95 failing to fetch Office.js due to HTTPS OCSP error

### ISSUE THREAD

**Issue by neville-jones** [OfficeDev/office-js#2305]
This issue is related to how Office.js is being served up in the CDN that is causing an error in Firefox's handling of the OCSP response. This is resulting in Firefox not loading Office.js and hence Office web add-ins being inoperable in that browser.

## Your Environment

* Platform: Office on the web
* Host: Outlook, but would affect all when used in Firefox browser
* Operating System: Windows 11
* Browser (if using Office on the web): Firefox version 95.0
 
## Expected behavior

 * Office add-in loads in side pane and is operational
 * when accessing the URL https://appsforoffice.microsoft.com/lib/1/hosted/office.js expect to get the Office javascript file

## Current behavior

 * Office add-in when loading in side pane reports error with yellow background: Something went wrong and we couldn't start this add-in. Please try again later or contact your system administrator.
 * Firefox 95 reports: Secure Connection Failed - An error occurred during a connection to appsforoffice.microsoft.com. The OCSP response does not include a status for the certificate being verified. Error code: MOZILLA_PKIX_ERROR_OCSP_RESPONSE_FOR_CERT_MISSING

## Steps to reproduce

1. Use Firefox 95
2. Click link [https://appsforoffice.microsoft.com/lib/1/hosted/office.js](https://appsforoffice.microsoft.com/lib/1/hosted/office.js)

## Context

Office web add-in fails to start

## Useful logs

* from Javascript console, see warning  Loading failed for the <script> with source “https://appsforoffice.microsoft.com/lib/1/hosted/office.js”.
* Uncaught ReferenceError: Office is not defined

**Comment by jennacui** [comment]
@madhavagrawal17 I'm not sure who is responsible for the add-in lifecycle. Could you please take a look and if you have the contact this issue should be assigned to? Thanks!

**Comment by jimmy-1990** [comment]
I can confirm that I am having the same problem trying to access portal.office.com this morning in Firefox.

**Comment by aranapatona** [comment]
trying to download visual studio community edition, just couldn' t connect,:
_**Error code: MOZILLA_PKIX_ERROR_OCSP_RESPONSE_FOR_CERT_MISSING**_

was surprised that finally a bug hits me and not someone else.
 https://visualstudio.microsoft.com/vs/community/

**Comment by neville-jones** [comment]
Problem not replicated today so something seems to have been fixed - can access https://appsforoffice.microsoft.com/lib/1/hosted/office.js and https://portal.office.com and Office web add-ins are operational.

**Comment by voltagex** [comment]
Getting this issue with https://www.microsoft.com/en-us/videoplayer/embed/RWNYGZ

**Comment by teamits** [comment]
Still a problem for me today on https://docs.microsoft.com/exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-1-0-in-exchange-online but strangely not https://docs.microsoft.com/.  https://partner.microsoft.com/en-us/dashboard/home wasn't working this morning, but is working now.

Edit: the Partner site stopped working at some point after letting me log in.  Perhaps MS is rolling out fixes across their servers.

**Comment by jlaundry** [comment]
Firefox bug, currently rated P1 S2: https://bugzilla.mozilla.org/show_bug.cgi?id=966856

**Comment by madhavagrawal17** [comment]
@jennacui, Thank you for reaching out to me. I have contacted the owner team to take a look at this issue.

**Comment by wandyezj** [comment]
@neville-jones I tested using Firefox 95 on 2021-12-16

The [Word Rhyme for outlook Add-In](https://appsource.microsoft.com/en-us/product/office/WA200001477) is able to load.

I am also able to access: https://appsforoffice.microsoft.com/lib/1/hosted/office.js

Are there additional steps I should take to test?

**Comment by neville-jones** [comment]
@wandyezj - from my reading of https://bugzilla.mozilla.org/show_bug.cgi?id=966856 it seems this was caused by use of SHA-256 digital signatures for OCSP stapling at a number of Microsoft sites but Firefox v 95.0 and below not supporting such. It looks like the Firefox issue has been fixed, but maybe Microsoft temporarily reverted its OCSP stapling method to use SHA-2 based digital signature and that is why we saw some early rectification?

I did report 3 days ago that the problem seemed fixed for me.
