### ISSUE TITLE
Office.context.mailbox.item.body.getAsync results in OSF.DDA.Error code: 9020

### ISSUE THREAD

**Issue by r0bb077** [OfficeDev/office-js#2398]
# Provide required information needed to triage your issue

Office.context.mailbox.item.body.getAsync is failing to work on the web version of the add in but works on Desktop. This seems also to fail only when I use email accounts within my work organisation. I've used a test personal outlook account and that works fine, so it seems specifically for my work account.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Operating System: Windows
* Browser (if using Office on the web): Chrome and FIrefox
 
## Expected behavior
Expecting Office.context.mailbox.item.body.getAsync to return the contents of the body

## Current behavior

Current error that is received;
```
error: OSF.DDA.Error
code: 9020
message: "An internal error has occurred."
name: "GenericResponseError"
status: "failed"
value: undefined
```

## Steps to reproduce

1. https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator - Use the article to create a new Office Add-in Task Pane project, using Javascript as the script type
2. Then in taskpane.js, changing the `run` function to this;
```
export async function run() {
  const mailItem = Office.context.mailbox.item;
  console.log('mailItem', mailItem);
  console.log('mailitem.body', mailItem.body);
  // grab the body content first.
  mailItem.body.getAsync(Office.CoercionType.Text, (getBodyResult) => {
    console.log(getBodyResult);
  });
}
```

## Context
We have customers affected by this so it's not just an internal issue currently it seems

**Comment by exextoc** [comment]
Thanks @r0bb077 for reporting this issue. Can you please tell us if you are trying this API in Read-Mode (reading email) or Compose-Mode (writing new email)?

**Comment by r0bb077** [comment]
> Thanks @r0bb077 for reporting this issue. Can you please tell us if you are trying this API in Read-Mode (reading email) or Compose-Mode (writing new email)?

Sorry, forgot to add that in my original issue, this happens in Read Mode only. Compose looks good.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding body.getAsync. We are able to reproduce this issue internally. It has been put on our backlog. We unfortunately have no timelines to share at this point

Internal tracking id: Office: 142470

**Comment by courington** [comment]
Following this issue as I have an Outlook add-in with customers effected by this bug. Web (Chrome and Edge) affected, desktop app working as expected.

**Comment by cbishop-fv** [comment]
Our app is seeing the same.

**Comment by exextoc** [comment]
We have fixed the bug, will update you once it reaches 100% of the users.

**Comment by ch-alex72** [comment]
> We have fixed the bug, will update you once it reaches 100% of the users.

Dear exextoc!

Can you estimate how much time this could take? We are experiencing this issue in combination with the Salesforce Outlook Addin...

Thanks a lot in advance!

Br, Alex

**Comment by geniuslionel** [comment]
Last week, I noticed this issue and thought it was our module. Our module was written and tested five years ago. We have a ton of users affected by this issue. Patiently waiting :)

**Comment by exextoc** [comment]
We have fixed the issue, please confirm.

**Comment by alexisweeren** [comment]
Running into the same problem as discussed above. Still not working for me :/

**Comment by geniuslionel** [comment]
@exextoc Looks like the fix didn't propagate immediately. My timezone is PST. Until early afternoon, had intermittent successful API calls. Late afternoon, had all successes. I'll check again Monday. Thank you and have an excellent weekend!

**Comment by r0bb077** [comment]
Still running into the issue here also.

**Comment by alexisweeren** [comment]
> Running into the same problem as discussed above. Still not working for me :/

It is working for me now!

**Comment by robebsta** [comment]
> Still running into the issue here also.

I take that back, it seems to be working for me now also.

**Comment by exextoc** [comment]
@geniuslionel Can you please confirm if the issue is fixed for you?

**Comment by alexisweeren** [comment]
> > Running into the same problem as discussed above. Still not working for me :/
> 
> It is working for me now!

Hi, this was working for me yesterday and now I am getting the same error as before.

**Comment by alexisweeren** [comment]
> > > Running into the same problem as discussed above. Still not working for me :/
> > 
> > 
> > It is working for me now!
> 
> Hi, this was working for me yesterday and now I am getting the same error as before.

@exextoc

**Comment by geniuslionel** [comment]
@exextoc It's fixed. Yesterday, our support also confirmed this. If possible, please add a unit test. I already added a watch dog in our code just in case this happens again. Thank you!

**Comment by exextoc** [comment]
> > > Running into the same problem as discussed above. Still not working for me :/
> > 
> > 
> > It is working for me now!
> 
> Hi, this was working for me yesterday and now I am getting the same error as before.

Is it still broken for you @alexisweeren ?

**Comment by alexisweeren** [comment]
> > > > Running into the same problem as discussed above. Still not working for me :/
> > > 
> > > 
> > > It is working for me now!
> > 
> > 
> > Hi, this was working for me yesterday and now I am getting the same error as before.
> 
> Is it still broken for you @alexisweeren ?

It is working now! Thanks for checking back in.

**Comment by bendblasko** [comment]
I am still receiving this error when using older version of Outlook that use IE 11.

**Comment by JuaneloJuanelo** [comment]
@bendblasko  this issue is focusing on Outlook on the Web. If you are  getting this issue please open a separate issue. We will close this one as this has been fixed as reported by many folks including the opening party.
