### ISSUE TITLE
Document properties not syncing after creating word document

### ISSUE THREAD

**Issue by Jarum77** [OfficeDev/office-js#2465]
I have created an software in Word that stores .docx files onto a MongoDB database and then opens them using the function below. On opening the file, the 'Document Info' or 'Document Properties' such as Author, Category, and Title no longer sync through the document when there are multiple of the same properties field. 

The rest of the document is the same: All fonts and styles are correct, the text is in the right place, and all images are still present. 

Here is the code used to load in a .docx file as a base64 string (variable 'text'):
`           context.application.createDocument(text).open();            
            return context.sync();
`
I have seen that only rich text content controls work currently, and so this may be the cause of the problem.

If anyone has any feedback, that would be greatly appreciated.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Office 365
* Operating System: Windows 10
* Browser (if using Office on the web): N/A
 
## Expected behavior
For the document to load as it was uploaded.

## Context
I aim to allow for the storing and recalling of word documents inside a Word software so useful files are available when needed.

**Comment by RuizhiSunMS** [comment]
@yihuax , :)

**Comment by yihuax-msft** [comment]
Yes, the add-in APIs only support rich text content controls, although you may get or set the other types of content controls through OOXML.

Could you provide us a simple sample Word document with multiple properties, as you said, so we can try it and see? Thanks!

**Comment by StevenBendell** [comment]
[Document info test document.docx](https://github.com/OfficeDev/office-js/files/8309393/Document.info.test.document.docx)
Hi @yihuax-msft ,

Please find a test document attached.

Thanks

**Comment by yihuax-msft** [comment]
Thank you @StevenBendell. After my investigation, yes, it is a bug in our API. I have just fixed it. I will put my fix into production in a few days.

**Comment by StevenBendell** [comment]
@yihuax-msft much appreciated. Thanks a lot

**Comment by StevenBendell** [comment]
@yihuax-msft 

What's the status of this? Has this been pushed into production? It still appears to be broken in our add-in (do we need to publish a new version?)

**Comment by yihuax-msft** [comment]
@StevenBendell I checked the history and the fix should be in the version of 16.0.12506.10000 or later. Have you got this version? Thanks.

**Comment by StevenBendell** [comment]
@yihuax-msft 
I have the following version of word: Microsoft® Word for Microsoft 365 MSO (Version 2204 Build 16.0.15128.20158) 64-bit 
Is this what you are referring to?

**Comment by yihuax-msft** [comment]
@StevenBendell Sorry my typo. The fix is in version 16.0.15206.10000 or later. Your version is only a few days older than the one that has the fix! :-)
