### ISSUE TITLE
makeEwsRequestAsync not returning any response when size limit exceeded (Outlook for Mac 2016)

### ISSUE THREAD

**Issue by kbl212** [OfficeDev/office-js#289]
When trying to get the MimeContent of a large (>1MB) email through EWS on Mac, there is no response from EWS, neither a success nor failure (expected) response. See stackoverflow issue here: https://stackoverflow.com/questions/53073456/ews-request-not-responding-with-error-on-mac

## Expected Behavior

I expect to get a response similar/equal to the one I see on Windows in the same situation - an error message saying: "Response exceeds 1 MB size limit. Please modify your EWS request".

## Current Behavior
I send the makeEwsRequestAsync on Outlook for Mac 2016 to get the MimeContent for an item, but get no response whatsoever from EWS. The add-in just seems to hang, saying "[Add-in Name] is working on your [Add-in Name] request." I am able to receive a response for other errors, such as when a field isn't valid in the SOAP envelope, but not for this specific error. When I make this same MimeContent request on Windows (Outlook 2016), I see the above-mentioned error message, as expected.

## Steps to Reproduce, or Live Example
1) Open Outlook for Mac 2016
2) Find a large email (>1MB including attachments)
3) Click add-in button on Home ribbon to call function.
4) Function makes "makeEwsRequestAsync" to get the MimeContent for the current email
5) Check to see if there is a response from EWS (success or failure).

Sample SOAP request used for getting the MimeContent:

```
<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <soap:Header>
      <RequestServerVersion xmlns="http://schemas.microsoft.com/exchange/services/2006/types" Version="Exchange2013" soap:mustUnderstand="0" />
   </soap:Header>
   <soap:Body>
      <m:GetItem>
         <m:ItemShape>
            <t:BaseShape>IdOnly</t:BaseShape>
            <t:IncludeMimeContent>true</t:IncludeMimeContent>
         </m:ItemShape>
         <m:ItemIds>
            <t:ItemId Id="abc123" />
         </m:ItemIds>
      </m:GetItem>
   </soap:Body>
</soap:Envelope>
```

## Your Environment
* Platform: MacOS Sierra Version 10.12.6
* Host: Outlook
* Office version number: Outlook for Mac Version 16.18 (181014)

**Comment by macOutlookExtensibility** [comment]
Thanks for raising it. Will check and work towards fixing it.

**Comment by kbrandl** [comment]
@macOutlookExtensibility any update on this issue?

**Comment by lindalu-MSFT** [comment]
@macOutlookExtensibility @exextoc Is there any resolution to this matter? Otherwise I'll close since there's no recent activity or follow-up.

**Comment by koonal19** [comment]
Hi @macOutlookExtensibility @exextoc @lindalu-MSFT getting same issue with Outlook 2019 mac client 16.42 version for large large email (>1MB including attachments) . it doesn't show any error while executing Office.context.mailbox.makeEwsRequestAsync function to read the mime content of the mail. 



@kbl212 please let me know if you get any work around for the same issue.

**Comment by exextoc** [comment]
@koonal19  This original bug was fixed in 16.24 and later builds.  Are you facing this issue in Classic Mac Outlook or New Mac Outlook? Also, Can you share the repro steps? Is it same as the original issue reported?

**Comment by koonal19** [comment]
@macOutlookExtensibility @exextoc @lindalu-MSFT
I am using MacOs Mojave 10.14.6 with Mac Outlook version 16.44 (20121301).
Here repro steps are the exactly same via EWS makeEwsRequestAsync Request. 

Here i am able to get the error in windows outlook client and OWA in all the browsers.

**Comment by exextoc** [comment]
Hey @koonal19 ,

We are investigating this issue and we will keep you updated.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding makeEwsRequestAsync .It has been put on our backlog. We unfortunately have no timelines to share at this point.
Internal tracking id: Office: 1759533

**Comment by liamtim** [comment]
@exextoc Are there any plans to increase the 1mb response limit? It would drastically increase capabilities if the limit was increased to 10mb for example.

**Comment by exextoc** [comment]
@koonal19 @liamtim We have fixed the bug. 1mb response limit has also been increased to 5mb. Both should be available from build 16.73.23042601 onwards. When an updated build is available depends on the release channel a customer is on.
Thanks!

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.

**Comment by ashaychallawar1** [comment]
I am still getting - an error message saying: "Response exceeds 1 MB size limit. Please modify your EWS request".
