### ISSUE TITLE
🔥😨 Excel: using Office.context.ui.displayDialogAsync wipes out contents of all iframes in the task pane

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js#3006]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: evergreen
* Operating System: Windows 11 Pro
* Browser (if using Office on the web): Edge / Chrome evergreen
 
## Problem description

Using `Office.context.ui.displayDialogAsync()` wipes out all `iframe` contents in the task pane DOM.

## Steps to reproduce

Use sample add-in in minimal repro: https://github.com/VelixoSolutions/office-js-reproduce-iframe-wipeout

1. Click the "Run" button
2. Observe `iframe` element added to the document

![image](https://user-images.githubusercontent.com/5159662/204649827-92ef26a3-f718-4e5e-9b66-4eeb45f08d19.png)

3. After 3 seconds, observe "add-in wants to display a new window and click "Ignore":

![image](https://user-images.githubusercontent.com/5159662/204649892-91a4a3a5-2da7-4430-adc8-db55097c5601.png)

## Actual result:

Observe `iframe` body is gone:

![image](https://user-images.githubusercontent.com/5159662/204649931-7cfba313-3384-45e1-a4a5-912c2df5107e.png)

## Expected result:

No such thing happens. `iframe` contents should be preserved.

# Provide additional details

This issue wipes out all real-time support opportunity we have with [Intercom](https://intercom.com/) inside our add-in - its messenger uses an `iframe` to display the support chats.

Due to this issue, the support widget disappears from the app completely as soon as we display a single sign-on window. 

There is no reasonable workaround - we have to use an external dialogue for single sign on, and it seems that the overlay logic for "add-in wants to display a new window" does crazy things.

DOM excerpt from the real world:

Before:

![image](https://user-images.githubusercontent.com/5159662/204650677-554ac333-c275-42b3-acc4-cc104761747b.png)

After:

![image](https://user-images.githubusercontent.com/5159662/204650636-3f29bb81-af9e-4e58-97a6-d1753c16d051.png)

**Comment by RuizhiSunMS** [comment]
Have forward this issue to heidi.

**Comment by iotataru** [comment]
@wh1t3cAt1k can you please make https://github.com/VelixoSolutions/office-js-reproduce-iframe-wipeout public or share it with me (email: iotataru@microsoft.com)

**Comment by wh1t3cAt1k** [comment]
@iotataru apologies, it was unintentionally private - this is public now :)

**Comment by wh1t3cAt1k** [comment]
Any update on this issue @iotataru @RuizhiSunMS ?

**Comment by iotataru** [comment]
The issue should be resolved. Let me know if it still reproduces on your end @wh1t3cAt1k

**Comment by wh1t3cAt1k** [comment]
@iotataru What is the fix version in the host / Office.js? 

![image](https://user-images.githubusercontent.com/5159662/228394007-05c20408-f249-4c08-97d0-5587dc4c00e8.png)

I cannot confirm that the issue is gone, it is still replicable on my side on the latest Chrome + Excel Online.

See the above screenshot, the iframe contents are replaced with empty head/body elements.

**Comment by iotataru** [comment]
It looks like the fix should be in Excel Online starting with version [16.0.16102.42304]
Which version are you on?

**Comment by wh1t3cAt1k** [comment]
@iotataru my version 16.0.16330.42300.

The issue still replicates.

**Comment by wh1t3cAt1k** [comment]
@iotataru @RuizhiSunMS @Wenjun-Gong I have just verified that the issue replicates using the same exact reproduction step on the minimal repro repository, using Excel Online on Chrome. Therefore, it definitely has not been fixed.

<img width="391" alt="image" src="https://user-images.githubusercontent.com/5159662/229780650-4ae1d586-ed9d-4656-b98f-e2c79472ebe9.png">

(The IFrame initially contains "Foo" as text inside, after Office displays the dialogue prompt only empty head/body tags remain in the HTML, the contents are removed)

**Comment by wh1t3cAt1k** [comment]
Can we hope for any kind of feedback for this?..

**Comment by iotataru** [comment]
@wh1t3cAt1k yes the issue should be resolved. Can you confirm?

**Comment by wh1t3cAt1k** [comment]
@iotataru @RuizhiSunMS @Wenjun-Gong

I feel really silly - the issue still replicates and the steps did not change. (This is the second time the situation repeats 🙈) 

Can we hope for some serious attention to this problem? 

Once again, the problem is **not** solved.

**Comment by wh1t3cAt1k** [comment]
@iotataru @RuizhiSunMS @Wenjun-Gong calling for your attention to this problem one more time...

**Comment by RuizhiSunMS** [comment]
@wh1t3cAt1k  loatatru should be the owner actually.

**Comment by iotataru** [comment]
Deployment issue has been resolved a while ago, we should close this issue.

**Comment by jaiswalshubh1** [comment]
Hi @wh1t3cAt1k ,

Issue has been fixed, Can you please verify from your side? 

cc: @kustonaut 

Thanks!
Shubham Jaiswal

**Comment by jaiswalshubh1** [comment]
Hi @wh1t3cAt1k ,

We are waiting for your response as issue has already fixed, I am closing this issue, please feel free to open fresh bug if you get same issue.

cc: @kustonaut 

Thanks!
Shubham Jaiswal
