### ISSUE TITLE
The keyboard shortcut `Ctrl+Enter` triggers the `ItemSend` event anew in OWA

### ISSUE THREAD

**Issue by eugene-plutoflume** [OfficeDev/office-js#3082]
# Provide required information needed to triage your issue
We have found that in Outlook when you send an email and click the `Send` button the `ItemSend` callback may be triggered multiple times, such actions are caused by pressing `Ctrl+Enter` on the keyboard while the email is being processed. Normally `Ctrl+Enter` just sends the email. But if you handle the `ItemSend` in the add-in, that keyboard shortcut triggers the event anew in OWA (Chrome). So, you may end up with an email being sent out without any evidence in the UI.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: -
* Operating System: any
* Browser (if using Office on the web): Chrome
 
## Expected behavior

The send operation can't be triggered while the item is being processed, i.e. the `ItemSend` callback is invoked, so can't re-enter the same function multiple times. But the practice shows that the callback can be triggered anew by using a keyboard shortcut.

## Current behavior

The email can be sent out silently independently of the results of running the `ItemSend` callback.

## Steps to reproduce

1. Compose a new email in Outlook (OWA running in Chrome). The desktop applications work correctly.
2. Click the Send button. The `ItemSend` callback should be triggered. 
3. While the `ItemSend` callback is working use the keyboard shortcut  `Ctrl+Enter` to submit/send the email anew.

**Comment by AlexJerabek** [comment]
Thanks for reporting this issue @eugene-plutoflume.

@exextoc, could you please investigate?

**Comment by exextoc** [comment]
Hey @eugene-plutoflume 

We are not able to reproduce the issue at our end 
- Can you help us with a repro video, if possible?
- Did you discover this recently (or do you know this was working fine previously) ?

**Comment by eugene-plutoflume** [comment]
Hi @exextoc! Here is how it looks now in OWA:

![outlook-dialog](https://user-images.githubusercontent.com/32734640/213216209-82470d0c-fa67-4491-ad7d-a31f0dec3794.gif)

The issue was discovered a month ago.

As you can see on the video, the item can be sent silently while the dialog is initialized or any other code in the `ItemSend` event handler is working. Just press `Ctrl + Enter` to submit an email and keep pressing it again and again. Your item will be sent out independently of the `ItemSend` callback results :)

**Comment by eugene-plutoflume** [comment]
Hi @exextoc! Were you able to reproduce the issue? Let me know if you need any other information.

**Comment by exextoc** [comment]
Thank you for reporting this issue. We are able to repro and have added this to our backlog and will have a look at it. However, we have no timelines to share at this point. 
Internal tracking id: 188273

**Comment by exextoc** [comment]
This issue has been fixed and fix should be available now.

**Comment by eugene-plutoflume** [comment]
@exextoc unfortunately I still see the problem in web browsers - Chrome Version 111.0.5563.65 (64-bit) and MS Edge Version 111.0.1661.41 (64-bit).

**Comment by exextoc** [comment]
Thanks for information. We will investigate further

**Comment by eugene-plutoflume** [comment]
@exextoc the issue has not been fixed. Please keep it open.

**Comment by exextoc** [comment]
@eugene-plutoflume Is this issue still reproducible ??

**Comment by eugene-plutoflume** [comment]
@exextoc fixed, I couldn't reproduce this issue any longer. Thank you.
