### ISSUE TITLE
Outlook Add-in not showing in shared mailbox

### ISSUE THREAD

**Issue by cody-lettau** [OfficeDev/office-js#3227]
We have an add-in that has previously worked in shared mailboxes, but no longer is showing up in the shared mailbox.

We are deploying the add-in via a managed deployment from the O365 Admin Portal to the main user account and the shared mailbox. Our manifest has the flag ```<SupportsSharedFolders>true</SupportsSharedFolders>```. This has worked previously, but now does not appear to be working at all.

Our customers are reporting this same issue.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): Chrome
 
## Expected behavior
The add-in is visible and usable in the Shared Mailbox

## Current behavior

The add-in is not available in the shared mailbox.

## Steps to reproduce

Create an add-in that supports shared mailboxes (defined in the manifest). Deploy this add-in via a managed deployment to the main user account and the shared mailbox that that user has access to.

Open the shared mailbox in OWA using the "Open another mailbox" feature.

## Link to live example(s)

You can view our manifest here: https://cdn.virtru.com/outlookjs/manifest/VirtruForOutlook.xml

## Context

We have large customers with thousands of users who are attempting to use this functionality and are finding the add-in is not available in their shared mailboxes.

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)
![image](https://user-images.githubusercontent.com/7740624/225910614-e6a3f199-9f1e-4bbf-b1af-0a5e17476513.png)
![image](https://user-images.githubusercontent.com/7740624/225910712-dfccb85a-ae30-4852-86d7-14d5a8f1ec41.png)
Note: We login to the main user account (support@virtrutest.biz) and then we open another mailbox (support-shared@virtrutest.biz -- which was created as a Shared Mailbox and the original user has permissions granted to it). The add-in DOES display in the mailbox of the original user.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by cody-lettau** [comment]
@exextoc this seems like a pretty major bug. We have thousands of users who are expecting this functionality to work. It worked for some time about a month or two ago after we implemented it and now the add-in no longer shows up in the shared mailbox.

Can we please look into this with urgency? We need to understand if something has changed in terms of requirements for add-ins to be usable in a shared mailbox or if something has been broken in the Add-in framework.

**Comment by cody-lettau** [comment]
It appears that over the weekend, the add-in started showing up in our shared mailboxes for our test accounts. We deployed it on 3/15/2023 in the afternoon and it definitely was not available 48 hours later on Friday afternoon. Sometime over the weekend it must have become available in the shared mailbox (even though we saw it in a user's inbox that was part of the managed deployment on Friday).

That said, I'm curious what type of deployment times we should expect when using a managed deployment of an add-in to shared mailboxes? I see the following note in the documentation, which is what we've communicated to our customers:
![image](https://user-images.githubusercontent.com/7740624/226345826-4c13b5a5-fa61-4e58-b06f-a0e158367624.png)

But it doesn't seem that is accurate, as this deployment took over 48 hours.

**Comment by cody-lettau** [comment]
And now this morning, after NO changes at all to the deployment, the add-in is no longer available in the shared mailbox.

This is a major issue with how inconsistent the add-in framework is in shared mailboxes. We cannot have our add-in deployed for customers in shared mailboxes and have it be available some days and not the others (with no changes at all to the deployment or the add-in).

**Comment by exextoc** [comment]
@cody-lettau, is this issue happening on the Outlook Desktop application for Windows, or the Mac Outlook client or the web client?

Looking through your manifest XML, everything seems to be in place, so I don't think there any issues with your manifest.

For add-ins that are deployed via Centralized Deployment, it can take up to 72 hours for the changes to show up for users. This is documented online here: https://learn.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-faq?view=o365-worldwide#how-long-does-it-take-for-add-ins-to-show-up-for-all-users-

We may need to clarify our documentation here.

**Comment by cody-lettau** [comment]
@exextoc we are definitely seeing it in OWA. I believe we also see it on desktop clients as well, but I'd need to confirm with my Support team.

I will take note of the up to 72 hours part and relay that to our Support team. That seems like quite a poor UX though, so I'd really like to push for that rollout to be shorter if at all possible :)

**Comment by exextoc** [comment]
@cody-lettau, we will wait to hear from you regarding which client you are observing this issue in. Thanks.

**Comment by cody-lettau** [comment]
@exextoc I tested on Mac Desktop (new UI) and in OWA:

- Mac Desktop: The add-in shows as expected for both the main user account and the shared mailbox.
- Windows Desktop: The add-in shows as expected for both the main user account and the shared mailbox.
- OWA: The add-in shows as expected for the main user. It is NOT available within the Shared Mailbox (opened using "Open another mailbox" option).

So the issue seems to be currently only occurring in OWA.

**Comment by exextoc** [comment]
Thanks for reporting this issue. We are not able to repro this. To investigate this further, we need some more info.

1. Addin not showing up in Shared Mailbox when opened using "Open Another mailbox" is a consistent behavior or does it happens sometimes?
2. Is it not showing up for all the users or only some of them?

As workaround, you can try adding shared mailbox in same window- [https://support.microsoft.com/en-us/office/open-and-use-a-shared-mailbox-in-outlook-on-the-web-98b5a90d-4e38-415d-a030-f09a4cd28207](https://support.microsoft.com/en-us/office/open-and-use-a-shared-mailbox-in-outlook-on-the-web-98b5a90d-4e38-415d-a030-f09a4cd28207)

**Comment by cody-lettau** [comment]
> Thanks for reporting this issue. We are not able to repro this. To investigate this further, we need some more info.
> 
> 1. Addin not showing up in Shared Mailbox when opened using "Open Another mailbox" is a consistent behavior or does it happens sometimes?

It appears to be only happening at times. During my testing and reported from users, it was there one day and then gone the next day (with no changes made to the manifest or the deployment via the admin console).

> 2. Is it not showing up for all the users or only some of them?
> 
> As workaround, you can try adding shared mailbox in same window- https://support.microsoft.com/en-us/office/open-and-use-a-shared-mailbox-in-outlook-on-the-web-98b5a90d-4e38-415d-a030-f09a4cd28207

It appears that it does not show up in the shared mailbox for any users when this occurs. That said, it shows fine in the main user's account (not the shared mailbox).

The workaround you mention does not provide the same functionality as "Open another mailbox" in OWA. There are differences in how the user must use the add-in and it causes friction with our use cases unfortunately.

**Comment by exextoc** [comment]
@cody-lettau Thank you for reporting the issue. We are unable to repro this at the moment but would like to connect with you to learn more on this. Please reach out to us at nikitamittal@microsoft.com

**Comment by exextoc** [comment]
The issue is being looked at internally, closing this ticket.

**Comment by cody-lettau** [comment]
Can we keep this open until it is resolved? There definitely is a bug here and relevant logs and details have been provided by email.

**Comment by exextoc** [comment]
@cody-lettau The fix is scheduled to be available by mid-September. please feel free to reopen this if issue persists after that.

**Comment by cody-lettau** [comment]
@exextoc is there any reason we are closing bugs before they are actually fixed in production? Unless the fix is released and available to be confirmed, I think the bug should remain open.

**Comment by Codapr-01** [comment]
We also have the issue on our shared mailbox, the fix has been deployed ?

**Comment by chriseiken** [comment]
Can we get confirmation on if the fix has been deployed or if not, when it's expected to be deployed.

**Comment by ovdixon** [comment]
Would be great to have an update on this!

**Comment by infog2i** [comment]
The issue is still occuring, could we have an update about it ? We can't fully use add-in that we paid for. 

It's still the same issue : 

1. Windows Desktop: The add-in shows as expected for both the main user account and the shared mailbox.

2. OWA: The add-in shows as expected for the main user. 
- It is NOT available within the Shared Mailbox opened using "Open another mailbox" option.
- It is available within the Shared Mailbox opened threw the main mailbox using "Add shared mailbox" option.

**Comment by ajays-msft** [comment]
2.1 above is by design. 

To clarify:
1) OWA "Open another mailbox" flow will show addins deployed in "shared mailbox account". Only admin deployed addins are shown in shared mailbox. In order for the addin to show up in shared mailbox, please have the addin be deployed to the sharedmailbox account via admin center. 

2) OWA "Add shared mailbox" or Windows Desktop shared mailbox will show addins for the user account and not "shared mailbox account". Here user can launch store and install the addin directly if they want.

**Comment by akshayta23** [comment]
Sharing the public documentation link for accessing add-ins via Shared Mailbox https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/delegate-access?tabs=modern%2Cjsonmanifest Please follow the steps outlined and let us know if there are any issues you are facing.
