### ISSUE TITLE
Excel.WorksheetCollection onNameChanged Event no longer exists

### ISSUE THREAD

**Issue by zpfaltersack** [OfficeDev/office-js#3253]
# Provide required information needed to triage your issue

We use the worksheet collection's onNameChanged event and sometime in the last 24 hours or so that event no longer seems to exist on the collection. It still exists in our typescript type definitions we've pulled in and it still exists in the docs, but trying to add a handler to the event fails with 'Cannot read properties of undefined (reading 'add')' in every environment we have.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web and Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: all
* Operating System: Windows
* Browser (if using Office on the web): Chrome and Edge
 
## Expected behavior

You can still add handlers to the onNameChanged event in Excel.WorksheetCollection

## Current behavior

context.workbook.worksheets.onNameChanged is undefined

## Steps to reproduce

1. Create a small app and try to add a handler for that event on the WorksheetCollection.

## Context

This is causing errors in every dev and test environment as well our production environment. It's impacting every session a user has with our addin.

## Useful logs

![image](https://user-images.githubusercontent.com/6788086/227751273-2bc4dc84-1fc1-4b2f-8273-a9d49f9f5966.png)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by pvsleeper** [comment]
WTH!? This stopped working for us too! Please - our app relies on the events - how can they just get deleted!?!?! onVisibilityChanged even is also gone!?

**Comment by XiLiuRoy** [comment]
Hi Guys, we are also experiencing this problem and unable to listen to events, development has been paused and can we please give this issue a higher priority and any hints that cause this incident?

**Comment by jipinshi** [comment]
HI All, thanks for the reporting the issue, we have found the root cause and is doing the mitigation. At the same time, the possible thing you may can do to mitigate the issue is to use https://appsforoffice.edog.officeapps.live.com/lib/beta/hosted/office.debug.js library first to unblock your customers. Will report back once the issue is mitigated.

**Comment by pvsleeper** [comment]
Hi @jipinshi - is there a more stable version of the API that we can reference? This is now the 2nd time in the past 6 months that some change to the API have caused our Add-in to fail to load (around Halloween there was some update that deleted all the bindings in a sheet - at the time we were making use of bindings and that change also brought our add-in to its knees).

Our deployment process does not allow for us to quickly change something and push it out at the drop of a hat. Before any change can go out to our production environment we have to have a full QA sign-off and the deployment process involves multiple parties across multiple time-zones. 

Any advice on how we can lessen the impact these changes? From what I am now starting to see, this might be a semi regular occurrence and we need to have some control put in place to address it when some random change to the API breaks our add-in. 

From what I can tell, I can import it via NPM, but not allowed to use the NPM version when going out to the app store. Do you know how other people work around these kind of issues? Clients do not really care whose fault it is when something isn't working, they just care about the fact that it's not working and it's not great not being able to provide them with a timely solution.

Thank you

**Comment by zpfaltersack** [comment]
Hi @jipinshi, I appreciate a proposed workaround but in this particular case pushing a beta build into production doesn't seem reasonable. We have no way of knowing what unvetted changes or bugs may exist that are even worse than what we're currently experiencing.
We're all software engineers here and we know bugs happen; it's the nature of the game. That said, this particular category of error doesn't seem like it should really escape a dev/test environment. It's one thing if an API begins misbehaving, but having swaths of the public API just disappear seems hard to justify. 
I have to agree with @pvsleeper. We have many customers that are paying for a product and they do not care why it's unavailable, all they know is they aren't getting what they've paid for. It's frustrating to feel as though we must be vigilant to changes beyond our control, especially because the recommended way to consume the OfficeJS APIs are through the CDN as opposed to NPM or similar where we can control the revisions that get deployed with our applications.

**Comment by pvsleeper** [comment]
@jipinshi - any status updates on this issue yet?

**Comment by penglongzhaochina** [comment]
Hi all,Our roll-back deployment is done. But Still have some cache need to purge. So it should be resolved by Wednesday. Sorry for any inconvenience.

**Comment by pvsleeper** [comment]
@penglongzhaochina @jipinshi - do you have any advice on how to avoid these kind of issues in the future. Our add-in has effectively been out of action for the good part of 2 days... :(

Also, is there a way that we can see release notes or anything when an update gets pushed? 

Thank you

**Comment by jipinshi** [comment]
HI All, the fix has been done. If you clear cache and respect the latest js, it should work now. Let me know whether it is same in your side.

**Comment by zpfaltersack** [comment]
@jipinshi The issue is still occurring for me across the board. I've purged caches, used incognito mode, etc, and nothing is getting it to work. May still be propagating out on your side though.

**Comment by pvsleeper** [comment]
@jipinshi - using the web version, it looks good for me, but using Desktop, its still busted. 

When you say clear the cache, I tried the following on desktop:
- In DevTools disable the caching for network requests
- Deleted  contents of %LOCALAPPDATA%\Microsoft\Office\16.0\Wef\

Is there anything else I should do to try and clear the cache? Thanks!

**Comment by jipinshi** [comment]
@zpfaltersack @pvsleeper , how about now? My side can work with win32.

**Comment by zpfaltersack** [comment]
@jipinshi late last night Excel Online started working for us. Excel Desktop wasn't working then, but it is now this morning. So I think we're back in business. Thanks!
