### ISSUE TITLE
When I open Document Using insertFileFromBase64() then alignment getting  disturb and Header & Footer is missing

### ISSUE THREAD

**Issue by Jayshiv-IRIS** [OfficeDev/office-js#3357]
Hello Team,
I am using Word API for developing word add-in. I have used insertFileFromBase64 method for opening existing  document .
When I open existing document on same word instance that time header footer getting missing and data alignment getting disturb but when I open that in new WORD instance that time its comming perfect.

My Environment
Platform : PC desktop
Host: Word
Office version number: Microsoft® Word for Microsoft 365 MSO (Version 2304 Build 16.0.16327.20200) 64-bit
Operating System: Windows 10 pro

When I use this snippet 
```
Word.run(async function (context) {
    var body = context.document.body;
    var sections = context.document.sections;
    sections.load();
    await context.sync();
    sections.items.forEach(function (section) {
    
        section.body.clear();
        section.getHeader('primary').clear();
        section.getHeader('firstPage').clear();
        section.getHeader('evenPages').clear();
        section.getFooter('primary').clear();
        section.getFooter('firstPage').clear();
        section.getFooter('evenPages').clear();
      
    });
    body.clear();
    await context.sync();
    body.insertFileFromBase64(mybase64, Word.InsertLocation.replace);
});
```
 output:
[Same instance OutPut.docx](https://github.com/OfficeDev/office-js/files/11474719/Same.instance.OutPut.docx)
As you can see  page content formating disturb and data is also split on 2nd page.

Now,
when I use this code snippet  to opening in new Word Instace it's getting Perfectly 

snippet
```
 var newdoc = context.application.createDocument(mybase64);
 newdoc.open();
```

OutPut : 
[Output.docx](https://github.com/OfficeDev/office-js/files/11474740/Output.docx)

Expected Output

[ExpectedOutPut.docx](https://github.com/OfficeDev/office-js/files/11474774/ExpectedOutPut.docx)

Here My expected output and 1st code snippet output is not matching but when I open word in new intstance it will give me same output i need that same output in same word instance instead of opening new word instance

**Comment by Searion** [comment]
Thank you bringing this to our attention! This issue is happening because Body.insertFileFromBase64() cannot import headers, footers, styles and other formatting. 

We recommend you to use our new API Document.insertFileFromBase64() to handle this scenario perfectly, which will be released in this month.

**Comment by Jayshiv-IRIS** [comment]
@Searion  Hi, Can you please provide release date or period of time  for Document.insertFileFromBase64() this method .

**Comment by Searion** [comment]
@Jayshiv1408Dev It is avalible now. Please refer to https://learn.microsoft.com/en-us/javascript/api/word/word.document?view=word-js-preview#word-word-document-insertfilefrombase64-member(1)

**Comment by Jayshiv-IRIS** [comment]
Hey team for same document I used this method Header and footer getting set properly but there is still formatting issue

as you can see this in attached Document data movement is there data is split in two pages instead of one page
Here is my code snippet
In myBase64 i set bytes of my original document .
Original document
[OriginalDoc.docx](https://github.com/OfficeDev/office-js/files/11598967/OriginalDoc.docx)
 
```
Word.run(async function (context) {
    var document = context.document;
    document.insertFileFromBase64(mybase64, Word.InsertLocation.replace);
    excelLinkingDiv();
});
```

[ExpectedOutPut.docx](https://github.com/OfficeDev/office-js/files/11598885/ExpectedOutPut.docx)
[errorOutput.docx](https://github.com/OfficeDev/office-js/files/11598886/errorOutput.docx)

Is there any way to set formatting to current word instance because when I open new instance of word using same byte then it come properly.

**Comment by Searion** [comment]
@Jayshiv1408Dev If you don't pass InsertOptions, paragraph spacing and styles will not be imported. For this document, styles are the determining factor. You use it like this:
context.document.insertFileFromBase64(mybase64, "Replace", {
      importTheme: false,
      importStyles: true,
      importParagraphSpacing: false,
      importPageColor: false,
      importChangeTrackingMode: false
    });

**Comment by Jayshiv-IRIS** [comment]
@Searion  Hii, Thanks for your response,

here is My original File
[Consolidated and separate statements of financial position Origanl.docx](https://github.com/OfficeDev/office-js/files/11625194/Consolidated.and.separate.statements.of.financial.position.Origanl.docx)
[Consolidated and separate statements of other comprehensive income Origanl.docx](https://github.com/OfficeDev/office-js/files/11625196/Consolidated.and.separate.statements.of.other.comprehensive.income.Origanl.docx)
[Consolidated and separate statements of profit or loss Origanl.docx](https://github.com/OfficeDev/office-js/files/11625197/Consolidated.and.separate.statements.of.profit.or.loss.Origanl.docx)

I use this code  snippest, but i getting formatting issue in header 
```
context.document.insertFileFromBase64(mybase64, "Replace", {
                                importTheme: true,
                                importStyles: true,
                                importParagraphSpacing: true,
                                importPageColor: true,
                                importChangeTrackingMode: true
                            });
```

Here is Error file
[Consolidated and separate statements of financial position Error.docx](https://github.com/OfficeDev/office-js/files/11625220/Consolidated.and.separate.statements.of.financial.position.Error.docx)
[Consolidated and separate statements of other comprehensive income Error.docx](https://github.com/OfficeDev/office-js/files/11625221/Consolidated.and.separate.statements.of.other.comprehensive.income.Error.docx)
[Consolidated and separate statements of profit or loss Error.docx](https://github.com/OfficeDev/office-js/files/11625222/Consolidated.and.separate.statements.of.profit.or.loss.Error.docx)

Here is my expected Output file(when i open new section in new window that time i get this output)

[Consolidated and separate statements of financial position Expected.docx](https://github.com/OfficeDev/office-js/files/11625236/Consolidated.and.separate.statements.of.financial.position.Expected.docx)
[Consolidated and separate statements of other comprehensive income  Expected.docx](https://github.com/OfficeDev/office-js/files/11625237/Consolidated.and.separate.statements.of.other.comprehensive.income.Expected.docx)
[Consolidated and separate statements of profit or loss  Expected.docx](https://github.com/OfficeDev/office-js/files/11625238/Consolidated.and.separate.statements.of.profit.or.loss.Expected.docx)


As you can see  Header position getting disturb.

**Comment by Searion** [comment]
@Jayshiv1408Dev Thanks for reporting this issue regarding insertfilefrombase64. I found this seems happen when the target document has a heading and there is a table in the heading of source document. It has been put on our backlog. We unfortunately have no timelines to share at this point. ​

**Comment by Jayshiv-IRIS** [comment]
Hi Team,
Thanks For your response.
When this comes to resolution , please intimate us.
we want to merge the documents and preview them on office side.

**Comment by Jayshiv-IRIS** [comment]
Hi Team, Is there any update on this?

**Comment by Searion** [comment]
Thanks @Jayshiv1408Dev. We fixed it in late July. If you are not using preview version, you may get the it in early September. If there is any other issues, please let us know.

**Comment by Jayshiv-IRIS** [comment]
Hi @Searion  Thanks for your response. Can you please tell me what is the preview version? 
How can I find that I am using preview version or not?

**Comment by Jayshiv-IRIS** [comment]
Hii Team. Can you please provide date when it gonna release? I'm still facing same issue at my end.

**Comment by jipyua** [comment]
hi @Jayshiv1408Dev this fix should have been deployed to production, please have a try of the latest M365 version. thanks.

**Comment by WenyanZhao** [comment]
> 它现在是可用的。请参考 [https://learn.microsoft.com/en-us/javascript/api/word/word.document?view=word-js-preview#word-word-document-insertfilefrombase64-member（1）](https://learn.microsoft.com/en-us/javascript/api/word/word.document?view=word-js-preview#word-word-document-insertfilefrombase64-member(1))

why can't I import template using document.insertfilefrombase64
