### ISSUE TITLE
Excel Desktop for Mac: onSingleClicked event does not work on external monitor

### ISSUE THREAD

**Issue by s-ratashnyuk** [OfficeDev/office-js#3415]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.73
* Operating System: Ventura 13.4
* Browser (if using Office on the web): N/A
 
## Expected behavior
The onSingleClicked works despite of Excel window being placed on the internal or external monitor.

## Current behavior
If the Excel window was placed on the internal monitor, the handler works. If we move the window to the external monitor, the handler will stop working. If we move the window back to the internal monitor, the handler will work again.

## Steps to reproduce

1. open Excel, and ensure that the Excel window is placed on the internal monitor
2. using the ScriptLab, load the gist: https://gist.github.com/s-ratashnyuk/4533f28e0be6ce513d6e55c14a225de4
3. run the gist, press the Run button
4. click somewhere on the sheet and observe handled events
5. move the window to an external monitor
6. click somewhere and observe the events stop handling

## Context

In our add-in (Velixo) we want to add a "button" in a cell, to simplify the UI and to give a user one step less to make their job. Without a proper event, we only can use onSingleClicked to emulate the "button" behavior.

**Comment by ghost** [comment]
Thank you for letting us know about this issue. We will take a look shortly. Thanks.

**Comment by heimen-zc** [comment]
sorry, my description is not precise，i open a new issue, pls close this one.

**Comment by wh1t3cAt1k** [comment]
@ruijiaMS @JinghuiMS this issue should not have been closed, we don't know @heimen-zc and it was probably a mis-post.

The issue is highly relevant and replicable. Please reopen it and investigate if possible 🙏.

**Comment by gmichaud** [comment]
@heimen-zc did you mean to post your comment on a different issue? I can replicate this issue, bug is very much relevant.

**Comment by wh1t3cAt1k** [comment]
@ruijiaMS please reopen the bug if you have a minute.

**Comment by ruijiaMS** [comment]
Hi @heimen-zc, @wh1t3cAt1k, @gmichaud,
Thanks for letting us know the repro status and we raise an internal bug #8006523 to investigate this issue, any update will be post here. Thanks!

**Comment by kunitak-genialai** [comment]
I reproduced it on my Windows device with a sub-monitor.
Is there a workaround for this?

Environment:
Windows 11 Pro（22H2）
Microsoft 365 (version:2305, build:16.0.16501.20074) 64 bit

**Comment by s-ratashnyuk** [comment]
> I reproduced it on my Windows device with a sub-monitor. Is there a workaround for this?
> 
> Environment: Windows 11 Pro（22H2） Microsoft 365 (version:2305, build:16.0.16501.20074) 64 bit

No, just don't use an external monitor 🤷

**Comment by SiruiSun-MSFT** [comment]
Hi @wh1t3cAt1k, @kunitak-genialai, @s-ratashnyuk. Could your please update to the latest version and try again? Since we cannot repro this issue from our side. Here is our build version: 16.74(23061100). Thanks!

**Comment by kunitak-genialai** [comment]
Hello @SiruiSun-MSFT ,
I tried the version on my Windows device, which is now 2306, and the problem was resolved! 
Thanks for the fix!

**Comment by s-ratashnyuk** [comment]
No, the bug still exists. Checked on 16.75 (23070901)

Here is a screencast with repro:
https://velixo-my.sharepoint.com/:v:/p/sratashnyuk/EW957Q7317hAo_K88P7CgIEBBHNVsNu07x7vCffZIhXRYA?e=V5StH1

**Comment by doantumai** [comment]
Hi,
I have the same problem on Excel Desktop. 
Does anyone have any news?

My enviroment: MacOS Ventura 13.4

**Comment by andreyv99** [comment]
Hi,

The bug is reproducible on my Mac with external monitor. This is very critical bug. Does anyone know how to fix it?
@ruijiaMS @SiruiSun-MSFT @JinghuiMS

**Comment by YueLi-MSFT** [comment]
Hello guys, we appreciate your patience and understanding. Our team is working hard to identify the source of this problem and resolve it. We apologize for any inconvenience this may have caused you and we assure you that we will fix this issue as soon as we can. Thank you very much for your cooperation!

**Comment by YueLi-MSFT** [comment]
Hi guys, thanks you for waiting so long. Here's good news, we have fixed this issue on Excel Desktop for Mac. You can try it on the newer version of Office now! We're closing this ticket. If you have any questions, please contact us again.

**Comment by s-ratashnyuk** [comment]
> Hi guys, thanks you for waiting so long. Here's good news, we have fixed this issue on Excel Desktop for Mac. You can try it on the newer version of Office now! We're closing this ticket. If you have any questions, please contact us again.

Awesome, thank you so much!
