### ISSUE TITLE
Unable to get content HTML in Word using JS API

### ISSUE THREAD

**Issue by ChienHo** [OfficeDev/office-js#3699]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Web on Windown and MAC
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.0.16914.41010
* Operating System: Windows 11 Pro 23H2
* Browser (if using Office on the web): Version 116.0.5845.188 (Official Build) (64-bit)
 
## Expected behavior

In word when using JS api with function getHtml() we can get HTML content of body in word file.
Link document: https://learn.microsoft.com/en-us/javascript/api/word/word.body?view=word-js-preview#word-word-body-gethtml-member(1)
## Current behavior

Funtion getHtml()  return error .

## Steps to reproduce

1. Insert content control
2. Insert table data to content control
3. Using function getHtml() to get content body of word file

## Link to live example(s)

1. https://gist.github.com/ChienHo/d91cec8e629b9b2930ee3655c2282403
2. 
[error-word-getHtml-api.webm](https://github.com/OfficeDev/office-js/assets/30323038/88e9ffe0-6f0d-4061-9420-7b615460c596)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by yilin4** [comment]
We will investigate for this, thank you

**Comment by yilin4** [comment]
@ChienHo This should be a bug. It has been put on our backlog<Bug#8433856> for internal track. We will keep track of this issue and let you know if there are any updates.

**Comment by monominia** [comment]
Any update on this issue now?

**Comment by yilin4** [comment]
@monominia We haven't arranged time to fix this bug. maybe you can tell me the influence of this bug, so we can fix it in advance. Or you can try this workaround if this can meet your needs: [https://gist.github.com/yilin4/c5d4b3eecbbd2bc22e32dd10c26ffad6](https://gist.github.com/yilin4/c5d4b3eecbbd2bc22e32dd10c26ffad6)
Defining the insertData in front of inserting a content control, and insert it with this data. Hope this can help you.

**Comment by monominia** [comment]
Hey @yilin4 , I tried the gist you shared here inside Script Lab, and the still get the error thrown after I click `Get Content` button.
![Screenshot 2023-11-16 at 2 12 22 PM](https://github.com/OfficeDev/office-js/assets/13508893/73aebe61-b49e-47ab-8891-96ac3a3f8995)

**Comment by monominia** [comment]
Hey @yilin4 , the influence of this bug is we cannot deliver the add-in we're developing as expected. Basically the use case is: the add-in created some Content Controls filled in with some HTML string (we use `insertHtml` now). After user finishing editing those content inside the Content Controls, we call `getHtml` to fetch to data and send them to the APIs we hosted with our business logics.

**Comment by monominia** [comment]
Hey @yilin4 , you can see my screen recording below:

https://github.com/OfficeDev/office-js/assets/13508893/2d2f8148-e414-4a7f-a358-43c0162b8d45

**Comment by yilin4** [comment]
@monominia I have tried it again and I found that when inserting a content control to an empty paragraph, then trying to get HTML will throw this error. After throwing the error, any changes won't help, you will always get the error. Maybe you should refresh the browser and run the gist again, and I think it will work. If you still have this error after the refresh, please let me know it. Thank you~

**Comment by monominia** [comment]
Hey there, do we have an expected date for this  bug fix? I mean it doesn't help even the gist work, because our use case is letting the user input any hyper text in the content control, and after they submit the add-in need to call get Html() to read the content. The gist you shared here obviously assumed you already know what html string is inside the content control before you call getHtml() (the insertData here)

**Comment by yilin4** [comment]
@monominia Could you estimate the MAU from your new add-in? So, we can determine the priority of this bug.

**Comment by monominia** [comment]
Hey @yilin4 , the estimated MAU from my team is 50,000 active users per month.

**Comment by yilin4** [comment]
@monominia We are actively working on it, and we will let you know once we have some progress. Thank you!

**Comment by yilin4** [comment]
@monominia The bug has been fixed now, you can have a try, and if there is any other question, please contact me. Thank you!

**Comment by monominia** [comment]
Hey @yilin4 , it still doesn't work on my side, I just tested it using the Github gist you shared with me, and it still thrown error like before.
![Screenshot 2023-11-23 at 10 00 44 PM](https://github.com/OfficeDev/office-js/assets/13508893/aff969f4-cd9e-499c-8dcf-925cfd4eb4a9)

**Comment by yilin4** [comment]
@monominia Sorry for that, I have just checked it, and found it only works in the inner ring now. It may need some time to roll out to the production, and I will reminder you at that time, or you can try it a few days later.

**Comment by monominia** [comment]
> @monominia Sorry for that, I have just checked it, and found it only works in the inner ring now. It may need some time to roll out to the production, and I will reminder you at that time, or you can try it a few days later.

hey @yilin4 , thanks for your reply, please tell me when it's out of the inner ring, have a good day!

**Comment by yilin4** [comment]
@monominia It's okay now, please have a try.

**Comment by monominia** [comment]
Hey @yilin4 , I tried the `getHtml()` on Web, and I noticed a problem.

- When I typed in a simple underlined text on Web, and call `getHtml`, it returned `'<HTML>\r\n<HEAD></HEAD>\r\n<BODY>\r\n<div class="OutlineGroup"><div class="OutlineElement Ltr"><div class="ParaWrappingDiv"><p class="Paragraph" xml:lang="EN-US" lang="EN-US" paraid="0" paraeid="{6d0b102d-122e-465d-9f02-dcabe497e586}{187}" style="font-weight: normal; font-style: normal; vertical-align: baseline; font-family: &quot;Segoe UI&quot;, Tahoma, Verdana, Sans-Serif; font-kerning: none; background-color: transparent; color: rgb(245, 245, 245); text-align: left; margin: 0px 0px 10.6667px; padding-left: 0px; padding-right: 0px; text-indent: 0px; font-size: 6pt;"><span class="ContentControl" cceid="{0799e006-e848-4c4d-b93d-d13364c3130e}{45}" cclevel="1" ccappearance="boundingbox" role="group" aria-label="Rich text content control paragraph"><span data-contrast="auto" xml:lang="EN-US" lang="EN-US" class="ContentControlBoundarySink" style="font-size: 11pt; text-decoration: underline; line-height: 18.3458px; font-family: WordVisi_MSFontService, Calibri, Calibri_EmbeddedFont, Calibri_MSCustomFont, Calibri_MSFontService, sans-serif;" ccindex="1">​</span><span data-contrast="auto" xml:lang="EN-US" lang="EN-US" class="TextRun Underlined" style="font-size: 11pt; text-decoration: underline; line-height: 18.3458px; font-family: WordVisi_MSFontService, Calibri, Calibri_EmbeddedFont, Calibri_MSCustomFont, Calibri_MSFontService, sans-serif;"><span class="NormalTextRun">Bold Text</span></span></span><span data-contrast="auto" xml:lang="EN-US" lang="EN-US" class="TextRun Underlined EmptyTextRun" style="font-size: 11pt; text-decoration: underline; line-height: 18.3458px; font-family: WordVisi_MSFontService, Calibri, Calibri_EmbeddedFont, Calibri_MSCustomFont, Calibri_MSFontService, sans-serif;"></span><span class="EOP" style="font-size: 11pt; line-height: 18.3458px; font-family: WordVisiPilcrow_MSFontService, Calibri, Calibri_EmbeddedFont, Calibri_MSCustomFont, Calibri_MSFontService, sans-serif;">&nbsp;</span></p></div></div><div class="OutlineElement Ltr"><div class="ParaWrappingDiv"><p class="Paragraph" xml:lang="EN-US" lang="EN-US" paraid="0" paraeid="{6d0b102d-122e-465d-9f02-dcabe497e586}{193}" style="font-weight: normal; font-style: normal; vertical-align: baseline; font-family: &quot;Segoe UI&quot;, Tahoma, Verdana, Sans-Serif; font-kerning: none; background-color: transparent; color: rgb(245, 245, 245); text-align: left; margin: 0px 0px 10.6667px; padding-left: 0px; padding-right: 0px; text-indent: 0px; font-size: 6pt;"><span class="ContentControl" cceid="{0799e006-e848-4c4d-b93d-d13364c3130e}{45}" cclevel="1" ccappearance="boundingbox" role="group" aria-label="Rich text content control paragraph"><span data-contrast="auto" xml:lang="EN-US" lang="EN-US" class="ContentControlBoundarySink" style="font-size: 11pt; text-decoration: underline line-through; line-height: 18.3458px; font-family: WordVisi_MSFontService, Calibri, Calibri_EmbeddedFont, Calibri_MSCustomFont, Calibri_MSFontService, sans-serif;" ccindex="1">​</span><span data-contrast="auto" xml:lang="EN-US" lang="EN-US" class="TextRun Underlined Strikethrough" style="font-size: 11pt; text-decoration: underline line-through; line-height: 18.3458px; font-family: WordVisi_MSFontService, Calibri, Calibri_EmbeddedFont, Calibri_MSCustomFont, Calibri_MSFontService, sans-serif;"><span class="NormalTextRun">Strikethrough Text</span></span></span><span data-contrast="auto" xml:lang="EN-US" lang="EN-US" class="TextRun Underlined Strikethrough EmptyTextRun" style="font-size: 11pt; text-decoration: underline line-through; line-height: 18.3458px; font-family: WordVisi_MSFontService, Calibri, Calibri_EmbeddedFont, Calibri_MSCustomFont, Calibri_MSFontService, sans-serif;"></span><span class="EOP" style="font-size: 11pt; line-height: 18.3458px; font-family: WordVisiPilcrow_MSFontService, Calibri, Calibri_EmbeddedFont, Calibri_MSCustomFont, Calibri_MSFontService, sans-serif;">&nbsp;</span></p></div></div></div><span class="WACImageGroupContainer"></span><span class="WACImageGroupContainer"></span><span data-contrast="auto" xml:lang="EN-US" lang="EN-US" class="TextRun Underlined" style="font-size: 11pt; text-decoration: underline; line-height: 18.3458px; font-family: WordVisi_MSFontService, Calibri, Calibri_EmbeddedFont, Calibri_MSCustomFont, Calibri_MSFontService, sans-serif;"></span><span data-contrast="auto" xml:lang="EN-US" lang="EN-US" class="TextRun Underlined Strikethrough" style="font-size: 11pt; text-decoration: underline line-through; line-height: 18.3458px; font-family: WordVisi_MSFontService, Calibri, Calibri_EmbeddedFont, Calibri_MSCustomFont, Calibri_MSFontService, sans-serif;"></span>\r\n</BODY>\r\n</HTML>'`
- When I typed in the same content in Word on Mac/Windows, calling `getHtml` returned `<html>\r\n\r\n<head>\r\n<meta http-equiv=Content-Type content="text/html; charset=utf-8">\r\n<meta name=Generator content="Microsoft Word 15 (filtered)">\r\n<style>\r\n\x3C!--\r\n /* Font Definitions */\r\n @font-face\r\n\t{font-family:"Cambria Math";\r\n\tpanose-1:2 4 5 3 5 4 6 3 2 4;}\r\n@font-face\r\n\t{font-family:Calibri;\r\n\tpanose-1:2 15 5 2 2 2 4 3 2 4;}\r\n /* Style Definitions */\r\n p.MsoNormal, li.MsoNormal, div.MsoNormal\r\n\t{margin-top:0in;\r\n\tmargin-right:0in;\r\n\tmargin-bottom:8.0pt;\r\n\tmargin-left:0in;\r\n\tline-height:107%;\r\n\tfont-size:11.0pt;\r\n\tfont-family:"Calibri",sans-serif;}\r\n.MsoChpDefault\r\n\t{font-size:11.0pt;\r\n\tfont-family:"Calibri",sans-serif;}\r\n.MsoPapDefault\r\n\t{margin-bottom:8.0pt;\r\n\tline-height:107%;}\r\n@page WordSection1\r\n\t{size:8.5in 11.0in;\r\n\tmargin:1.0in 1.0in 1.0in 1.0in;}\r\ndiv.WordSection1\r\n\t{page:WordSection1;}\r\n-->\r\n</style>\r\n\r\n</head>\r\n\r\n<body lang=EN-US style='word-wrap:break-word'>\r\n\r\n<div class=WordSection1>\r\n\r\n<p class=MsoNormal><u>Bold Text</u> </p>\r\n\r\n</div>\r\n\r\n</body>\r\n\r\n</html>\r\n`
- You can see the result returned from Word on Web is not using standard HTML tag, but Word on Mac is using the standard tag `<u></u>`.
- When calling `insertHtml()` on Web with the result returned from `getHtml()` on Web, it cannot render the correct style itself. However, Word on Mac can render it correctly. This [issue](https://github.com/OfficeDev/office-js/issues/2483) mentioned the same thing.

**Comment by yilin4** [comment]
@monominia I will investigate this and respond to you if there is anything found.
