### ISSUE TITLE
Using Office.context.mailbox.getCallbackTokenAsync on a shared mailbox fails

### ISSUE THREAD

**Issue by kworksltd** [OfficeDev/office-js#3748]
Using Office.context.mailbox.item.getSharedPropertiesAsync on a shared mailbox fails. This also happens when using the Script Lab for Outlook add-in, using the shared mailbox example. The expected behaviour when selecting the 'Run operation as delegate on selected message' returns nothing. Debugging the code reveals the getSharedPropertiesAsync call is returning an error: OSF.DDA.Error,  Code 9018, "GenericTokenError". I expect the add-in to show the email's properties but instead it shows nothing.

I have tried this on the web client for Outlook on Windows 10 and the latest Outlook Client on Windows 10. I have checked all the settings on the shared mailbox to ensure I have the correct permissions and that it is visible in GAL

**Comment by exextoc** [comment]
Can you share the code snippet you are using

**Comment by kworksltd** [comment]
This is the code taken from Script Lab for Outlook - the Perform operation as a delegate  example.
```
$("#get").click(get);
$("#run-message").click(runOnMessage);
$("#run-appointment").click(runOnAppointment);

function get() {
  if (!Office.context.mailbox.item.getSharedPropertiesAsync) {
    console.error("Try this sample on an item from a shared folder.");
    return;
  }

  Office.context.mailbox.item.getSharedPropertiesAsync(function(result) {
    console.log(result.value);
  });
}

function runOnMessage() {
  if (!Office.context.mailbox.item.getSharedPropertiesAsync) {
    console.error("Try this sample on a message from a shared folder.");
    return;
  }

  Office.context.mailbox.getCallbackTokenAsync({ isRest: true }, function(result) {
    if (result.status === Office.AsyncResultStatus.Succeeded && result.value !== "") {
      Office.context.mailbox.item.getSharedPropertiesAsync(
        {
          // Pass auth token along.
          asyncContext: result.value
        },
        function(result2) {
          let sharedProperties = result2.value;
          let delegatePermissions = sharedProperties.delegatePermissions;

          // Determine if user has the appropriate permission to do the operation.
          if ((delegatePermissions & Office.MailboxEnums.DelegatePermissions.Read) != 0) {
            var ewsId = Office.context.mailbox.item.itemId;
            var restId = Office.context.mailbox.convertToRestId(ewsId, Office.MailboxEnums.RestVersion.v2_0);
            let rest_url =
              sharedProperties.targetRestUrl + "/v2.0/users/" + sharedProperties.targetMailbox + "/messages/" + restId;

            $.ajax({
              url: rest_url,
              dataType: "json",
              headers: { Authorization: "Bearer " + result2.asyncContext }
            })
              .done(function(response) {
                console.log(response);
              })
              .fail(function(error) {
                console.error(error);
              });
          }
        }
      );
    }
  });
}

function runOnAppointment() {
  if (!Office.context.mailbox.item.getSharedPropertiesAsync) {
    console.error("Try this sample on an appointment from a shared folder.");
    return;
  }

  Office.context.mailbox.getCallbackTokenAsync({ isRest: true }, function(result) {
    if (result.status === Office.AsyncResultStatus.Succeeded && result.value !== "") {
      Office.context.mailbox.item.getSharedPropertiesAsync(
        {
          // Pass auth token along.
          asyncContext: result.value
        },
        function(result2) {
          let sharedProperties = result2.value;
          let delegatePermissions = sharedProperties.delegatePermissions;

          // Determine if user has the appropriate permission to do the operation.
          if ((delegatePermissions & Office.MailboxEnums.DelegatePermissions.Read) != 0) {
            var ewsId = Office.context.mailbox.item.itemId;
            var restId = Office.context.mailbox.convertToRestId(ewsId, Office.MailboxEnums.RestVersion.v2_0);
            let rest_url =
              sharedProperties.targetRestUrl + "/v2.0/users/" + sharedProperties.targetMailbox + "/events/" + restId;

            $.ajax({
              url: rest_url,
              dataType: "json",
              headers: { Authorization: "Bearer " + result2.asyncContext }
            })
              .done(function(response) {
                console.log(response);
              })
              .fail(function(error) {
                console.error(error);
              });
          }
        }
      );
    }
  });
}
```

**Comment by exextoc** [comment]
Can you check if getCallbackTokenAsync api alone returns the token as expected for your account?

**Comment by kworksltd** [comment]
Yes - this works fine for emails in my account.

Kind regards,
Sharad

Sharad Patel
Filestar
Tel: 0203 318 3113 ext 2
Mobile: 0780 1657 052

Web: filestar.eu
________________________________

**Comment by exextoc** [comment]
@kworksltd The error mentioned above is related to token API and not specific to getSharedPropertiesAsync
Could you please confirm if  getCallbackTokenAsync api is working in the **shared account** by running below code?
Sample code:
  Office.context.mailbox.getCallbackTokenAsync(
	function (asyncResult)
	{
		console.log(JSON.stringify(asyncResult));
	}
);

**Comment by kworksltd** [comment]
It is the getCallbackTokenAsync call (on the shared folder - works fine on the non-shared folder) that is returning the error. Please see the attached screenshot for the code and response in a debug window for Edge. The console window at the bottom shows the error. Although this is my code, I get the same response from the Script Lab sample I originally posted.

<img width="663" alt="Screenshot 2023-10-17 at 13 13 09" src="https://github.com/OfficeDev/office-js/assets/2692356/744163b5-1c00-4039-8d57-f8677c29a2a6">

**Comment by exextoc** [comment]
Thanks for confirming. Has this been working previously, and have you only started receiving the error recently?

**Comment by kworksltd** [comment]
This has been working perfectly for non-shared inboxes (and still does). Recently we added support for shared inboxes and therefore followed the Script Lab example on how to get the content for an email from a shared inbox and obtain a token for the shared inbox. This is when we encounter the issue. Our getEmailCallbackToken routine (as shown in my previous screenshot) returns a token just fine for a non-shared inbox, but returns the error when it is a shared inbox.


Kind regards,
Sharad

Sharad Patel
Filestar Support


[cid:fe3886a5-0736-417f-be28-56dff8dacb08]

<http://filestar.eu/>


________________________________

**Comment by kworksltd** [comment]
This is the set-up of the shared inbox that I have been using with the add-in.
<img width="527" alt="Screenshot 2023-10-17 at 15 25 24" src="https://github.com/OfficeDev/office-js/assets/2692356/716dca9d-dace-4a87-9983-88b7df9d0cc9">

**Comment by exextoc** [comment]
@kworksltd  Thanks for the details. We can repro the issue. It has been put on our backlog. We unfortunately have no timelines to share at this point. 
Updating the title with the correct API name.

**Comment by exextoc** [comment]
Hi @kworksltd, we have checked in a fix for this issue and the same is available in OWA client version 20231124004.01 and above. Please confirm if the issue is resolved for you.

**Comment by kworksltd** [comment]
I tried my own add-in but I still get the same GenericTokenError error. I cleared my browser cache and reloaded OWA. Is there something I need to do when building my add-in? How do I check what OWA client version I have?
p.s. I tried to test this with the Outlook Script Lab add-in (which I had used previously to verify the issue) but that is not working at all for me now - it just keeps saying 'No script to run'.

**Comment by plamenbotev** [comment]
Could this be related to https://github.com/OfficeDev/office-js/issues/3886? 
I have also tested and still get GenericTokenError when trying to obtain EWS and REST tokens for a shared mailbox, added as a shared folder.

**Comment by ajays-msft** [comment]
@plamenbotev It is not related to the script lab issue.

@kworksltd - Some fixes related to shared mailbox went in recently and changes are rolled out to prod. Can you please try again and check if you are still facing the issue?

**Comment by sahanar28** [comment]
<img width="940" alt="MicrosoftTeams-image (13)" src="https://github.com/OfficeDev/office-js/assets/88164424/9652afc7-4118-4186-9017-b36fee12f0e3">
Hi, @exextoc Even I am facing the same issue with 
Using Office.context.mailbox.getCallbackTokenAsync on a shared mailbox with the exact same error message and error code.
I have already raised a github ticket for it. Is this issue fixed or when can we expect it be fixed?

**Comment by kworksltd** [comment]
> @kworksltd - Some fixes related to shared mailbox went in recently and changes are rolled out to prod. Can you please try again and check if you are still facing the issue?

I have tested this again today and I am still getting the same error response when using the shared inbox. is there a sample add-in you can provide to test this outside of our own code? Outlook Script-Lab that I had previously used to test this is now having its own problem (already reported).

**Comment by exextoc** [comment]
@kworksltd  Could you please confirm which Extension point is being used by your Add-in here?

**Comment by kworksltd** [comment]
The Extension point  in my add-in is **MessageReadCommandSurface**

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding shared mailbox. It has been put on our backlog. We unfortunately have no timelines to share at this point
 
Internal tracking id: Office: 4023303

**Comment by sajalsoni6** [comment]
@exextoc i'm still facing this issue. when will it be fixed?

**Comment by ingin97** [comment]
@exextoc We are also facing this issue getting GenericTokenError (code 9018) when trying to obtain EWS or REST tokens for a shared mailbox, added as a shared folder.

**Comment by parlato-vooma** [comment]
@exextoc we're facing the same issue; getting a GenericTokenError (code 9018) when trying to fetch an access token. Code below; we're using https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js. This did appear to work for some time for us, and recently broke (within the last week, maybe). I don't think the users facing this issue are using a shared inbox, however - I'm not entirely sure what that means.

```javascript
const getAccessToken = async () => {
  return new Promise<string>((resolve, reject) => {
    Office.context.mailbox.getCallbackTokenAsync(
      { isRest: true },
      function (result) {
        if (result.status === Office.AsyncResultStatus.Succeeded) {
          resolve(result.value);
        } else {
          reject(result.error);
        }
      }
    );
  });
};
```

**Comment by ajays-msft** [comment]
@kworksltd , @ingin97 -The shared mailbox token issue is now resolved. Fix is available in prod.

**Comment by kworksltd** [comment]
I can confirm that this is now working without presenting the error as originally submitted. I am therefore happy to mark this as closed.

**Comment by kdeshpande-methodcrm** [comment]
We are still facing the same issue. Do we know how this can be fixed? Or was there an update from Microsoft that we missed?

**Comment by mmanjaree-msft** [comment]
@kdeshpande-methodcrm  Can you please open a separate issue and add repro steps and video/screenshot there

**Comment by kdeshpande-methodcrm** [comment]
@mmanjaree-msft My colleague has opened an issue here : https://github.com/OfficeDev/office-js/issues/4583 
As for the reproduction steps, the comment - https://github.com/OfficeDev/office-js/issues/4583#issuecomment-2189034372 has an example to demonstrate the same issue we are facing
