### ISSUE TITLE
[Outlook] Dialog gets orphaned if user closes task pane (Outlook for Mac)

### ISSUE THREAD

**Issue by ShannonLCapper** [OfficeDev/office-js#380]
In Outlook for Mac, closing the task pane does not automatically close an open dialog spawned by that task pane.

## Expected Behavior

When a taskpane gets closed (either because the user manually closed the task pane via the X button, or because they closed the window in which the task pane existed), I would expect a dialog opened by that task pane to also be closed. This is the behavior in Windows Outlook 2013 and 2016. In OWA, it is not possible to interact with the underlying Outlook window when a dialog is open, so the issue is moot there.

## Current Behavior

In Outlook for Mac only, when a taskpane is closed, the dialog remains open. This is especially problematic because the dialog is now orphaned. Any calls to `Office.context.ui.messageParent` from the dialog get thrown into the void without any thrown errors, and the dialog is unable to close itself (since only the task pane has the ability to call `Dialog.close()`). The dialog has no way of even detecting that it has lost connection to its task pane.

## Steps to Reproduce, or Live Example

* Additional details:
  1. In Outlook for Mac, open a taskpane in a compose message window.
  2. Call `Office.context.ui.displayDialogAsync` from inside the taskpane.
  3. Once the dialog is open, move it over to reveal the compose message window underneath.
  4. Click the X above the taskpane to close it, or close the whole compose message window. The dialog will remain open (unlike in Windows Outlook).

## Context

Our plugin makes heavy use of the DialogAPI and the ability to send a message from the dialog to the underlying taskpane. Our dialog also contains a `Close` button that, when clicked, sends a message to the task pane that will then call `Dialog.close()`. However, there is nothing stopping a user from moving the dialog over and closing the task pane, sending the mail in which the task pane is running, or closing the compose window altogether. This causes several problems:
- Our dialog becomes basically non-functional --  it can no longer send messages to the task pane to interact with the majority of the OfficeJS API.
- The dialog cannot detect when it is in this state, since no error is thrown by `Office.context.ui.sendMessage`. That means it can't update its UI to tell the user that it is no longer functional and should be closed. We've worked around this by using a "heartbeat" in local storage: the task pane increments a variable in local storage on an interval, and the dialog listens for this variable in local storage. If the dialog detects that the heartbeat has stopped incrementing, it knows the task pane has been closed.
- Even if the dialog can detect that it is in this orphaned state, it cannot close itself programmatically. Our `Close` button no longer works since it relies on a message to the task pane to trigger `Dialog.close()`. As it turns out, in Mac only, the unsupported API `window.close()` actually does succeed in closing the dialog. However, since this API is unsupported, we would prefer not to depend upon it in a production system.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.21.117.0
* Operating System: MacOS High Sierra v 10.13.6 (17G3025)
* Browser (if using Office Online): N/A

## Useful logs

N/A

**Comment by ShannonLCapper** [comment]
I can no longer repro this issue (on Mac Outlook version 16.22.220.1)! That's awesome that this has been fixed! Does anyone happen to know if this got fixed on the Mac application side, or on the JS side?

**Comment by macOutlookExtensibility** [comment]
Yes, this has been fixed couple of weeks back and now out to public.

**Comment by SWei1234** [comment]
But it still happened on windows outlook. 
1.set popup window:
Office.context.ui.displayDialogAsync(URL , {
    height: 100,
    width:100,
    displayInIframe: false,
    promptBeforeOpen: true
  },fucntion......
2. then messageParent can not deliver message and window.close() can not close the window.
is this a bug?

**Comment by SWei1234** [comment]
> Yes, this has been fixed couple of weeks back and now out to public.

But it still happening on windows outlook.
1.set popup window:
Office.context.ui.displayDialogAsync(URL , {
height: 100,
width:100,
displayInIframe: false,
promptBeforeOpen: true
},fucntion......
2. then messageParent can not deliver message and window.close() can not close the window.
is this a bug?

**Comment by linaelf** [comment]
> > Yes, this has been fixed couple of weeks back and now out to public.
> 
> But it still happening on windows outlook.
> 1.set popup window:
> Office.context.ui.displayDialogAsync(URL , {
> height: 100,
> width:100,
> displayInIframe: false,
> promptBeforeOpen: true
> },fucntion......
> 2. then messageParent can not deliver message and window.close() can not close the window.
> is this a bug?

I have the exact same issue as yours. Did you solve it?
JS in host page:
```JavaScript
Office.context.ui.displayDialogAsync(
        fullUrl,
        { height: 60, width: 30 },
        function (result) {
            console.log("Dialog has initialized. Wiring up events");
            console.log(`${JSON.stringify(result)}`);
            loginDialog = result.value;
            loginDialog.addEventHandler(Office.EventType.DialogMessageReceived, () => {
                console.log("Dialog message received");
            });
            loginDialog.addEventHandler(Office.EventType.DialogEventReceived, () => {
                console.log(`Dialog event received!!`)
            })
        });
```

JS in Dialog:
```JavaScript
Office.onReady(() => {
    console.log(`auth completed`);
    Office.context.ui.messageParent("test");
    console.log('pass info back to outlook');
});
```

**Comment by RuckertSolutions** [comment]
Facing the same issue on Windows with Ms Outllok 2016 (16.0.4954.1000) 32bit. @MS in which version did you apply the fix ? 

If I close the taskpane, the dialog window goes back to the initial loading spinner but does not close itself.
