### ISSUE TITLE
Excel custom functions not loading on new machines, causing error in loading Add-in

### ISSUE THREAD

**Issue by bhattikashif** [OfficeDev/office-js#3843]
# Provide required information needed to triage your issue
We have an excel add-in containing customs functions and taskpane and users were using without any problem. However recently many users have reported and we have tested it ourselves also, that if there is a fresh machine/laptop having pre-installed office with windows. When we login our Microsoft 365 Enterprise licenses users, and try to install Add-in, it fails and gives error about custom functions cannot be installed. This happens only on new laptops, if we remove add-in from existing machines and then try to install it, it installs successfully without any problem.

My office version is Microsoft® Excel® for Microsoft 365 MSO (Version 2310 Build 16.0.16924.20054) 32-bit 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PX desktop
* Host [Excel, Word, PowerPoint, etc.]: ______Excel
* Office version number: ______16.0.16924.20054
* Operating System: ______ windows 10 build 19045.3636
* Browser (if using Office on the web): ______
 
## Expected behavior

As there is no problem in add-in, it should be able to install custom functions on new machines with pre-installed office (as it is currently doing with old machines)

## Current behavior

Excel gives error that It cannot load custom functions, hence Add-in installation fails.

## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by ruijiaMS** [comment]
Hi @bhattikashif,
Thanks for letting me know this issue! could you please provide more information like which add in you added and the screenshot of the error coming up?

**Comment by bhattikashif** [comment]
I have developed this add-in for my company, and it is deployed using Admin Centre. Sometimes I get error about custom functions not installed correctly, however when I tried it now I got this error 
![image](https://github.com/OfficeDev/office-js/assets/103940975/fadbce5b-28e0-4e0c-ac95-e7b7f8dd9515)
 
![image](https://github.com/OfficeDev/office-js/assets/103940975/b5a904fe-7fd2-4f6e-82f6-6efa8c7351fd)

While trying to figure out the issue, I compared contents of %LOCALAPPDATA%\Microsoft\Office\16.0\Wef\ folders on both systems where it was installed and other with error. Only difference was CustomFunctions was empty on system with error. When I copied this folder from other one, add-in started working.

**Comment by eqinox76** [comment]
@bhattikashif Many many thanks for the workaround! We were going a bit crazy.

**Comment by ruijiaMS** [comment]
Hi @bhattikashif and @eqinox76,
We have raised an internal bug #8549174 to check this "Error installing add-ins" issue. This issue might impact since Oct. fork and only impact the desktop Excel, the online excel should always work.
There are some workarounds for this issue, you can either copy the CustomFunctions file to the new machine or you can sideload the Office add-in for new machine. Here is a reference about how to sideload it: https://learn.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins. Any update about the fix will post here. Thanks!

**Comment by penglongzhaochina** [comment]
Hi all, We have fixed this issue, could you please verify this issue? Remember to clear the wef cache before you try it.

**Comment by pbowden91** [comment]
@penglongzhaochina this is possibly still an issue for macs? Seeing similar symptoms and resolutions

**Comment by penglongzhaochina** [comment]
Hi @pbowden91 ，

This is a regression at that time. We already fixed that issue. You can create a new github issue if you met this behavior for mac.

Thanks.
