### ISSUE TITLE
Outlook: Unable to remove sideloaded add in

### ISSUE THREAD

**Issue by aantimengocom** [OfficeDev/office-js#3923]
I am working on renewing an old Outlook Addin, and in the process I have made changes to the manifest.xml file to enable OAuth,

When removing the old Add-in (and also the new Add-in) - they do not dissappear from the "Apps" list (Compose form) 

![image](https://github.com/OfficeDev/office-js/assets/67316229/00c7153b-1517-4889-9957-3ab6dc91d3d1)

... in the above image you see that there are NO Custom Addins "**No add-ins found**." 

As seen in this image below - both add-ins are still there.. 

![image](https://github.com/OfficeDev/office-js/assets/67316229/17a18d8a-6bff-4685-8d3a-77b2f59dbabc)

This is a HUGE issue and we cannot move forward with migrating customers before there is a solution. The same happens on the Outlook Classic on windows desktop - and even after deleting the files here : C:\Users\Administrator\AppData\Local\Microsoft\Outlook\HubAppFileCache
and here: C:\Users\Administrator\AppData\Local\Microsoft\Office\16.0\Wef - and reopening Outlook Desktop - it just repopulate the folders - and the dual "ghost" addins are still there .. how do i remove them? 

Sometimes the addins dissappear right away when removing them in the sideload site - and other times they need weeks before they dissappear .. how do i explain this to a customer? 

Regards,
Allan

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding uninstallation of add-ins. This issue has been added to our backlog and we, unfortunately, have no timeline to share at this point. We will update this post once the fix is available. 

Internal Tracking ID: 4179908

**Comment by gbl-Time** [comment]
Months ago using "Get add-ins" in Outlook (which has since dissapeared) and using sideload did not have this problem. Now it does. 

Installing/uninstalling Outlook office add-ins takes unknown amount of time  and there seem to be nothing to do abouit it. 

A small time frame for caching when installing/uninstalling could perhaps make sense (but would certainly prefer no caching!), but hours or even days is a really bad use case both developing but also when installing office add-ins at customers.

**Comment by bas-eenhoorn** [comment]
> A small time frame for caching when installing/uninstalling could perhaps make sense (but would certainly prefer no caching!), but hours or even days is a really bad use case both developing but also when installing office add-ins at customers.

The weird part is that it actually worked instantly, a few months ago, for like years. Addins were instantly removed and added. Now they take 15 minutes, or maybe  20 hours.

**Comment by ajays-msft** [comment]
This issue should be resolved now. The fix is checked in and available in prod since Jan 10th.

**Comment by asli-surveill** [comment]
@ajays-msft I still have this problem.  The sideloaded app looks uninstalled everywhere but it still shows up in the ribbon and due to the add-in functionality, prevents from me sending emails.
