### ISSUE TITLE
addFileAttachmentAsync on Outlook Web (OWA) throws Sys.ArgumentOutOfRangeException when attaching files larger than 20MB.

### ISSUE THREAD

**Issue by guzman-rc** [OfficeDev/office-js#3994]
When I attach files larger than 20 MB with the Office.context.mailbox.item.addFileAttachmentAsync function I get the following error:
Uncaught Sys.ArgumentOutOfRangeException: Sys.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. Parameter name: base64File

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: Mac OS X and Windows 10
* Browser (if using Office on the web): Edge and Chrome.
 
## Expected behavior

It should allow you to attach the file.

## Current behavior

It is not allowed to attach files larger than 20 MB. 

## Steps to reproduce

1. To reproduce the error install our application from the url: https://appsource.microsoft.com/es-es/product/office/WA200003633
2. Create a new email.
3. Click on MetaClean icon from tool bar and from the right-hand panel attach a file larger than 20MB.
    You can try the following file: https://www.adarsus.com/downloads/CCN/Webinar/Webinar_metaOLVIDO.pptx

## Context

This error affects all users.

## Useful logs

- [X] Console errors
![Error_2](https://github.com/OfficeDev/office-js/assets/96702862/cc706c40-02f9-42bd-beb0-3e8ef69b3c87)

- [X] Screenshots
![Error_1](https://github.com/OfficeDev/office-js/assets/96702862/87f89f9d-da35-4b02-96ec-13e52101c150)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
@guzman-rc Are you using API [Item.addFileAttachmentFromBase64Async](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/outlook/preview-requirement-set/office.context.mailbox.item#methods)? There is a limit on the size of the attachment, for base64 it is 27,892,122 characters. You can check all limits at [limits of API](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/limits-for-activation-and-javascript-api-for-outlook-add-ins#limits-for-javascript-api).

**Comment by guzman-rc** [comment]
As you can see in the screenshot, I am using: Office.context.mailbox.item.addFileAttachmentAsync
![Imagen 1](https://github.com/OfficeDev/office-js/assets/96702862/41406e26-68be-4f2c-b33d-664fe76b9de8)

**Comment by exextoc** [comment]
@guzman-rc Thanks for reporting this issue. I could reproduce this problem. We have created a bug and added to our backlog. Unfortunately, we don't have any timeline to share at this point.
Tracking ID: 250582

**Comment by exextoc** [comment]
Can you please share the exact size of the file which is being added?

**Comment by guzman-rc** [comment]
You can test with this file (23,6 MB):
https://www.adarsus.com/downloads/CCN/Webinar/Webinar_metaOLVIDO_v2.0.pptx

**Comment by guzman-rc** [comment]
Hi,

You can test with this file (23,6 MB):
https://www.adarsus.com/downloads/CCN/Webinar/Webinar_metaOLVIDO_v2.0.pptx

Best regards,
Guzmán Rejón.

From: Outlook Add-ins Team - MSFT ***@***.***>
Reply-To: OfficeDev/office-js ***@***.***>
Date: Monday, 22 January 2024 at 07:49
To: OfficeDev/office-js ***@***.***>
Cc: guzman-rc ***@***.***>, Mention ***@***.***>
Subject: Re: [OfficeDev/office-js] addFileAttachmentAsync on Outlook Web (OWA) throws Sys.ArgumentOutOfRangeException when attaching files larger than 20MB. (Issue #3994)


Can you please share the exact size of the file which is being added?

**Comment by guzman-rc** [comment]
Is there any news on this issue?

**Comment by rkpathak** [comment]
This issue is fixed and rolled out now.

[Outlook Add-ins Engineering Team]

**Comment by guzman-rc** [comment]
The error still occurs.

Outlook Web (OWA) allows attachments larger than 20 MB, but if we use the function:`Office.context.mailbox.item.addFileAttachmentAsync` it returns an error indicating that the file is too large.

If you attach the file: https://www.adarsus.com/downloads/tmp/MetaCleanPlatform.pptx directly the file is added successfully, but if you use the AddIn: https://appsource.microsoft.com/es-es/product/office/WA200003633 which uploads the file through the `addFileAttachmentAsync` function it returns an error.

![AttachError](https://github.com/OfficeDev/office-js/assets/96702862/48e8d602-bfa7-4995-8ac7-e960d0350bf5)

**Comment by ajays-msft** [comment]
@guzman-rc - You mean the issue still occurs for the same file originally reported, https://www.adarsus.com/downloads/CCN/Webinar/Webinar_metaOLVIDO_v2.0.pptx which is 23.6 mb?

OR 

Issue now occurs for a different file https://www.adarsus.com/downloads/tmp/MetaCleanPlatform.pptx  which is 32.5 mb?

**Comment by guzman-rc** [comment]
Hi,

The error occurs for the file https://www.adarsus.com/downloads/tmp/MetaCleanPlatform.pptx

**Comment by ajays-msft** [comment]
@guzman-rc - Then I would consider this as issue fixed for original problem. The new file is bigger than the allowed limit in OWA. I will work on getting the documentation updated. @samantharamon - FYI

[Attachment api limitation in OWA](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/limits-for-activation-and-javascript-api-for-outlook-add-ins#limits-for-javascript-api)

**Comment by guzman-rc** [comment]
What is the maximum size allowed in OWA?

From OWA it allows me to attach the 32MB file **if I attach it directly from the "Attach File" button**, but if I attach it using the `Office.context.mailbox.item.addFileAttachmentAsync` function it returns an error.

In both cases I'm using OWA but it only fails with addFileAttachmentAsync and it should work, right?

**Comment by ajays-msft** [comment]
@guzman-rc - Please go through this link [Attachment api limitation in OWA](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/limits-for-activation-and-javascript-api-for-outlook-add-ins#limits-for-javascript-api)

This is limitation with the office js api.

**Comment by guzman-rc** [comment]
According to the url:
https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/limits-for-activation-and-javascript-api-for-outlook-add-ins
**addFileAttachmentAsync** allows to **attach 25 MB** files but this method does not allow to attach 22.3 MB files in Outlook on the web.

The **Office.context.mailbox.item.addFileAttachmentAsync** method returns the following error message: **The attachment cannot be added because it is too big.**

I have tested it with this file: https://www.adarsus.com/downloads/tmp/Test_22MB.docx
