### ISSUE TITLE
masterCategories.getAsync returns error while multiple items are selected (Outlook on the web)

### ISSUE THREAD

**Issue by manuelsidler** [OfficeDev/office-js#4146]
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: -
* Operating System: macOS 14.3.1
* Browser (if using Office on the web): Edge
 
## Expected behavior
When calling `Office.context.mailbox.masterCategories.getAsync` I'd expect to get a list of all master categories, even if I have multi select support enabled and multiple items selected.

## Current behavior
When selecting multiple items and calling `Office.context.mailbox.masterCategories.getAsync`, the result contains an error:
```
{"name":"Internal Error","message":"An internal error has occurred."}
```

It works fine on Outlook for Mac

## Steps to reproduce
1. Enable multi select support
2. Select multiple mails
3. Call `Office.context.mailbox.masterCategories.getAsync`
4. Result returns error

## Link to live example(s)
You can also clone this GitHub repo to reproduce the bug: https://github.com/manuelsidler/outlook-addin-multiselect
1. Sideload `manifest.xml` in Outlook on the web
2. Select multiple mails
3. Open the add-in (Contoso Add-In -> Show Taskpane)
4. Click on _Get Master Categories_

**Comment by manuelsidler** [comment]
@exextoc any comment on this issue?

**Comment by ajays-msft** [comment]
@manuelsidler - I am able to repro the issue. We are working on a fix for this. Internal tracking id: 4353361

**Comment by shighosh-msft** [comment]
This issue has been fixed. Thank you for raising the issue and helping us make the product better.

**Comment by manuelsidler** [comment]
Unfortunately, the error still appears in Office on the web. Can you reproduce it on your side?

**Comment by rajjha-msft** [comment]
Hey @manuelsidler 

Can you please share a video of the repro ?

**Comment by manuelsidler** [comment]
Hello @rajjha-msft 

I'm not able to reproduce the error anymore today. It works like a charm 🤷‍♂️

I'll post a video in case the error appears again. Thanks!
