### ISSUE TITLE
mailbox.item.getInitializationContextAsync() never calls callback function in Old Windows Outlook

### ISSUE THREAD

**Issue by sangaman** [OfficeDev/office-js#4161]
# `mailbox.item.getInitializationContextAsync()` never calls callback function in Old Windows Outlook

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft® Outlook® for Microsoft 365 MSO (Version 2401 Build 16.0.17231.20194) 64-bit - Old Outlook
* Operating System: Windows 11

## Expected behavior

The callback function passed to `getInitializationContextAsync()` is called.

## Current behavior

The callback function passed to `getInitializationContextAsync()` is never called.

## Steps to reproduce

1. Use Old Outlook with the version above on a Windows 11 PC
2. Call `getInitializationContextAsync()` and pass a callback function to it.
3. Observe that the callback function is never called.

# Provide additional details

This bug appears to have been introduced recently, within the last few weeks, as our code used to work on Old Outlook. The same code that fails on Old Outlook works on New Outlook on Windows and also on Outlook for MacOS.

## Context

We are trying to read the initialization context from an Actionable Message. We have code that has been working for several weeks, similar to the code in the example [here](https://learn.microsoft.com/en-us/javascript/api/outlook/office.messageread?view=outlook-js-preview#outlook-office-messageread-getinitializationcontextasync-member(1)), which no longer works on Old Outlook.

**Comment by Oleg-O** [comment]
We've rolled out a change that should fix this and it should propagate to all users within a few hours.
Thanks for reporting this issue, internal tracking id is office:8774113.

**Comment by sangaman** [comment]
@Oleg-O Is there a version or build number where this issue is fixed? We're still seeing this issue as of this morning.

**Comment by Oleg-O** [comment]
@sangaman this was a service change - we've updated office.js libraries on CDN. Users that still see this are seeing it because the browser component used by the naive client is caching the older JS. This will age out at some point but users can also open the addin taskpane and hit CTRL+F5 to force refresh of the add-in content including the libraries it loads.

**Comment by sangaman** [comment]
@Oleg-O We're still seeing this issue as of this morning, this is after trying restarts and force refreshes.

The current version is Microsoft® Outlook® for Microsoft 365 MSO (Version 2401 Build 16.0.17231.20236) 64-bit

**Comment by Oleg-O** [comment]
@sangaman this is not expected... we're looking into this further to understand why some users are not getting the updated files from CDN.

**Comment by Oleg-O** [comment]
An update here. We've pushed another change to the office.js today and we're hoping this should have helped address this issue. Due to complexity of the content distribution system all up and various caching in place, it's a bit hard to estimate how quickly it'll get to everyone. We think it should start having effect by now. It would help if anyone affected could let us know if the issue is being resolved or not and without forcing refresh (ultimately we want to resolve it without asking everyone to force refresh).

**Comment by sangaman** [comment]
As of this morning, after a reboot we are still experiencing this issue. Do the version numbers matter here? Should I keep sharing those?

**Comment by Oleg-O** [comment]
@sangaman has this been resolved? We believe this should had been resolved for everyone yesterday. Can you please confirm?

**Comment by sangaman** [comment]
@Oleg-O We are still seeing this issue as of this afternoon, even after a restart.

**Comment by Oleg-O** [comment]
This really shouldn't be happening anymore. Is this still a problem? How many users are affected? Our telemetry indicates (and other users reports align with it) that this should have been fixed last week... I do wonder if there is a separate issue so please let us know if this reproduces and what the symptoms are.

**Comment by sangaman** [comment]
It finally worked this morning, not at first but it did after a restart.
