### ISSUE TITLE
Outlook Addin Office.context.mailbox.makeEwsRequestAsync calls are failing with 403 forbidden for outlook.com accounts

### ISSUE THREAD

**Issue by JulienSchneider** [OfficeDev/office-js#4353]
# Provide required information needed to triage your issue

I'm implementing an Outlook add-in.
All calls to Office.context.mailbox.makeEwsRequestAsync are all failing with 403 forbidden for outlook.com (outlook.live.com) accounts. It works fine for Microsoft 365 accounts (outlook.office.com).
The EWS calls I make are "GetItem" (to get messages by id) and "CreateItem" to send messages (with MessageDisposition="SendAndSaveCopy") but the behavior is the same for any EWS call.

Looks very similar to https://github.com/OfficeDev/office-js/issues/4292

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: All
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Online / Outlook for Windows v. 2403 / ...
* Operating System: Windows 11 / Mac
* Browser (if using Office on the web): Edge, Chrome, Firefox
 
## Expected behavior

Office.context.mailbox.makeEwsRequestAsync call is successful for outlook.com accounts

## Current behavior

Office.context.mailbox.makeEwsRequestAsync call fail for outlook.com accounts

## Steps to reproduce

1. Call Office.context.mailbox.makeEwsRequestAsync from an Outlook add-in with an outlook.com (outlook.live.com) account
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

This is what I see happening in the browser console
* A 1st POST call to https://outlook.live.com/owa/0/service.svc?action=GetClientAccessToken&UA=0&app=Mail&n=69 works fine
* A 2nd POST call to https://outlook.live.com/owa/0/service.svc?action=ExecuteEwsProxy&UA=0&app=Mail&n=70 fails with the following response:
```
{
	"WasProxySuccessful": false,
	"ErrorMessage": "The remote server returned an error: (403) Forbidden.",
	"StatusCode": 0,
	"StatusDescription": null,
	"Body": null
}
```

**Comment by rkpathak** [comment]
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point. 

Internal tracking id: Office: [269409]

**Comment by tourloupis** [comment]
I am experiencing the same problem using <verbatim>makeEwsRequestAsync</verbatim> in the Outlook add-in that I have developed and tested against an outlook.live.com web client using Visual Studio 2022.  It was working fine last year up until December 2023, and then failed with (403) forbidden without any reason.

Note that I have correctly defined the permission of <verbatim>ReadWriteMailbox</verbatim> in the XML manifest of the add-in, an excerpt of which I have provided below.

<img width="875" alt="image" src="https://github.com/user-attachments/assets/aa2a991c-ddc7-41e7-a927-8a440e4f9ac3">

This is in accordance with the [Authentication and Permission Considerations for makeEwsRequestAsync](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/web-services#authentication-and-permission-considerations-for-makeewsrequestasync).

<img width="599" alt="image" src="https://github.com/user-attachments/assets/bcf1cc84-21f5-46b1-99c0-490de5614c01">

I may be wrong but, I suspect that the cause of the problem could be due to the <verbatim>OAuthAuthentication</verbatim> parameter being set to <verbatim>false</verbatim> on the Client Access server EWS directory.  If so, I suspect that this is the same cause of issue #4292 and possibly the cause of issue #4124 which has since been resolved externally.

**Comment by lunarwtr** [comment]
I am also having problems with this.  It is affecting my ability to build addin.   Is there any update?

**Comment by tourloupis** [comment]
Hi Kelly, the only update that I had was a new version of the TypeScript package for MSBuild available under the NuGet Manager, not to mention many updates to Visual Studio 2022 Community Edition and, presumably, the MSBuild compiler.

![image](https://github.com/user-attachments/assets/738261f9-7cbb-4709-ad1e-1367ca25f806)

Unfortunately, this has made no difference.  Still getting the same error.

**Comment by rkpathak** [comment]
This issue has been fixed and rolled out. For outlook.com accounts makeEwsRequestAsync API will work now. @JulienSchneider

**Comment by lunarwtr** [comment]
I'm still having issue occur for a simple "GetServerTimeZones" call.    403 Forbidden

I wanted to do a lighter weight call vs GetItem to see if EWS was broken, so I changed our addin to do a GetServerTimeZones to see if EWS was supported / turned on before doing other calls.

**Comment by lunarwtr** [comment]
@rkpathak  can this be looked at again?  i tested the day you said it was fixed and was still getting the error.

**Comment by JulienSchneider** [comment]
Hi,

I just tried it out and I still have the same issue with xxx@outlook.com accounts:
`error: Object { name: "GenericResponseError", message: "The remote server returned an error: (403) Forbidden.", code: 9020 }`
@rkpathak can you please re-open the issue?

As a side question, how does this relate to the incoming Outlook legacy tokens deprecation? Are xxx@outlook.com accounts also in the scope?

Thanks

**Comment by tourloupis** [comment]
Hi Kelly/Julien,

Unfortunately, I am unable to check if their alleged fix has resolved the problem since I am experiencing problems connecting to the Exchange server due to a 401 Unauthorised error.  It may or may not be related to the issue that I am experiencing.

However, I have noted that there have been no updates to the NuGet package, nor the CDN for Office.js since their last release.  Therefore, unless the alleged fix involved a change to the Exchange server, and how it handles authentication, I suspect that they have not looked at it.

**Comment by thao33** [comment]
Hi, I'm now facing the issue too.

When i debug at callback function of makeEwsRequestAsync, it return 9020 error `"GenericResponseError"`

<img width="518" alt="Image" src="https://github.com/user-attachments/assets/e59a797e-5544-407f-ab32-2892ca1a1634" />

**Comment by ANovitsky** [comment]
Hello, I got the same issue, 

![Image](https://github.com/user-attachments/assets/ae8a3895-b1b2-4c89-827d-e0e76c712d9a)

**Comment by adampound** [comment]
I'm getting same error too. Any updates?
