### ISSUE TITLE
When replying or forwarding an email body.getAsync() returns an incorrect value

### ISSUE THREAD

**Issue by bchenhs** [OfficeDev/office-js#4360]
# Provide required information needed to triage your issue

Same symptoms as https://github.com/OfficeDev/office-js/issues/3988

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web, the New Outlook for Windows
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 
```
You have Microsoft Outlook Version 1.2024.403.300 (Production).
Client Version is 20240405002.12 .
```
* Operating System: MacOS 14.4.1
* Browser (if using Office on the web): Chrome
 
## Expected behavior
Appropriately get the value of the mail body.

## Current behavior
The quoted part (Original Message) of the email body is duplicated.

## Steps to reproduce
1. Open a received email and press the reply button. We see this issue on the Microsoft Viva emails.
2. Type anything in the email
3. Execute body.getAsync.

## Link to live example(s)

These are taken from https://github.com/OfficeDev/office-js/issues/3988

Javascript
```
Office.onReady().then(() => {
    Office.context.mailbox.item.body.getAsync(Office.CoercionType.Html, (result) => {
            document.getElementById("htmlBody").innerHTML = escapeHtml(result.value);
    });
    Office.context.mailbox.item.body.getAsync(Office.CoercionType.Text, (result) => {
            document.getElementById("textBody").innerHTML = escapeHtml(result.value);
    });
});

function escapeHtml(html) {
    return html
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#039;");
}
```

HTML
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
</head>
<body>
    <p>--HTML Body--</p>
    <p id="htmlBody"></p>
    <br><br>
    <p>--Text Body--</p>
    <p id="textBody"></p>
    <script src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>
    <script src="taskpane.js"></script>
</body>
</html>
```

# Provide additional details
- This appears to be part of an active rollout on the Current Channel. We can repro this on some accounts and not others.

**Comment by hsptkt** [comment]
Hey, just wanted to chime in with some more details of our impact.

We're unsure of how far along this rollout is, but this would potentially affect over 50k of our users using one of our core features once fully rolled out.

We're not able to provide a minimally reproducible example, because we are facing issues with Script Lab on Outlook web, but the cause and effects all match the linked issues #3988.

Thank you.

**Comment by bchenhs** [comment]
Hi @exextoc @ajays-msft is there any update on this issue? Do you need more debug information from me? We are getting more user reports of this issue, and it is disruptive to their ability to reply and forward emails.

**Comment by ajays-msft** [comment]
@bchenhs - I can repro this, and we are actively working on the fix. Will update you when it is available.

**Comment by bchenhs** [comment]
Thank you, @ajays-msft!

**Comment by ajays-msft** [comment]
Thiis is fixed now.

**Comment by bchenhs** [comment]
Hi @ajays-msft @exextoc Looks like this issue came back either yesterday or today. We've received multiple users reporting this and we were able to reproduce it. Did another update break/undid the previous fix?

**Comment by bchenhs** [comment]
We've opened https://github.com/OfficeDev/office-js/issues/4392 to track it.

**Comment by neprasad-microsoft** [comment]
The fix for this issue caused another issue (#4392 ) . So, we are reverting this and are working on this issue. Unfortunately, we do not have any timelines for this right now.

**Comment by hsptkt** [comment]
Hi @neprasad-microsoft, thank you for the details and update!

We just verified that this is now resolved on our side. We don't think further change is needed, especially since we've had some back and forth / regressions with the fix here.

Are you able to confirm the current behavior is now all set - if not, could we get more info if we need to expect an upcoming change?

**Comment by DivyaPatidar** [comment]
@hsptkt Yes, no changes are expected at the moment.
