### ISSUE TITLE
Outlook Online addin task pane overlaps email instead of being displayed next to it

### ISSUE THREAD

**Issue by Aidam1** [OfficeDev/office-js#4440]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Operating System: Windows 11
* Browser (if using Office on the web): Chrome 124.0.6367.201
 
## Expected behavior
Addin task pane is displayed next to the email. Same behavior as when My Day or Tips panel is shown. This was the initial behavior of task panes as well.

## Current behavior
Addin taskpane is displayed over the email. Also, the pinned task pane is not hidden when I navigate to Calendar/People/Group or any other app integrated in Outlook Online. This happens even with Viva Insights and Script Lab addins.

**Comment by mmanjaree-msft** [comment]
Thanks for reporting this issue. We have put this issue in our backlog but unfortunately, we do not have any timelines to share at this point. 
Internal tracking id ; 276374

**Comment by bchen-hs-eng** [comment]
Hi @exextoc @mmanjaree-msft This issue is affecting our add-in users. Can we please get a firm timeline on when this issue will be resolved? Thank you!

**Comment by bchen-hs-eng** [comment]
@exextoc @mmanjaree-msft This is a pretty serious regression, where the taskpane covers up many UI elements while open:
![Screenshot 2024-05-14 at 8 23 42 PM](https://github.com/OfficeDev/office-js/assets/168113738/41318f2b-e788-4070-895a-f8bb93e8b4f3)

If we can't get a fix in quickly, can we at least revert the offending change for now?

**Comment by hsptkt** [comment]
Hey @exextoc @mmanjaree-msft, we are getting an increasing number of reports on this issue from customers describing disruption to their workflow.

Is the team able to increase the priority for this based off the blast radius here?

**Comment by JustTryingtoGetHelpp** [comment]
This is affecting me too, and severely affecting my workflow. When can I anticipate a resolution?

**Comment by DmitryKostochko** [comment]
This affected both us and our users. We are receiving more and more complaints. Please fix this as soon as possible.

**Comment by jacifkusto** [comment]
We are experiencing the same issue. The task pane overlaying the email disrupts workflow significantly. We're eagerly awaiting a fix to restore seamless functionality.

**Comment by mmanjaree-msft** [comment]
Apologies for inconvenience caused. We are actively working on the fix. It is in review stage. Can't mention specific timeline but be assured this is a priority and should be fixed soon.

**Comment by hsptkt** [comment]
Hi @mmanjaree-msft, could we get an update on the fix timeline since it's been a few days?

**Comment by demkantor** [comment]
This is happening in all browsers for us as well, not in desktop clients

**Comment by JustTryingtoGetHelpp** [comment]
Any updates on this? Driving me and my coworkers insane.

**Comment by CurtisRiva** [comment]
Adding my voice to this post.  Getting a lot of complaints from customers as well.  Hoping it is resolved soon.

**Comment by anjalitp** [comment]
Thanks for your patience. This issue has been fixed and rolled out to Production.

**Comment by bchen-hs-eng** [comment]
@anjalitp @exextoc @akshayta23  This issue still occurring on the new Outlook for Windows for some of our add-in users. Is the rollout missed on this platform for some accounts? Or there are additional steps needed to pick this fix up? Thanks.

**Comment by MohamedMoussaTTW** [comment]
Can still see this issue on our end as well.

**Comment by akagarwa-msft** [comment]
The issue has been fixed, please hard refresh and clear cache your browser and see if the issue still exists. If it does, please follow the instructions here to capture logs for OWA/New Outlook wherever the issue is: 
[Collecting log files for Outlook Add-ins issues · OfficeDev/office-js Wiki (github.com)](https://github.com/OfficeDev/office-js/wiki/Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues)
