### ISSUE TITLE
Mac Excel v16.85 crashes when opening workbooks modified by our add-on

### ISSUE THREAD

**Issue by ScottMaxson** [OfficeDev/office-js#4486]
# Provide required information needed to triage your issue
Excel for Mac, version 16.85, crashes when opening workbooks which have been previously (in earlier version of Excel) modified by our add-on.
Various operations on sheets using our add-on now crash this version of Mac Excel as well.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac Desktop App
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.85
* Operating System: latest Mac OS
* Browser (if using Office on the web): N/A
 
## Expected behavior
Workbooks should open without crashing the application.
Our add-on should behave as is did on previous versions of Excel.

## Current behavior
Per above note, workbooks that we could open before now crash excel. This happens on opening the workbook, before the add-on is loaded.
Operations on sheets using our add-on now crash the application as well.

## Steps to reproduce
1. go to https://my.tillerhq.com and register. A trial account will be sufficient.
2. you will be prompted to add accounts, but you can skip this step.
3. download the excel template, and install the Tiller sidebar add-on as instructed in the help screen which appears.
4. Save the workbook.
5. upon re-opening this saved workbook, Excel will crash.

## Link to live example(s)
Not available

# Provide additional details

N/A

## Context
All users of our add-on for Mac are unable to use this tool if they have upgraded to this version of Excel. This impacts several hundred users of our tool.

## Useful logs

see the crash log attached to this report
[open-crash.txt](https://github.com/OfficeDev/office-js/files/15396356/open-crash.txt)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by keyur32** [comment]
assigning to @XuanZhouMSFT to help investigate.

**Comment by JessieChenMS** [comment]
Hi Scott, thanks for reporting the issue, we are actively looking at the issue now. At the same time, wondering is it ok for you to help check whether this repro on 16.86 version? We got that version on hand and cannot repro against that version. So could be a quick mitigation to upgrade to 16.86 if also cannot repro on your end.

**Comment by heather-TillerMoney** [comment]
I'm the product owner for Tiller - I'm not seeing the 16.86 available for my Mac. I can try updating my OS if needed but figured I'd try just Office apps first. 
<img width="606" alt="Screenshot 2024-05-22 at 10 36 08 AM" src="https://github.com/OfficeDev/office-js/assets/68031073/e9edd45b-177b-4b05-bcaf-b1c9587bb66c">

**Comment by heather-TillerMoney** [comment]
I was able to update to 16.86 using the beta channel updates. However, now when I open a workbook that has some more advanced formulas/calcs I get this error. 

<img width="443" alt="Screenshot 2024-05-22 at 12 23 12 PM" src="https://github.com/OfficeDev/office-js/assets/68031073/f137d1ff-e4b0-42be-b184-97358ef68b55">

**Comment by eschwieb** [comment]
Hi Scott and Heather,

We made a change on May 7 to no longer allow unsigned code in our process space in order improve security. This broke a different well-known 3rd party addin, so we reverted the change on May 16. That would explain why the issue went away in the next insiders release. We will be making this change again at some point in the future for Mac Office, so I would like to work with you offline to figure out why this broke your addin as well and how we can mitigate the issue. Please contact me directly at eriksc@microsoft.com -- thanks!

**Comment by JessieChenMS** [comment]
[like]  Jessie Chen reacted to your message:
________________________________

**Comment by shanshanzheng-dev** [comment]
Hi @ScottMaxson and @heather-TillerMoney, The change was in a beta (pre-release, insider) build, and the fix was in the next insider build. If you are using Insider delivery services, you need to update to the latest insider release. The production version of Mac Office never had the bug. Could you try this if it works? Thanks.

**Comment by heather-TillerMoney** [comment]
I'm still getting this error when opening a workbook that has a more complex template in it and I'm running 16.87

**Comment by ScottMaxson** [comment]
@shanshanzheng-dev Just to clarify: we're not running insider builds of Mac Office/Excel.

**Comment by shanshanzheng-dev** [comment]
Hi @heather-TillerMoney, @ScottMaxson I'd like to confirm with you, about this issue "Mac Excel v16.85 crashes when opening workbooks modified by our add-on" is working on production, right? But when you open a workbook that has some more advanced formulas/calcs, you get an alert? And heather-TillerMoney, could you provide us more detailed information, such as advanced formulas/calcs? Thanks.

**Comment by heather-TillerMoney** [comment]
This is a dummy data sheet where I get an alert after opening and before updating to 16.86 a few days ago the workbook would immediately crash. I believe it's related to the worksheet called "Debt Payoff Planner" - there is a hidden area to the right with a bunch of formulas that you can review. A contractor built this for us so I'm not familiar with all the formulas/calcs that it's using, but it seems to be a common denominator. There are likely other templates built by our [community](https://community.tillerhq.com/c/microsoft-excel/show-tell/45) that are failing similarly.  

The other action that was crashing the add-in was when we were installing templates that were simple. This seems to be fixed in 16.86 and above. I ran a test and installed all our core sheets (Transactions, Categories, Balance History, Accounts, Balances) and never received the alert. I installed Debt Payoff and it installed fine, but when I went to save the workbook (for the first time) I got the "out of resources alert" so I deleted that sheet save and closed the workbook. Then I re-opened the workbook and did not get the alert so seems pretty narrow to whatever is in that Debt Payoff template at least in our supported templates list. There are others related to budgeting I haven't installed/tested yet. But our [default Foundation template](https://storage.googleapis.com/assets.templates.tillermoney.com/Tiller-Foundation-Template.xlsx) opens without issue so I don't think there is an issue with those.

[dev-foundation-Jan24.xlsx](https://github.com/OfficeDev/office-js/files/15484460/dev-foundation-Jan24.xlsx)

**Comment by shanshanzheng-dev** [comment]
Hi @heather-TillerMoney, Thanks for so much detailed information. Yes, about this issue "Mac Excel v16.85 crashes when opening workbooks modified by our add-on #4486", just like you mentioned, we have fixed. And I think the problem you are facing the alert is different. In order to triage your issue better, could you please create another issue? we'll follow normal process to triage your issue？And then we'll close this issue. Thanks.

**Comment by heather-TillerMoney** [comment]
Thank you for the reply here. Can you let me know if 16.86 has been pushed to current channel or is it only available for beta channel still?

**Comment by heather-TillerMoney** [comment]
We have confirmed with some of our internal teammates that they're not on the beta channel and they are still not able to get 16.86. Do you know when this will be broadly available? Until then many customers that do not want to update on beta channel are completely blocked from using our product.

**Comment by shanshanzheng-dev** [comment]
Hi @heather-TillerMoney Sorry, I think there is only available for beta channel,  and I'm not sure  when 16.86 will be broadly available. But according to https://learn.microsoft.com/en-us/officeupdates/update-history-office-for-mac#release-history-for-office-for-mac (release  each month), I guess we can get 16.86 at Mid -June.
