### ISSUE TITLE
OneNote web add-in opens two iframes in taskpane when taskpane button is pressed twice

### ISSUE THREAD

**Issue by yxg10** [OfficeDev/office-js#4686]
In OneNote web, when I click on the button to open my taskpane addin twice, it opens 2 iframes in the taskpane.

However if I press the button again (doesn't matter if the taskpane is still open or closed), it will create another iframe inside the same taskpane which results in two iframes horizontally placed next to each other.

The left iframe will fail to load and show the yellow Add-in error message above. The right iframe will load normally.

I have to refresh the page for it to go back to normal.

This is not limited to my add-in. Using the built-in Feed add-in from the Home tab also leads to this behaviour (press Feed twice to see it)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: OneNote on Web
* Host [Excel, Word, PowerPoint, etc.]: OneNote
* Office version number: -
* Operating System: Windows 11
* Browser (if using Office on the web): Chrome 126.0.6478.115
 
## Expected behavior
The add-in page is refreshed. Only 1 iframe is present.

## Current behavior
2 iframes are created.

## Steps to reproduce

1. Press the Feed add-in in Home.
1. Press the button again (doesn't matter if the taskpane is still open or closed), it will create another iframe inside the same taskpane which results in two iframes horizontally placed next to each other.
1. The left iframe will fail to load and show the yellow Add-in error message above. The right iframe will load normally.
1. Refresh the page for it to go back to normal.

**Comment by AlexJerabek** [comment]
Thanks for reporting this @yxg10.

@EsterBergen, could you please investigate?

**Comment by EsterBergen** [comment]
@yxg10 - Thanks for reporting this. I don't see Feed double stacking, but I do see multiple Add-ins opening side by side in the browser (See below). I will check to see what the expected behavior is for taskpanes in One Note Web. 
![image](https://github.com/user-attachments/assets/fc2aa85c-4033-4832-8520-475b83b55c79)

Can you report a problem in One Note Online? Include a screenshot in the bug.
![image](https://github.com/user-attachments/assets/d4394ad4-575c-4748-a3b3-3d1775400a38)

**Comment by yxg10** [comment]
Thanks for looking into this @EsterBergen. I may not have been clear on the issue when I initially reported it. The issue is not that multiple taskpanes of different addins open side by side. I believe that is fine and expected.

The issue is that (apparently only starting this week), pressing the same add-in twice causes 2 iframes to be loaded within the same taskpane of the addin. The issue is visible in your screenshot as you can see the horizontal scrollbar at the bottom of the add-ins' taskpanes. If you scroll them to the right you will see another copy of the same addin.

Inspecting the url of the iframes show that they both have the same url.

Normally pressing the addin button twice used to just refresh the addin.

This is a screenshot of what it looks like when you scroll to the right on the Feed addin.

![image](https://github.com/user-attachments/assets/3d3c7c76-2716-4c7f-9002-c3b9149cc0c2)

I will report this separately to OneNote online as well.

**Comment by EsterBergen** [comment]
@yxg10 - Tried again today and it looks like the issue is resolved. 
<img width="767" alt="image" src="https://github.com/user-attachments/assets/ad20e16a-2626-4245-a3dd-f5fa12d1c28b">
Do you see something similar on your end?

**Comment by yxg10** [comment]
The same issue is still occurring for me, nothing appears to have changed unfortunately.

**Comment by EsterBergen** [comment]
@yxg10 - I see this when i open up the same add-in twice. This is a bug (9216582). We will track it and post updates here once available. Thank you for reporting this issue!

**Comment by EsterBergen** [comment]
@yxg10 - It seems like this issue is resolved. Can you please try and let us know if you still experience the issue?

**Comment by aborzanovic** [comment]
Hello!

I've been experiencing this issue. Purchased Office 365 a few days ago in order to make an add-in for OneNote and this bug's been a complete blocker.

The first time you open a task pane you only get one iframe loaded. But if you close it and reopen it will spawn 2 iframes (only one is visible, the other is off-screen). And my issue appears to be that in the visible iframe "await context.sync()" never resolves but it does in the one off-screen. Thus I've lost all ability to interact with the task pane since everything I do triggers in the off-screen pane.

**Comment by EsterBergen** [comment]
@aborzanovic - can you share more details about what version of OneNote you're using? Go to home, account, and share what it says under "about oneNote". Thanks!

**Comment by yxg10** [comment]
On my end I no longer get the bug. When trying to replicate with the Feed functionality that used to have this issue, pressing it twice causes the sidebar to hide instead of spawning another iframe.

**Comment by aborzanovic** [comment]
@EsterBergen I'm using OneNote for the web, I can't find "about one note" there. I have used [this tutorial](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/yeoman-generator-overview#use-the-tool) to generate an add-in (selecting Office Add-in Task Pane project, JavaScript, Onenote). This left me with an example add-in which showcases the bug well (at least in the web version).

I've attached a recording showing that when you click the button - the current pane is just refreshed, does not close.

I've also attached a screenshot of 2 adjacent iframes (the first time you open the pane there's only one).

https://github.com/user-attachments/assets/d92f5423-8e73-49f3-85a5-1032ed3fd918

<img width="1175" alt="Image" src="https://github.com/user-attachments/assets/12675490-95e2-4697-bafe-119548633963" />

**Comment by EsterBergen** [comment]
@aborzanovic Thanks for this! If you want to close the task pane, you'll need to click on the x on the upper right of the add-in. Clicking on the ribbon button for the add-in won't close the task pane. 

Is the issue you're experiencing for closing the task pane? or for two task panes being opened side by side (original issue in this thread)?

To see the version number on web, go to "File"> "About" and Build is listed at the bottom of that page.

<img width="432" alt="Image" src="https://github.com/user-attachments/assets/ac5044ab-98f4-41e0-87b4-4826e36762b8" />

**Comment by aborzanovic** [comment]
@EsterBergen Thanks, here's the info:
Session Id: 2ec805cc-78ea-4d40-9965-521c54a4b299[c][w]
Build: 16.0.18611.41002

> If you want to close the task pane, you'll need to click on the x on the upper right of the add-in. Clicking on the ribbon button for the add-in won't close the task pane.

Right, I just wanted to address this:

> When trying to replicate with the Feed functionality that used to have this issue, pressing it twice causes the sidebar to hide instead of spawning another iframe.

That works for the Feed but not for add-in panes. For add-in panes it introduces a new iframe.

> Is the issue you're experiencing for closing the task pane? or for two task panes being opened side by side (original issue in this thread)?

The issue is two task panes being open but they're not side by side - one iframe takes up the whole pane pushing the other one off-screen. Again, this would be fine if both panes _worked_. Only the one off-screen works, i.e. in the visible iframe stuff like `await context.sync();` (which is essential for any plugin) will wait forever, the promise is never resolved.

I assume the top frame coordinates things and only allows one instance of the add-in or something.

**Comment by EsterBergen** [comment]
@aborzanovic This is interesting. I'm not able to reproduce the issue you're mentioning. When I try to open an Office Addin, I only see one taskpane. If i open more than one addin, the task pane shows up next to the other addin that was opened. I don't see multiple panes on top of each other.

Can you "Report a problem"? and this will provide a bug with logs. Go to Help> Give Feedback to Microsoft> Report a Problem.

![Image](https://github.com/user-attachments/assets/a428e4d4-c77e-48fa-bf36-3c54e7e0b9c3)

**Comment by aborzanovic** [comment]
@EsterBergen Thanks, I've submitted the feedback.

> I don't see multiple panes on top of each other.

Just to clarify, I don't _see_ multiple panes either. One is visible and it's pushing the other one off-screen. And that makes a whole lot of issues. Easiest way to experience an issue is to follow [this tutorial](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/yeoman-generator-overview#use-the-tool) to generate an add-in (selecting Office Add-in Task Pane project, JavaScript, Onenote). When you open the task pane the Run button works. Once you reopen it - it stops working.

I just wanted to add that I've tested it in Chrome 133, Safari 12.7.1 and Firefox 135 on a Mac - same issue everywhere. I've tried to make a production build and serve it from a remote server using valid TLS certs - still have the same bug. Interestingly enough this doesn't seem to happen with extensions installed from the store.

**Comment by aborzanovic** [comment]
> Interestingly enough this doesn't seem to happen with extensions installed from the store.

Scratch that. Some do, like "SiteMap", "File from Egnyte Connect" and "Image Chooser".

**Comment by Acibi** [comment]
As mentionned in #5470 : We've determined that is there is a TaskPaneID in the action from the manifest, it will happen. If you remove the TaskPaneID, OneNote behave correctly.

It's not a solution for us, because we want to open different URL, in the same TaskPane.

**Comment by aborzanovic** [comment]
@Acibi thanks you're a lifesaver. I only have 1 action so i was able to solve my issue this way.
