### ISSUE TITLE
Numbering Styles do not work on WOPI host (CSPP)

### ISSUE THREAD

**Issue by aeturneus** [OfficeDev/office-js#4698]
We have created Word templates containing numbering styles that work fine in desktop and O365, but fail in the WOPI word editor provided by CSPP (the Microsoft Cloud Storage Partner Program)

In our environment, opening a template containing auto-numbering styles results in the document being rendered without any numbers displayed, as shown in the example screenshot:

![image](https://github.com/user-attachments/assets/68771eea-870b-4b79-9507-87f513945681)

As soon as any change is made to the document, the document re-renders with numbering displayed, however there are added characters in the numbering for certain headings (`%` character is added), as shown in the example screenshot:

![image](https://github.com/user-attachments/assets/ea0fa885-d3cf-4cc0-91e0-75182d55867f)

## Your Environment

- Platform [PC desktop, Mac, iOS, Office on the web]: WOPI editor provided by CSPP
- Host [Excel, Word, PowerPoint, etc.]: Word
- Office version number: Build 20240627.8
- Operating System: Any
- Browser (if using Office on the web): Chrome
 
## Expected behavior
The document should open with numbering styles correclty rendered.

## Current behavior
Numbering styles do not render in the document.

## Steps to reproduce

1. Open a document with numbering styles in our WOPI editor (credentials available on request)

## Link to live example(s)
1. alternatively, use our production application test account (I will provide credentials if requested)

## Context
This bug prevents our production application from being used in WOPI, limiting our ability to deploy this tool to thousands of lawyers across Canada and the United States - it's a critical use case for us.

**Comment by aeturneus** [comment]
@xiruatms may be related to https://github.com/OfficeDev/office-js/issues/4640

**Comment by aeturneus** [comment]
Possibly related to this issue https://github.com/OfficeDev/office-js/issues/4684

**Comment by xiruatms** [comment]
@aeturneus , thanks for reporting this. 

Please help to clarify following questions for me:
1. when a template  file with auto-numbering style (which style please?) is opened in WOPI, there's no number displayed. There's nothing related directly to JS codes, correct?
2. What do you mean by "any changes is made to the document"? Simply typing on editor can trigger this, correct?
3. Do you have any testing template file for us the verify this please?

**Comment by aeturneus** [comment]
@xiruatms thanks for taking a look

1. Correct, the issue appears upon opening the document and does not require any JS activity to reproduce
2. Correct, typing in the editor can trigger re-rendering and cause numbering styles to appear
3. Template file attached - numbers render correctly in Word Online but not in WOPI environment 
[numbering-style-issue-example.docx](https://github.com/user-attachments/files/16350135/numbering-style-issue-example.docx)
<img width="1361" alt="Screenshot 2024-07-23 at 11 12 59 AM" src="https://github.com/user-attachments/assets/31676d99-d4e2-429e-bd12-f210f531ec7d">

**Comment by C-monC** [comment]
I can confirm I get the same behavior. 
No Numbering initially. I then type a single key. The page spasms and inserts
![image](https://github.com/user-attachments/assets/06108743-5825-46b6-89a3-17944d94434a)
the characters %1.%2.%3.... over every tab char/new line?? under the numbered heading.

**Comment by aeturneus** [comment]
@xiruatms gentle bump - this is affecting our production application and making most of our forms unusable currently, any path to resolution would be greatly appreciated

**Comment by xiruatms** [comment]
@aeturneus , thanks for your patience. Our experts are working on this. To make sure we're on the same page, will you please share the credentials to access your WOPI? Please submit the information using:https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR9NvrlmrippKsMvh4kTM325URVZMWjYyQTVOTVNLTUo5VzFRTTcyNU1RSy4u

Thanks.

**Comment by aeturneus** [comment]
@xiruatms let us know if there is anything further required to investigate this issue - continues to be a high priority problem for us and many other organizations using WOPI

**Comment by mcg-kahootz** [comment]
I can confirm seeing similar behaviour when opening documents using numbering styles. Sometimes the document will load with no numbering at all and in other instances the numbering starts at 11 instead of 1. Setting a new numbering value (creating a new list from 1) in Word on the desktop does not alter how the numbering is represented in WOPI.

Any updates on a fix?

**Comment by aeturneus** [comment]
Have to be the squeaky wheel as this is such a major blocking issue for our team - really hoping for a fix soon

**Comment by xiruatms** [comment]
Thank you for your patience. We've made great progress on this. Codes to fix are being carefully prepared and under review.

**Comment by C-monC** [comment]
I think this has been fixed.

**Comment by aeturneus** [comment]
@xiruatms @C-monC it's not completely fixed - when content is inserted into the document it appears to be added at the wrong list level (all top level numbering, instead of further list levels as originally styled)

however at least the numbering appears!
![image](https://github.com/user-attachments/assets/1ec8decf-5726-4332-bcee-9c48218a3c79)

**Comment by C-monC** [comment]
Glad you caught that. The issue remains... My list gets flattened into bullets on a reopen.
![image](https://github.com/user-attachments/assets/d4dd4739-4935-430f-9d8e-400daed8cedd)

![image](https://github.com/user-attachments/assets/9a3df038-00a6-4e47-84fd-255ff1eebf98)

**Comment by aeturneus** [comment]
@xiruatms any update on this one? Still critical for us.

**Comment by shanshanzheng-dev** [comment]
Hi @aeturneus Sorry for slow response, we have recently checked in a fix, and it'll take sometime to be available in PROD. Thanks

**Comment by aeturneus** [comment]
@shanshanzheng-dev that is great to hear. Thank you for the update!

**Comment by aeturneus** [comment]
@shanshanzheng-dev any idea when this will be available in PROD?

**Comment by shanshanzheng-dev** [comment]
Hi @aeturneus seem it deploys to PROD now. You can try it if still happened. Thanks.

**Comment by aeturneus** [comment]
@shanshanzheng-dev still seeing the same bug behaviour

**Comment by shanshanzheng-dev** [comment]
could you try to update a new build version?

**Comment by aeturneus** [comment]
@shanshanzheng-dev this is word online build 20240919.2

**Comment by shanshanzheng-dev** [comment]
Hi @aeturneus I'm confirming this issue with experts. Will update later.

**Comment by aeturneus** [comment]
@shanshanzheng-dev were you able to reproduce the issue or do you need any further information from me?

**Comment by aeturneus** [comment]
@qinliuMSFT let us know if you need any more info - eagerly awaiting a resolution for last few months!

**Comment by aeturneus** [comment]
@qinliuMSFT it seems the issue is the paragraph listlevel is not being set even though the list style is correctly set

**Comment by qinliuMSFT** [comment]
Hi @aeturneus, I'm testing on version 20241015.5 and I'm experiencing the following behavior, can you help confirm if you're requesting a correction for this behavior? 

When I edit the numbering style in a document in the WOPI environment, everything goes well and I get something like this:
![image](https://github.com/user-attachments/assets/d5782e02-f398-45bd-998d-38c565ba16d4)

Then I close the document and re-open, I found the numbering style mixed up, as shown below
![image](https://github.com/user-attachments/assets/afc587dd-15f5-4726-8445-a89ea6f15c25)

**Comment by aeturneus** [comment]
> Hi @aeturneus, I'm testing on version 20241015.5 and I'm experiencing the following behavior, can you help confirm if you're requesting a correction for this behavior?
> 

This seems closely related to our issue. We can reproduce the same flattened list behaviour by using office-js to show hidden content, or hiding content then showing it, using our Word add-in. The hidden content is always flattened even if it was originally nested with multiple list levels. It seems that you are able to reproduce the same problem by closing and opening the document without office-js.

**Comment by aeturneus** [comment]
@qinliuMSFT does that answer your question?

**Comment by qinliuMSFT** [comment]
Hi @aeturneus , thanks for your supplement! It has been put on our backlog #9185124, the team will investigate and we will reply to you as soon as there is any progress. Thank you for your patience.

**Comment by aeturneus** [comment]
@qinliuMSFT it would be very helpful to know if we can expect a fix in weeks, or months, or indefinitely to determine whether to invest resources into a costly workaround.

**Comment by qinliuMSFT** [comment]
Hi @aeturneus , at this time, we do not have a specific timeline to share. Based on the information provided, the issue does not seem to be directly related to Office-JS code, as it can be reproduced without any JavaScript activity. We are collaborating with the Word Web team to further investigate and resolve the issue. However, this process may take some time as it is outside our direct control. We appreciate your understanding and continued patience.

**Comment by aeturneus** [comment]
@qinliuMSFT understood, please let us know if there is anything we can do to assist or expedite resolution.

**Comment by aeturneus** [comment]
@qinliuMSFT we are really hoping to see a resolution to this by end of year - is there anything that can be done to assist/expedite resolution?

**Comment by aeturneus** [comment]
@qinliuMSFT is this still something that will be addressed by the Word Web team?

**Comment by qinliuMSFT** [comment]
@aeturneus, sorry for the late response. The issue is still active and the Word Web team is following up.

**Comment by jaiswalshubh1** [comment]
Hi @aeturneus ,

As per the internal ticket: 9185124, issue has been fixed and its working fine, can you please verify from your side ?

cc: @kustonaut 

Thanks!
Shubham Jaiswal

**Comment by jaiswalshubh1** [comment]
Hi @aeturneus ,

We are waiting for your response as issue has already fixed, I am closing this issue, please feel free to open fresh bug if you get same issue.

cc: @kustonaut 

Thanks!
Shubham Jaiswal
