### ISSUE TITLE
[Excel] RichApi.Error: ControlIdNotFound

### ISSUE THREAD

**Issue by hdwatts** [OfficeDev/office-js#4807]
# Provide required information needed to triage your issue

A subset of our clients are reporting that clicking a button in the ribbon of our Excel add-in appears to not do anything. The command itself is simple, if the user is authenticated (which we have confirmed they are in these cases) then enable the other controls in the ribbon. 

We are accomplishing this by calling the below requestUpdate function for each of the other controls:

```tsx
// The groupId, controlId, and enabled are passed in as variables
// as we go through the hard coded controls

await Office?.ribbon?.requestUpdate({
	tabs: [
		{
			id: 'Chrono.xConnectTab',
			groups: [
				{
					id: groupId,
					controls: [
						{
							id: controlId,
							enabled,
						},
					],
				},
			],
		},
	],
})
```

The group and control ids are hardcoded to match 1:1 with the IDs in our manifest file. This code works for the majority of our users and for us. However, a subset of our users frequently encounter an error with OfficeJS that hits our Sentry logs:

```
RichApi.Error: ControlIdNotFound
  at new n(/lib/1.1/hosted/excel-win32-16.01.js:25:265603)
  at i.processRequestExecutorResponseMessage(/lib/1.1/hosted/excel-win32-16.01.js:25:330050)
  at ? (/lib/1.1/hosted/excel-win32-16.01.js:25:328113)
```

Given that the Ribbon is visible and these control ids are hard coded, how can they not be found?

When we were debugging with the client, we found opening the taskpane and triggering a right click -> reload would fix the problem and the button functions as expected.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Office 365 Enterprise (Version 2407 Build 17830.20138)
* Operating System: Windows 11 Enterprise (10.0.22631 Build 22631)
 
## Expected behavior
- Our command is able to enable or disable controls as expected

## Current behavior
- Some users receive the ControlIdNotFound error and nothing happens.

## Context

- Clients are upset that they cannot login to our add-in

## Useful logs

```
RichApi.Error: ControlIdNotFound
  at new n(/lib/1.1/hosted/excel-win32-16.01.js:25:265603)
  at i.processRequestExecutorResponseMessage(/lib/1.1/hosted/excel-win32-16.01.js:25:330050)
  at ? (/lib/1.1/hosted/excel-win32-16.01.js:25:328113)
```

**Comment by shanshanzheng-dev** [comment]
Hi @hdwatts Thanks for reporting this issue. Could you share us which add-in is hitting this error or your manifest? We'll investigate this root cause. Thanks.

**Comment by hdwatts** [comment]
Hi @shanshanzheng-dev - the addin can be found on the [AppSource here](https://appsource.microsoft.com/en-us/product/office/WA200006423?tab=Overview).

The manifest can be found here: https://excel.chronograph.pe/xconnectjs-manifest.xml

Thank you for looking into this. I have a call with a client about this tomorrow so would appreciate any insight you may have.

**Comment by hdwatts** [comment]
Hi @shanshanzheng-dev and @m-hellesen

Our client has set up a weekly call with us to discuss our progress on this issue. Do you have any insight into this problem we can share with them?

**Comment by shanshanzheng-dev** [comment]
Hi @hdwatts It has been put on our backlog <bug #9278887>. we're triaging this issue. We'll report back if we have a suggestion for you. Thanks for your patience.

**Comment by hdwatts** [comment]
Thanks @shanshanzheng-dev - is there a link to the backlog I can share with the client?

**Comment by shanshanzheng-dev** [comment]
Hi @hdwatts, Sorry, the link is our internal backlog link and you have no access to open. But we'll report back if we have a update for you. We unfortunately have no timelines to share at this point.

**Comment by hdwatts** [comment]
@shanshanzheng-dev @m-hellesen Just checking in, anything I can communicate to our clients who are still experiencing this issue?

**Comment by RuizhiSunMS** [comment]
@hdwatts , sorry but here is no new update. Our colleagues are still working on it.

**Comment by hdwatts** [comment]
Hi @RuizhiSunMS - checking in on an update here for this issue as it has been a few months now and a client is still experiencing it.

**Comment by 4tti** [comment]
@RuizhiSunMS, @Wenjun-Gong Any update? We are facing similar issues at the customer site.

@hdwatts is that addin deployed through MS365 admin center (centralized deployment)?

**Comment by Isaac96SM** [comment]
Some of our users are having this issue too, Any update?

**Comment by 4tti** [comment]
**This is extremely critical, it started to appear more often**! Please take this seriously as it renders our product totally immature compared to COM/VSTO variants.

@Wenjun-Gong FYI

PS: it is somehow related to cache I suspect because sometimes we also see error with registration of custom functions and in that case this is 100% reproducible in some environments.

**Comment by Wenjun-Gong** [comment]
> **This is extremely critical, it started to appear more often**! Please take this seriously as it renders our product totally immature compared to COM/VSTO variants.
> 
> [@Wenjun-Gong](https://github.com/Wenjun-Gong) FYI
> 
> PS: it is somehow related to cache I suspect because sometimes we also see error with registration of custom functions and in that case this is 100% reproducible in some environments.

We have reached out to the SME to take a look at this issue. We will share back once there is any update.

**Comment by 4tti** [comment]
Just to add, in our case we get these:
![Image](https://github.com/user-attachments/assets/3082ff03-e865-442d-bfe3-fe1395cd5958)
![Image](https://github.com/user-attachments/assets/27ad6d7b-165c-424d-b41c-782ffc865d83)

**Comment by Wenjun-Gong** [comment]
@4tti , do you have any repro steps for this issue? We are currently not able to repro on our end.

**Comment by 4tti** [comment]
hello @Wenjun-Gong , thanks!

We are trying to find repro with ScriptLab if ever.

1. In our case it is just fine to use shared folder deployment (Sideloading). We have shared runtime add-in with custom functions, ribbon, commands, etc.
2. create some file with the addin attached, save it locally
3. close excel
4. open excel, mark the cleaning cache with next startup, close excel
5. open that file from explorer
6. repeat steps 3-6 till addin installation error (custom functions fail to register).
7. Then this issue happens

Note that on customer end  - they are encountering it with Centralized Deployment and usually it is related to the file iself - when inspect document is used to remove add-in and it is reinserted later on, it will work (and not easily reproducible).

**Comment by jakuboppelt** [comment]
Hi, 
we have created repository with minimum code to reproduce this issue. There is a CustomTab in manifest, custom function and showingTaskPane after office is ready...


repo: https://github.com/jakuboppelt/RibbonIssue
video: https://github.com/jakuboppelt/RibbonIssue/blob/main/recording.mp4

**Comment by 4tti** [comment]
@Wenjun-Gong  please see above. Give it high priority please, because shared folder deployment is the only way how to fulfill certain scenarios whicha re not possible with centralized deployment or app-source.

Also note, that actually SAME OR VERY SIMILAR issue is happening with centralized deployment but is very hard to provide steps. We were able to reproduce only on customer site (as mentioned above).

**Comment by 4tti** [comment]
Any update please? @Wenjun-Gong , @RuizhiSunMS

**Comment by Wenjun-Gong** [comment]
> Any update please? [@Wenjun-Gong](https://github.com/Wenjun-Gong) , [@RuizhiSunMS](https://github.com/RuizhiSunMS)

We have been waiting feedback from the area owner team. We will share back once there is any update. 

+ @EsterBergen

**Comment by EsterBergen** [comment]
Hi @4tti - Thanks for your patience. We are still looking into the issue and will reach out here when we can provide more details on next steps.

**Comment by trigurl** [comment]
Hi I'm Angela.  I'm going to attempt to repro this today.   I might have some questions along the way. 

I see that [jakuboppelt](https://github.com/jakuboppelt) uploaded a repro with all the files, so I will try that first.   I can't seem to view the video however as I can a message saying it's too large?  

There's a comment saying that [jakuboppelt](https://github.com/jakuboppelt) repro is easiest to repro with fileshare?

Thanks Angela

**Comment by 4tti** [comment]
@trigurl you can download the video from that repository.

And yes, use shared folder, please.
Thanks a lot!

**Comment by trigurl** [comment]
I can't seem to get the custom function to work (time 10 seconds in the video).  Here's what I did:
1) I grabbed all the files under https://github.com/jakuboppelt/RibbonIssue/tree/main/dist and copied it over to my local IIS server along with taskpane.css, customfunctions.ts and commands.ts
2) Updated the manifest.xml to point to my server, tested a few files to make sure I can make an HTTP request to them in the browser.
3) Setup file share catalog
4) Restart Excel and select the add-in, I see 2 buttons in the Ribbon, I can launch the taskpane. 
5) I proceed to type =XADD(1,2) into a cell and I get an error.  So I'm having issues using the sample.

**Comment by trigurl** [comment]
![Image](https://github.com/user-attachments/assets/b63221a2-aa56-4337-9f71-77c95c07e6c3)

**Comment by jakuboppelt** [comment]
Hi @trigurl 
my repository is create using yeoman https://learn.microsoft.com/en-us/office/dev/add-ins/develop/yeoman-generator-overview
so just clone it
then:

1. npm ci
2. npm run build-dev
3. npm run start

step 3. will start webpack dev server and launch excel with manifest from my project
Hope it helped

**Comment by trigurl** [comment]
Hi are you folks all using Yeoman Generator?  Is there anyone that has a really bare bones repro where there is 1 manifest file, html/js sources plus icon files?  I will just copy all the files to my local server.

**Comment by 4tti** [comment]
@trigurl not sure I understand. For our production add-in we don't use yeoman of course but this seemed the easiest way how to provide you small and simple add-in where we were able to reproduce the issue.
Why is that issue for you?

**Comment by trigurl** [comment]
Hi, in the interest of figuring out ways to get through our backlog of customer issues, we are asking folks to provide with bare bones repro steps that we can repro within a couple of minutes.  Right now, want to reduce the time we take to reproduce the issue.

I have a basic test add-in here, where we have a custom tab with some buttons. 
1) After installing the add-in, I launch Excel, then I verify that the custom tab and button controls are visible and enabled.
2) Then I call requestUpdate to set enabled: false

Results:  My selected control is then greyed out (disabled) 

In our test add-in, here is a snippet that does the call:

function SetButtonEnabled(commandTabID, commandButtonID, fEnabled) {

     console.log('Updating tabId' + JSON.stringify(commandTabID) + ' Button id: ' + JSON.stringify(commandButtonID) + ' to ' + JSON.stringify(fEnabled));

     try {
          OfficeRuntime.ui.getRibbon().then(function (ret) {
               try {
                    var dr = ret;
                    var btn = { id: commandButtonID, enabled: fEnabled };
                    var tab = { id: commandTabID, visible: true, controls: [btn] };
                    var data = { tabs: [tab] };
                    dr.requestUpdate(data);
               } catch (error) {
                    console.log("Error: " + error);
               }
          }).catch(function (error) {
               console.log("Error: " + error);
          });
     } catch (error) {
          console.log("Error: " + error);
     }
}

**Comment by 4tti** [comment]
Hello @trigurl,

can you please clarify what do you ask? To me it is not clear at all. You can reproduce it in couple of minutes just by using yeoman, right? We even provided video to make sure no step is missed.

**Comment by 4tti** [comment]
Any update?

**Comment by 4tti** [comment]
@trigurl, @Wenjun-Gong  is something needed from our end?

**Comment by 4tti** [comment]
Based on our internal testing it seems it was fixed. Can anyone confirm that there was some code change related to this issue published by MS, please? @trigurl, @Wenjun-Gong, @RuizhiSunMS  
Or is it just coincidence (or maybe something has change that is preventing us from reproducing the bug)?

**Comment by Wenjun-Gong** [comment]
Hi @4tti , AFAIK, there wasn't any code change checked in related to this issue. Whenever you see this problem again, or get a repro, feel free to update here then we will take further look.

**Comment by Wenjun-Gong** [comment]
Close this issue as it no longer re-pro. Please re-open if anybody still see the issue.

**Comment by hdwatts** [comment]
@Wenjun-Gong We are still getting these errors quite often from clients, I would not mark this as closed. I do not have permission to reopen but can you please do so?

<img width="547" height="454" alt="Image" src="https://github.com/user-attachments/assets/d57dc97a-d338-4698-a993-04effddb1339" />

**Comment by RuizhiSunMS** [comment]
@jakuboppelt sorry to hear that you are still blocked by this case. I will reopen it and take a look at your sharing next monday.
Btw, please provide a repro guideline for your problem.

**Comment by RuizhiSunMS** [comment]
@hdwatts sorry to hear that you are still blocked by it. But we suggest you open your own case here for your problem because we can better communicate if you are the owner. You can attach this case in your own one.

**Comment by hdwatts** [comment]
@RuizhiSunMS - please see the original post of this case and note the owner. This is my case.

**Comment by RuizhiSunMS** [comment]
@hdwatts sorry for the mistake. May I ask that we can repro it as the current repro guideline?
