### ISSUE TITLE
In outlook OWA and new outlook, moving or deleting an email message item, broke the child dialog window interaction with its parent

### ISSUE THREAD

**Issue by David-Buyer** [OfficeDev/office-js#4870]
As title, after moving an email message where the component is activated within, the next time i try use i attempt to activate the component on a new item message, and use Office.context.ui.messageParent() from a dialog on a new message ( activating the add-in from a click button ), it does not send the message to parent anymore. It seems remains hanged to the previous item message context and it does not capture the new one. This does not happen if i do not use the dialog as **displayInIframe: false** neither i do not remove/move the message. I'm struggling to find a solution or a workaround, but with no luck. It would appreciate if someone have a solution. To reproduce the issue is enough to follow the scenario to move an item message after click a dialog popup button, and try again with another item message to do same; the subsequent attempts to Office.context.ui.messageParent() will be broken.  The issue is automatically fixed by itself when timeout occurs ( after 5 minutes as default ), because the completed() method on the event raised does not remove the iframe ( baseframe ) injected by the component activation ( probably because item message context is lost ).

**P.S: this happens on OWA and new Outlook only.**

_Originally posted by @David-Buyer in https://github.com/OfficeDev/office-js/issues/3050#issuecomment-2334763025_

**Comment by Swathy-Mothilal** [comment]
Hi @David-Buyer, we’re unable to replicate this issue on our end. Could you please share the add-in's manifest where you’re encountering the problem, along with a video demonstrating the issue? This will help us reproduce it and debug more effectively. Thank you!

**Comment by David-Buyer** [comment]
> Hi @David-Buyer, we’re unable to replicate this issue on our end. Could you please share the add-in's manifest where you’re encountering the problem, along with a video demonstrating the issue? This will help us reproduce it and debug more effectively. Thank you!

Ok. Here is a video where the issue happens. As you can see it seems that first time all runs fine, while the next time the dialog pop up does not send the message back to parent, probably because there's a mess in target item context. If i do a refresh, obviously it comes back to work fine again. This happens just if i move the item and after moving it, i finalize the operation calling .completed() method. In the dev console you can see although i call completed() the context ( "baseframe" ), remains hanged there without closing. Further, the interesting thing it happens ONLY ON New Outlook and OWA, with Exchange Online, while in Outlook desktop 365 and Exchange on-premises in my organization ( requirements set 1.5 ), it doesn't happen all works fine as expected ( the "baseframe" context is closed after moving message and call completed() to finalize the flow ). The code is identical in several contexts i tested it and it uses the best practice to parent-child dialog window communication, using APIs  Office.context.ui.messageParent() and messageChild() in bidirectional way. I tried even using localstorage approach to exchange messages with polling using setInterval() but the problem seems to be in the child->parent direction using Office.context.ui.messageParent(), and just after moving the message the first time; subsequent attempts to run the flow, the Office.context.ui.messageParent() does not be able to propagate message to parent so the control is not returned ( the message error you see in the dialog pop up is a custom message i inserted with a timeout, to notify the refresh attempt in case of communication errors ). Another thing is that closed event continue to be received by the parent so the **DialogEventReceived** type event handler seems no to be affected, only the **DialogMessageReceived** type it is.

I hope this helps.

Here is the manifest that is pretty simple; after there's a video.

```
<?xml version="1.0" encoding="UTF-8"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0"
           xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides/1.0"
           xsi:type="MailApp">
  <Id>49b50ba7-82ed-4a2a-aa24-cb1b95c31003</Id>
  <Version>1.0.0.0</Version>
  <ProviderName>Test</ProviderName>
  <DefaultLocale>it-IT</DefaultLocale>
  <DisplayName DefaultValue="PhishAlarm Test">
    <Override Locale="en" Value="PhishAlarm Test"/>
    <Override Locale="it-it" Value="PhishAlarm Test"/>
  </DisplayName>
  <Description DefaultValue="Segnala un messaggio email sospetto d'attività di Phishing."/>
  <IconUrl DefaultValue="https://localhost:8015/Images/Icon64.png"/>
  <HighResolutionIconUrl DefaultValue="https://localhost:8015/Images/Icon64.png" />
  <SupportUrl DefaultValue="https://www.testing.it" />
  <AppDomains>
    <AppDomain>https://localhost:8015</AppDomain>
  </AppDomains>
  <Hosts>
    <Host Name="Mailbox" />
  </Hosts>
  <Requirements>
    <Sets>
      <Set Name="Mailbox" MinVersion="1.1" />
    </Sets>
  </Requirements>
  <!-- <FormSettings> non viene utilizzato ma è obbligatorio per la validazione del manifest per il supporto di clients legacy che non supportano gli add-ins commands  -->
  <FormSettings>
    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://localhost:8015/dummy.html"/>
        <RequestedHeight>250</RequestedHeight>
      </DesktopSettings>
    </Form>
  </FormSettings>
  <Permissions>ReadWriteMailbox</Permissions>
  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read" />  
  </Rule>
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
      <Requirements>
        <bt:Sets DefaultMinVersion="1.4">
          <bt:Set Name="Mailbox" />
        </bt:Sets>
      </Requirements>
      <Hosts>
        <Host xsi:type="MailHost">
          <DesktopFormFactor>
            <SupportsSharedFolders>true</SupportsSharedFolders>
            <FunctionFile resid="webFunctionFile" />
            <!-- Barra di lettura del messaggio -->
            <ExtensionPoint xsi:type="MessageReadCommandSurface">
              <OfficeTab id="TabDefault">
                <Group id="msgReadGroupPhisingAlert">
                  <Label resid="groupLabel" />
                  <Control xsi:type="Button" id="msgReadFunctionButton">
                    <Label resid="buttonLabel" />
                    <Supertip>
                      <Title resid="titleLabel" />
                      <Description resid="descriptionText" />
                    </Supertip>
                    <Icon>
                      <bt:Image size="16" resid="icon16" />
                      <bt:Image size="32" resid="icon32" />
                      <bt:Image size="48" resid="icon48" />
                      <bt:Image size="64" resid="icon64" />
                      <bt:Image size="80" resid="icon80" />
                    </Icon>
                    <Action xsi:type="ExecuteFunction">
                      <FunctionName>forwardPhishingEmail</FunctionName>
                    </Action>
                  </Control>
                </Group>
              </OfficeTab>
            </ExtensionPoint>
          </DesktopFormFactor>
        </Host>
      </Hosts>

      <Resources>
        <bt:Images>
          <bt:Image id="icon16" DefaultValue="https://localhost:8015/Images/icon16.png"/>
          <bt:Image id="icon32" DefaultValue="https://localhost:8015/Images/icon32.png"/>
          <bt:Image id="icon48" DefaultValue="https://localhost:8015/Images/icon48.png"/>
          <bt:Image id="icon64" DefaultValue="https://localhost:8015/Images/icon64.png"/>
          <bt:Image id="icon80" DefaultValue="https://localhost:8015/Images/icon80.png"/>
        </bt:Images>
        <bt:Urls>
          <bt:Url id="webFunctionFile" DefaultValue="https://localhost:8015/index.html"/>
          <bt:Url id="jsFunctionFile" DefaultValue="https://localhost:8015/index.js"/>
        </bt:Urls>
        <bt:ShortStrings>
          <bt:String id="groupLabel" DefaultValue="Phishing Alert"/>
          <bt:String id="buttonLabel" DefaultValue="Segnala tentativo di Phishing"/>
          <bt:String id="titleLabel" DefaultValue="Segnala tentativo di Phishing"/>
        </bt:ShortStrings>
        <bt:LongStrings>
          <bt:String id="descriptionText" DefaultValue="Segnala questo messaggio come sospetto."/>
        </bt:LongStrings>
      </Resources>
    </VersionOverrides>
  </VersionOverrides>
</OfficeApp>
```



https://github.com/user-attachments/assets/ee466ce0-d769-4ea3-b965-d27d0cf438a2

**Comment by Swathy-Mothilal** [comment]
@David-Buyer , thank you for the thorough explanation. The manifest you provided is hosted locally, and we’re unable to replicate the issue. 

Could you please host add-in, upload it in a private repository and share it with @exextoc ? This will help us investigate and identify the root cause.

**Comment by David-Buyer** [comment]
> @David-Buyer , thank you for the thorough explanation. The manifest you provided is hosted locally, and we’re unable to replicate the issue.
> 
> Could you please host add-in, upload it in a private repository and share it with @exextoc ? This will help us investigate and identify the root cause.

Ok, i will do.

**Comment by David-Buyer** [comment]
@exextoc i've added you to my private repository where i have the project you can see and test about this issue. For any info and details, i'm available.

**Comment by Swathy-Mothilal** [comment]
@David-Buyer Thanks for the invite. I noticed that the repo you shared contains several locally hosted files for the backend services. Could you host the necessary files externally and share just the manifest, so we can install and test it?

**Comment by David-Buyer** [comment]
> @David-Buyer Thanks for the invite. I noticed that the repo you shared contains several locally hosted files for the backend services. Could you host the necessary files externally and share just the manifest, so we can install and test it?

I've updated the readme file with some instructions for you. You can ignore backend part, beucase is not involved for the moment. Read the readme file and feel free to ask me further if it needs. Give me a feed if you have reproduced the issue please.

**Comment by Swathy-Mothilal** [comment]
@David-Buyer, We are still facing issues in setting up your repo. Could you please share a stripped-down version of the add-in, which focuses only on the problem?

**Comment by David-Buyer** [comment]
> @David-Buyer, We are still facing issues in setting up your repo. Could you please share a stripped-down version of the add-in, which focuses only on the problem?

@Swathy-Mothilal, after you clone the repo all you have to do is focusing just on **IPZS Office Add-InWeb** folder; you have there package.json file; do a "**npm install**" inside it to install the dependencies and after run the "**build:dev**" in the "**scripts**" section. After this process you will have the stuff compiled ( from **IPZS Office Add-InWeb\Components\src** ) inside the **IPZS Office Add-InWeb\Components\dist**. There you will find the manifest **IPZS Office Add-InManifest.xml** you can inject in the application. Anyway, in **IPZS Office Add-InWeb\Components\dist** you already have all the stuff compiled and the manifest also i pushed, ready to use and test in debugging source mode ( with .map files support ). The issue happens just if you follow the flow i explained above and it's systematic; i tried to implement all the flow logics in several strategies and workarounds, but it persists in the contexts i said.

Follow the steps i told and let me know, because there you have all you need to getting run the component with a few steps.

**Comment by David-Buyer** [comment]
@Swathy-Mothilal did you have any updates ?

**Comment by shighosh-msft** [comment]
Hi @David-Buyer, sorry for the delay in our response. We are able to repro the issue with the add-in you shared. The same has been added to our backlog. Internal tracking id: 310447

**Comment by David-Buyer** [comment]
> Hi @David-Buyer, sorry for the delay in our response. We are able to repro the issue with the add-in you shared. The same has been added to our backlog. Internal tracking id: 310447

Ok, np. I hope this will be fixed asap. Let me know if you need the testing repo support still, so i can remove it.

Thank you.

**Comment by saravanan-subramaniam** [comment]
+1 We are facing the same issue with our add-in.

**Comment by stephenegriffin** [comment]
@David-Buyer @saravanan-subramaniam I was asked to look at this and I checked on that internal bug - it looks like the solution was never posted back here. Basically, as the add-in developer, you need to call event.completed() when the dialog closes. This code snippet was shared:
```
dialog.addEventHandler(Office.EventType.DialogEventReceived, function (arg) {
    event.completed();
});
```

**Comment by mikelly-psat** [comment]
> ```
> dialog.addEventHandler(Office.EventType.DialogEventReceived, function (arg) {
>     event.completed();
> });
> ```

We've confirmed we're already doing this (in a separate web add-in than the folks posted above), but it doesn't seem to resolve the issue. The problem seems to fundamentally be with us moving the email with the Office.js context is still active. Is there a different way we can achieve this without getting into this state? We have a separate integrated spam-reporting addin that avoids this issue, but we still need to maintain our other addin to support mobile devices.

If we call completed too early on the event, then our add-in is killed before we're able to move the email.

**Comment by jsunkara-msft** [comment]
Hi @mikelly-psat , we are unable to reproduce this on our end. Is this something that has stopped working recently?

**Comment by mikelly-psat** [comment]
> Hi [@mikelly-psat](https://github.com/mikelly-psat) , we are unable to reproduce this on our end. Is this something that has stopped working recently?

This has been an issue for years. It's specifically coming up when we move the email after the dialog is closed, but before we complete our `MessageReadCommandSurface` event, and then the user attempts to report another message with our add-in. We call `event.completed()` immediately after we've moved the message using Graph / EWS APIs, as appropriate for the client's server.

If we move the mail while the dialog is still open, the addin terminates abruptly.

If we don't move the mail, and just complete the event, repeated reports are fine, however most of our customers don't find that workaround acceptable, as that leaves potentially malicious email sitting in the user's mailbox.

Prior GitHub issue: https://github.com/OfficeDev/office-js/issues/3050

**Comment by CELeviton** [comment]
We are also experiencing this issue when trying to utilize Proofpoint's "Submit Suspect Email" button. Proofpoint support directed us to this thread and is waiting for a resolution back from Microsoft.  Bumping this thread to see if there is any work being done to resolve this issue.

**Comment by jsunkara-msft** [comment]
This issue has been resolved.
