### ISSUE TITLE
OfficeThemes.css classes should not keep their default value

### ISSUE THREAD

**Issue by sami-romdhana** [OfficeDev/office-js#4882]
## Environment

* Platform: Office on the web
* Host: PowerPoint
* Operating System: Windows 11
* Browser: tested using Chrome and Firefox
 
## Expected behavior

OfficeThemes.css values get replaced with the current theme colors.

## Current behavior

The variables keep their default values on the web version. The desktop version works fine.

## Media

<table>
<tr>
<th>Desktop</th>
<th>Office on the web</th>
</tr>
<tr>
<td>
<img src="https://github.com/user-attachments/assets/f8f78065-a4a8-4a31-b66d-5b486545cddc" width="200" />
</td>
<td>
<img src="https://github.com/user-attachments/assets/e7785292-82fd-480b-98f7-f86e9235edc7" width="200" />
</td>
</tr>
</table>

## Link to live example

* [Manifest to an MRE](https://sami-romdhana.github.io/mre-powerpoint-theming/manifest.xml)
* [Source code of the MRE](https://github.com/sami-romdhana/mre-powerpoint-theming/)

## Context

We are trying to automatically pull theming information from the current presentation so that the user gets a customized experience. However we keep getting the default Office colors which might look jarring for our users in the context of our content add-in.

Additionally you might notice some theme colors missing in the desktop version, this has been reported in #4700.

**Comment by ivanosevitch** [comment]
Hi @EsterBergen and @m-hellesen , do you have any news on this issue?
This is currently preventing us from using PowerPoint themes in our addins, severely restricting our users' capacity to easily personalize the addin experience.
Thanks!

**Comment by sami-romdhana** [comment]
As of June 2025, this is still affecting us. Using the aforementioned MRE nets the same results.

**Comment by FrancoisBard-UpSlide** [comment]
Hello @EsterBergen @m-hellesen 
Can you please provide an estimate for a fix on this?
This is still affecting us.

**Comment by mayurandhare13** [comment]
Hi @sami-romdhana, a fix has been deployed. Could you please check again.
One point to note - you won't observe the theme change directly. You need to get them explicitly. Meaning if there is theme change happens, it won't automatically reflect the OfficeThemes.css rather you need to make a function call for it. I verified locally with your manifest/code as well. So, point is - you need to make function call to get the new theme data.

**Comment by sami-romdhana** [comment]
@mayurandhare13 thank you for your answer, as to your points:

> a fix has been deployed. Could you please check again.

I've tested this on my side, both using our internal add-in and the MRE and I still get default values on Office Online

<img width="300" alt="Image" src="https://github.com/user-attachments/assets/cdb13cf6-5b2a-4cb3-bec1-a50a47d41ba8" />

> you won't observe the theme change directly

I'm not expecting the theme to get automatically updated, I expect the theme to be loaded and correct at least on start up of the content add-in

> rather you need to make a function call for it

Can you clarify what you mean by that? Would that be if I expect the OfficeThemes colors to change as the theme changes? I don't but I still tried to load the CSS without relying on including the OfficeThemes.css file in the HTML head, by fetching, and the values are still the default values (even waiting upwards of 1 full second)
