### ISSUE TITLE
Outlook displays Smart Alert after Addin allows the mail

### ISSUE THREAD

**Issue by mkondadg** [OfficeDev/office-js#4968]
During our addin development testing, if the addin takes more than 5 secs to respond, a first smart alert displays showing its working.
Later if the addin allows the mail, Outlook still displays "Send" / "Don't Send".

This will contradict with the Addin response of Allow incase of auditing if the user clicks on "Don't Send".

## Your Environment

    Windows desktop
    Outlook
    You have Microsoft Outlook Version 1.2023.1018.300 (Production).
    Client Version is 20231027003.07 .
    Windows 10 Enterprise 21H2 19044.2006

You have Microsoft Outlook Version 1.2024.1002.100 (Production).
Client Version is 20241004002.11.
WebView2 Version is 129.0.2792.79.
 
## Expected behavior
Allow the email to be sent without displaying Smart alert

## Current behavior
Outlook displays smart alert again.

## Steps to reproduce
After OnMessageSend callback is triggered, delay by 10 secs in calling asyncResult.asyncContext.completed (true)

## Context
This will contradict with the Addin response of Allow incase of auditing if the user clicks on "Don't Send".

**Comment by mkondadg** [comment]
Attached Smart Alert image for reference.

![Screenshot 2024-10-15 192327](https://github.com/user-attachments/assets/c4eaca65-3d5b-425c-b10e-c75e962849bc)

**Comment by neprasad-microsoft** [comment]
Hi @mkondadg 
Can you please attach a video of the issue. It is not clear from the steps and the screenshot that what is the problem here.

**Comment by neprasad-microsoft** [comment]
Hi @mkondadg 
I was able to repro the scenario.

- Send an email with an OnSend add-in installed.
- Wait for the add-in to finish running, after the long running dialog comes up.
- The long running dialog will change to the dialog shared above.

This is expected behaviour on all platforms. If you want this to be changed, then it will be taken up as a new feature request.
We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered when we go through our planning process.

**Comment by alexm-plutoflume** [comment]
My team also is facing this, it's a UX quirk that doesn't make sense in our opinion.

@neprasad-microsoft I'm wondering why this is considered 'expected' behavior and the design choice around this?

If our Add-in has finished processing and determined that the email should be allowed to send, why is MSFT showing a dialog giving the user an option to send or don't send? That seems confusing to the end user, and it seems contradictory to the Add-in completing the event with "allowEvent" set to true.

If the Add-in finishes processing before the progress popup shows up and allows the email this dialog isn't show. Why does it need to show it if the progress pop up shows?

**Comment by JuaneloJuanelo** [comment]
FYI everyone we are taking this DCR on the team. We will replace this behavior so we dont show a redundant "send" button, which we agree is not the best UEX.  Above was mentioned by design from the perspective of not just disappearing the dialog, we will change the text to "sending email" wait a few moments and send the email autmaticallty.

**Comment by allfii** [comment]
@JuaneloJuanelo May I know what is the timeline?

**Comment by markdii** [comment]
Hi @JuaneloJuanelo , is there a timeline for the fix? Most of our users are refraining from using our addin due to this. They are fine with the addin is taking too long dialog but not ok with the fact that they have to react to the additional dialog.

**Comment by g2002dhruv** [comment]
I have faced same thing in my AddIn. Am also want to not seen this alert (Send, Don't Sent) if processing is complete then directly send the mail to the user.

<img width="400" alt="Image" src="https://github.com/user-attachments/assets/507cb94d-0d86-42ac-8cf8-fbef8470ded6" />

**Comment by kdeclerck** [comment]
![Image](https://github.com/user-attachments/assets/c23277ff-1aa3-4c5c-83a7-206b1b1545d2)

We're also seeing this issue on our end. Our users have started reporting it as well, and it's becoming quite frustrating for them. Do you have any timeline for a fix? We've also noticed the message appears inconsistently. In some cases, it shows up within just a second of processing.

**Comment by markdii** [comment]
Hi @JuaneloJuanelo , may we know is there any timeline on this fix please? This is a kicker for us and we are considering reverting back to the old On-Send event should there be no concrete plan/timeline for this fix

**Comment by max-yushchuk** [comment]
Are there any updates on this bug? Many users started to complain on this behavior.

**Comment by JuaneloJuanelo** [comment]
FYI this issue is fixed now !  The mentioned dialog will not be shown the user and upon successful verifications the email will fly away. thank for the feedback! 

1.  100% out in OWA 
2. 100% in New Outlook
3. Win32 Traditional Starting on Build 16.0.18526+ (released ~March 2025)

Mac will follow soon!

**Comment by charmingwhite73** [comment]
Hello @JuaneloJuanelo   we are still seeing the "finished sending" send/don't send.

**Comment by neprasad-microsoft** [comment]
@charmingwhite73 

Which platform are you seeing this on? In case it on Windows Classic, can you please check that the Build is 16.0.18526 or above.

**Comment by charmingwhite73** [comment]
Hi, v2408.  it's confusing. We're having the problems in November, your comments says that traditional Outlook was fixed in March 2025, yet we have a version 2408 that was released in August, therefore suggesting 2408 was still not fixed.   I will explore getting the 18526 build installed.  https://learn.microsoft.com/en-us/officeupdates/semi-annual-enterprise-channel#version-2408-november-11

**Comment by markdii** [comment]
> FYI this issue is fixed now ! The mentioned dialog will not be shown the user and upon successful verifications the email will fly away. thank for the feedback!
> 
> 1. 100% out in OWA
> 2. 100% in New Outlook
> 3. Win32 Traditional Starting on Build 16.0.18526+ (released ~March 2025)
> 
> Mac will follow soon!

Hi @JuaneloJuanelo , thank you. 

Btw, may I know when will this be fixed in Mac? Also, is there an opened issue that tracks this?

cc: @neprasad-microsoft

**Comment by jfeeney25** [comment]
Hi @neprasad-microsoft , we are also wondering when this will be fixed for Outlook for Mac. Thanks!
