### ISSUE TITLE
Outlook Online, ALL panel add-ins now have additional scroll

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#5051]
# Provide required information needed to triage your issue
Since last Friday we've started to receive complains that the bottom part of our Outlook add-in panel is not visible. Starting from today, we can also reproduce this issue, please see the screenshot below.

## Your Environment
* Platform: Office on the web
* Host: Outlook
* Office version number: ______
* Operating System: Windows 10 22H2
* Browser (if using Office on the web): Chrome Version 130.0.6723.92
 
## Expected behavior
There should not be any additional scrolls.

## Current behavior
The Outlook add-in panel has an additional scroll, the bottom part of the panel is not visible.

## Steps to reproduce
1. Sign in to Outlook Online.
2. Create a new message.
3. Open an add-in's pane. For example, you can try to open the Script Lab add-in.

# Provide additional details
It seems the issue depends on a Microsoft account. We can reproduce it on several accounts, but not on all of our Microsoft Outlook accounts.

## Context
The issue is critical for us – there are important controls in the bottom part of our panel.

## Useful logs
- [ x ] Screenshots
![image](https://github.com/user-attachments/assets/fa3eb2de-7cf5-4cfc-be9d-548a7f321b3f)

**Comment by parlato-vooma** [comment]
Office JS team please address this 🙏  it relates to my recently added ticket: https://github.com/OfficeDev/office-js/issues/5052

**Comment by katie-vooma** [comment]
please fix!!! would help!!!

**Comment by parlato-vooma** [comment]
Just a friendly bump on this ticket - this is impacting all of our users; our primary CTAs are hidden from view, and users are confused about how to complete critical tasks using our add-in. Can we please get an update?

**Comment by Oleg-O** [comment]
Thank you, we've alerted the owning team, I expect a prompt follow-up and a fix.

**Comment by cody-lettau** [comment]
Please fix this ASAP.

**Comment by cody-lettau** [comment]
@exextoc can we get an update on this? Although this seems like a small bug, for those of us who have CTAs and actions/buttons fixed to the bottom of the pane are severely impacted by this issue.

**Comment by anjalitp** [comment]
This issue has been fixed and is being rolled out. We will update this thread once fix is available 100% in Production.

**Comment by cody-lettau** [comment]
@anjalitp how long is this rollout expected to take? I'm still seeing the issue on at least one of my accounts.

**Comment by parlato-vooma** [comment]
@anjalitp please provide an update on the rollout - this is still impacting our users.

**Comment by DmitryKostochko** [comment]
@Oleg-O, @anjalitp,

As far as we can see, the scroll has decreased from 80px to 15px:
![image](https://github.com/user-attachments/assets/42f12b92-a757-4d8a-b321-4c68b12315a3)

I guess this is not the final fix, but rather some kind of an intermediate fix, correct?

>> Thank you, we've alerted the owning team, I expect a prompt follow-up and a fix.

Maybe this owning team has their own channel for reporting bugs? Or is there another way to contact them?

**Comment by neprasad-microsoft** [comment]
Hi @DmitryKostochko 
We had previously resolved this issue, but it may have regressed due to another change. We are actively working on it and sincerely apologize for any inconvenience caused. We will update this thread as soon as we have a fix.
