### ISSUE TITLE
DisplayDialogAsync displaying empty popup on Excel desktop (Windows)

### ISSUE THREAD

**Issue by b-gonzalez** [OfficeDev/office-js#5314]
# When I click a button in my taskpane, the window is blank and not displaying the UI elements

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: (Version 2503 Build 16.0.18604.20000) 64-bit 
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior

The popup should display the UI elements in a different (non-taskpane) HTML file. This was previously working correctly.

## Current behavior

When I click the button in the taskpane, a blank popup opens up with no UI elements

## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

My add-in is deployed on a server and I can run it in Excel online. Interestingly, it continues to work as expected on Excel on the web. So it looks like this may be related an issue on Excel on the desktop. 

I also recorded a video using my add-in on December 1st 2024 I believe. So the functionality was working as expected at that time.

## Context

My button is linked to functionality that is used to enter login credentials. So the UI element not working as expected is preventing me from logging in on Excel desktop

## Useful logs

- [ ] Screenshots

Excel desktop:

![Image](https://github.com/user-attachments/assets/2d337d02-1219-4a6f-b4d4-3b402bbfb2e2)

Excel on the web:

![Image](https://github.com/user-attachments/assets/2c345b81-0e4e-46fb-ada4-cedd85d5175f)

**Comment by guoms1** [comment]
Hi, @b-gonzalez 

Thanks for reporting this issue! I was able to reproduce it and I'm currently reaching out to experts for further insights. I appreciate your patience, and I'll update you as soon as I have more information.

Best,

**Comment by b-gonzalez** [comment]
@guoms1 Great thanks.

**Comment by guoms1** [comment]
Hi, @b-gonzalez

We applied a change that should fix this issue. Could you please have a try?

Thanks,

**Comment by b-gonzalez** [comment]
@guoms1 I am still showing that the dialog is not displaying as expected. I am also getting an error. I'm not sure if it's related but I was not getting this error when the add-in was working as expected. Please see the screenshot below:

![Image](https://github.com/user-attachments/assets/a59966d1-9b1c-4caa-b641-c9eca015b934)

**Comment by drittich** [comment]
I have the same issue happening while developing an Excel add-in on my desktop. I am attempting to load a local page served from the same host as the add-in, but the dialog is blank. I confirmed there are no errors by inspecting the result status, and additionally there are no console  errors.

**Comment by b-gonzalez** [comment]
A few things I forgot to add which may also be relevant:

1. I have multiple Office licenses on my account
2. The license that the add-in is using is my developer license
3. My developer license is on the beta channel
4. My license version is: (Version 2503 Build 16.0.18604.20000) 64-bit

**Comment by guoms1** [comment]
Hi, @b-gonzalez and @drittich 

We have conducted an initial investigation into the issue and are actively working on a solution. We expect to have results soon and will keep you updated. 

Let us know if you have any questions in the meantime!

Thanks,

**Comment by drittich** [comment]
@guoms1  Thanks for the update. I would like to know if there are any workarounds in the meantime, and whether this just impacts developer experience or end users as well. E.g., I need to know that I can rely on the modal functionality working for a variety of operating  systems and versions of Excel, and whether I will need multiple code paths depending on these variables..

**Comment by guoms1** [comment]
Hi, @drittich 

Thank you for your patience. I wanted to update you that the issue is due to a regression. Unfortunately, the rush of the long holiday meant that this problem wasn’t handled as promptly as we normally would. We have now identified the root cause and expect everything to be back to normal by this time tomorrow.

We truly value your trust in us and are committed to ensuring a smooth experience moving forward. Thanks again for your understanding.

Best regards,

**Comment by drittich** [comment]
@guoms1 Thanks, I appreciate the updates!

**Comment by guoms1** [comment]
Hi, @b-gonzalez and @drittich 

We’ve fixed the issue! Please check if everything is working now. If the problem is resolved, feel free to reply or close the issue.

Best regards,

**Comment by b-gonzalez** [comment]
@guoms1 Thanks for your assistance. I show that the issue is now fixed:

![Image](https://github.com/user-attachments/assets/4ba7949f-a179-49c6-85f8-07e15f177861)

I will close the issue.

**Comment by drittich** [comment]
I can confirm the dialog works as expected now.
