### ISSUE TITLE
Input control not able to get focus

### ISSUE THREAD

**Issue by djsakariya** [OfficeDev/office-js#5476]
# Provide required information needed to triage your issue
In office addin, input control is not able to get focus, when click on input box, focus goes to excel cell.
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Microsoft® Excel® for Microsoft 365 MSO (Version 2502 Build 16.0.18526.20144) 64-bit 
* Operating System: windows 11 Pro
* Browser (if using Office on the web): it works fine in web version
 
## Expected behavior

Input box should be able to get focus
## Current behavior

when click on input box and start typing, focus goes to Excel cell and key stroke typed in excel cells only
## Steps to reproduce

1. npm install -g yo generator-office
2. yo office
3.choose project type - Office Add-in Task Pane project
4. Script type - javascript
5.  name your add-in - any name which you wish. e.g. "My Office Addins"
6.  cd "My Office Addins"
7. open taskpane.html file and remove all elements from body and add form and input
8.  

<img width="783" alt="Image" src="https://github.com/user-attachments/assets/679ff1d6-e2a6-433c-ba94-a14c1b5209e6" />

9. start webpack by "npm start" on terminal
10. it will open excel and plugin
11. click on inputbox, focus will go to excel cell
12. 

<img width="957" alt="Image" src="https://github.com/user-attachments/assets/63f0bd14-4bea-488a-8333-c762423997dd" />

13. # Link to live example(s)

# Provide additional details

## Context

this is blocker as it cannot handle any user input in excel addins

https://github.com/user-attachments/assets/d64e9d8b-6f11-43b7-806d-09cb6da61201

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by graysenpack** [comment]
We are seeing the same problem with our Microsoft Word Add-in. I'm attaching a video of some troubleshooting we did recently. This only appears to be happening with Windows users.

https://www.loom.com/share/c4f05885ca8d4a89874a4418056a20de

**Comment by graysenpack** [comment]
Another similar report to this: https://github.com/OfficeDev/office-js/issues/5471

**Comment by PauliusMilmantas** [comment]
This is a critical issue for us and our clients also.

**Comment by ptrostianko** [comment]
In our excel add-in we have same issue all input text fields not focusing, than you click on them.

![Image](https://github.com/user-attachments/assets/8f6c5b03-e0c2-44fd-a43d-32250c19e238)

**Comment by guoms1** [comment]
Hi, all

I'm sorry to hear you're experiencing this issue. I wasn't able to reproduce the problem on Excel Desktop build 5203, so it appears that the issue may have been resolved in this build. To help clarify, I recorded a video that shows both the HTML code I used and a live demo of the Excel add-in's Taskpane. I hope you find this helpful.

Please let me know if you have any further questions or need additional assistance.

Best regards,

https://github.com/user-attachments/assets/b23565ab-78eb-4132-8c96-0de427b606ce

**Comment by djsakariya** [comment]
@guoms1 
my excel version is up to date and i still facing this issue.

This works fine on my colleague's machine having same version.

<img width="494" alt="Image" src="https://github.com/user-attachments/assets/e10966c7-9039-46a9-8ce5-a466eedec2ad" />

**Comment by guoms1** [comment]
Hi, @djsakariya 

Thank you for the update.

I've learned that this issue is impacting a significant number of users on build 5202, though not everyone is affected. This suggests that build 5203 might also be at risk. We're actively investigating the problem and working on a resolution, and we'll update you as soon as we have more information.

Best regards,

**Comment by trigurl** [comment]
Hello folks please refer to https://github.com/MicrosoftEdge/WebView2Feedback/issues/5144

1) Try updating to yesterday's version of 134.0.3124.68 WebView2 Runtime.
https://developer.microsoft.com/en-us/microsoft-edge/webview2/?form=MA13LH

2) Try again after shutting down all WV2 instances by "tskill msedgewebview2*" or rebooting your machine.

Can you see if this works?

**Comment by djsakariya** [comment]
@trigurl it works as expected with 134.0.3124.68 WebView2 Runtime.
Thanks

**Comment by Shukla-Dev** [comment]
if I already have webview2 runtime in system how can I install fixed one in windows ?

**Comment by guoms1** [comment]
Hi, @Shukla-Dev

You could patch your webview2 runtime with the instructions mentioned by [trigurl](https://github.com/trigurl). I copied the instructions here:

Hello folks please refer to https://github.com/MicrosoftEdge/WebView2Feedback/issues/5144

Try updating to yesterday's version of 134.0.3124.68 WebView2 Runtime.
https://developer.microsoft.com/en-us/microsoft-edge/webview2/?form=MA13LH

Try again after shutting down all WV2 instances by "tskill msedgewebview2*" or rebooting your machine.
