### ISSUE TITLE
Inconsistent valuesAsJson cell value type between Excel Online and Excel Desktop in Script Lab sample "Data types: Formatted numbers"

### ISSUE THREAD

**Issue by didu9898** [OfficeDev/office-js#5866]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web & desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 2504 (Build 18730.20226)
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
The type property should be consistent across platforms for the same formatted number values. 

## Current behavior
Excel Online: type = "Double"
Excel Desktop: type = "FormattedNumber"
**Note: This issue started yesterday (04-July-2025) and was working fine before.**

## Steps to reproduce

1. Open Script Lab and load the "Data types: Formatted numbers" sample.
2. Run the sample to set formatted numbers (date and currency) in cells.
3. Click all 4 buttons one by one to insert workbook, formatted date & formatted currency
4. Click "Log data types" and check the _type_ property in the console.
5. Compare results on Excel Online & Excel Desktop.

## Useful logs
Excel desktop:
![Image](https://github.com/user-attachments/assets/6e627de9-49cf-40c0-b026-69bd1ad4febd)

Excel on the web:
![Image](https://github.com/user-attachments/assets/998a893d-23e7-4851-a462-33100855c769)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by RuizhiSunMS** [comment]
Hi @didu9898, thx for reporting here. I have reproduced it and will reach out to colleagues for further investigation. Mark it as 10294924. Will update here if any new information.

**Comment by RuizhiSunMS** [comment]
Hi @didu9898 , we did some investigations and found it could be caused by release gap. Now it should be resolved. 
Please have a try and feel free to raise question here if you still met it.

**Comment by didu9898** [comment]
Hi @RuizhiSunMS, I gave it a try — on Excel for Web I still get type Double, but on Excel Desktop I’m getting FormattedNumber.

![Image](https://github.com/user-attachments/assets/99c05862-650c-49d9-8c8b-5f1870a47a33)

**Comment by RuizhiSunMS** [comment]
> Hi [@RuizhiSunMS](https://github.com/RuizhiSunMS), I gave it a try — on Excel for Web I still get type Double, but on Excel Desktop I’m getting FormattedNumber.
> 
> ![Image](https://github.com/user-attachments/assets/99c05862-650c-49d9-8c8b-5f1870a47a33)

would you please do something like cleaning cache or restart? I just tried with 2506 and it turned to be good now (showing double)

**Comment by didu9898** [comment]
@RuizhiSunMS, I'm on build 2504, so I assume I’ll still receive the FormattedNumber type. However, I saw that [FormattedNumberCellValue](https://learn.microsoft.com/en-us/javascript/api/excel/excel.formattednumbercellvalue?view=excel-js-preview) is marked as deprecated. Should we start adopting the new Double type instead?

**Comment by RuizhiSunMS** [comment]
@didu9898 , 
Formatnumber is deprecated, please don't use it anymore.
The support version is: Windows Excel version>16.0.18623.20116 or MAC Excel version > 16.95.324.2. Your 2504 should have been released to. Please have another try or make a update.

**Comment by didu9898** [comment]
Thank you @RuizhiSunMS. I will close this issue now. :)
