### ISSUE TITLE
Admin managed Add-in fail to load after Office upgrade with "You don't have permission to use this add-in"

### ISSUE THREAD

**Issue by eirik-vince** [OfficeDev/office-js#5979]
We are experiencing issues with an Excel add-in not loading after updating Office from 2505 to 2507.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Dekstop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2507
* Operating System: Windows 11
* Browser (if using Office on the web): N/A
 
## Expected behavior
After updating Office from 2505 to 2507 by changing the update channel, an add-in stoped

## Current behavior

Add-in will not load, instead displaying the error message "You don't have permission to use this add-in"

<img width="425" height="160" alt="Image" src="https://github.com/user-attachments/assets/a169e73d-6a5d-4d08-a984-313d29667b8a" />

The add-in load properly after rolling back to the previous Office version.
Clearing the web add-in cache resolves the issue and the add-in loads properly. 
If clearing the cache, and then rolling back to the previous Office version, then the add-in will not load

It seems that at some point there was a change to the web add-in caching which causes the issue.

## Steps to reproduce

1. Install Office 2505 - Monthly Enterprise Channel
2. Deply a web add-in by uploading a manifest using "Integrated apps" from M365 admin center
3. Verify the add-in launches
4. Change the update channel to Current and update Office
5. The add-in won't open, erroring with "You don't have permission to use this add-in"

## Context

We have several customers affected by this.

**Comment by RuizhiSunMS** [comment]
@eirik-vince , may I confirm that:
1. users using 2505 works fine all the time
2. for users do nothing but updating to 2507, they met this permission error.
3. for users upgrading to 2507, things would be good if clear the cache
4. for users upgrading to 2507, things would be good if go back to 2505
5. for users upgrading to 2507, they would meet permission error if clear the cache then go back to 2505. (and clearing cache again wont resolve it)

**Comment by eirik-vince** [comment]
@RuizhiSunMS  
1. Correct. Can also confirm that installing 2507 on a clean machine works OK
2. Correct
3. Correct
4. Correct, as long as they do not clear the cache first
5. Clearing the cache again after rollback to 2505 solves the issue.

As far as I can tell there seems to be some cache incompatability between Office the versions.

**Comment by tincann** [comment]
We are facing the same issue for users that upgraded to 2507. Clearing the cache does seem to be the workaround.

**Comment by AmandaHan123** [comment]
Hi @eirik-vince and @tincann , could you help to confirm if the issue only repro with admin deployed addin, or repro with both admin deployed addin and addin that is manually installed from Office Store?

**Comment by tincann** [comment]
@AmandaHan123 our add-in is admin deployed through the O365 admin panel (integrated apps).

**Comment by eirik-vince** [comment]
Hi @AmandaHan123 same for us. We haven't tried/tested with Apps from the store

**Comment by RuizhiSunMS** [comment]
Hi @tincann and @eirik-vince , would you please share that which addin you are using or you can repro it with any addin?

**Comment by eirik-vince** [comment]
@RuizhiSunMS for us it's failing for 3 different add-ins, all of them custom deployments via Integrated Apps.
You can test with this [manifest](https://vxl-dev.vincelive.dev/manifest.dev.xml)

**Comment by RuizhiSunMS** [comment]
@eirik-vince I can't open the link, would you please double check it? 
And please try some addins from Store as well, it would be helpful for us to investigate.

**Comment by eirik-vince** [comment]
@RuizhiSunMS sorry about that, the link should work now

**Comment by eirik-vince** [comment]
@RuizhiSunMS sorry about that, fixed the link

**Comment by RuizhiSunMS** [comment]
Hi @eirik-vince , my colleague and I succeeded to repro it. Mark it as 10412239, our owning fc will go on investigation. We will update here if we made any progress.

**Comment by vyvo2412** [comment]
we are having this issue as well

**Comment by SiruiSun-MSFT** [comment]
Hi @eirik-vince, @vyvo2412 and @tincann, Thanks for your reporting above! We are now under the investigation to locate the root cause. May I ask that, 

  1. Whether the steps you use to reproduce the Permission error are the same with @eirik-vince reported at the beginning of this thread(Update from 2505 MEC to Current Channel 2507 or later & the add-in was deployed on 2505)? 
  2. Currently, there seems to have two workarounds for mitigation the error. The first is to clear the cache Under Wef folder, and the other is to reinstall the add-in in the Add-in Store and restart Excel. We'd like to know whether the two workarounds could help you out first to unblock your customer?

looking forward for your reply, meanwhile, we will keep the investigation and update here if we got any progress! Thanks for your patience again!

**Comment by tincann** [comment]
Hi @SiruiSun-MSFT ,

> * Whether the steps you use to reproduce the Permission error are the same with [@eirik-vince](https://github.com/eirik-vince) reported at the beginning of this thread(Update from 2505 MEC to Current Channel 2507 or later & the add-in was deployed on 2505)?

Correct. It's basically: 
1. Install the add-in on Excel version 2505 or earlier through O365 integrated apps (upload manifest)
2. Open the add-in once inside Excel (this fills the cache)
3. Update Excel to 2507
4. Try to open the add-in through the Ribbon and see the permission error

> Currently, there seems to have two workarounds for mitigation the error. The first is to clear the cache Under Wef folder, and the other is to reinstall the add-in in the Add-in Store and restart Excel. We'd like to know whether the two workarounds could help you out first to unblock your customer?

This is now our current workaround. However, for some larger customers this must be done through their IT department, where they can clear the cache in bulk through Intune.

**Comment by eirik-vince** [comment]
It seems Microsoft recently rolled out build 2507 to the Monthly Enterprise channel, without fixing the issue.
For others experiencing the same issue, you can follow this guide for how to clear the cache: [Clear the Office cache | Learn Microsoft](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache#clear-the-office-cache-on-windows)

**Comment by miikka-laakso-dh** [comment]
It seems that this issue is escalating as 2507 is published in Monthly Enterprise channel, and Office add-in cache is expiring for end users. What is estimated schedule for fix?

**Comment by ptrflk** [comment]
This is now starting to seriously affect our customers.
Potentially over 100,000 users affected.
There's no way to get all of them to manually clear the cache.

What is the status of an update or hotfix from Microsoft?

**Comment by RuizhiSunMS** [comment]
@ptrflk may I confirm that:
1. this problem reproed to you after updating office?
2. only deployment addin can repro it?

Update:
I did a quick try to deploy an addin and validate it from an end user, everything looks good. But my office is latest so maybe your cases are not covered. If you still encounter it, please share the accurate version number to help us investigate.
Looking forward to your reply, I will check it.

**Comment by ptrflk** [comment]
This has affected at least three different customers after they updated to 2507, being on Monthly Enterprise Channel. 
We have confirmed that customers on Current Channel do not have the problem, since CC is 2508.

**Comment by RuizhiSunMS** [comment]
Hi @ptrflk , after some work I finally repro it with my PC. Will reach out to the owning team.
Btw, would you please share the amount of affected users now? It would be helpful for us to understand the priority
And also inform @miikka-laakso-dh @spinit-jlin, @eirik-vince, @tincann and @jk-vince if you can share your amount as well.

**Comment by tincann** [comment]
@RuizhiSunMS This is potentially affecting over a thousand users for us when their semi-annual channel updates. This has already affected hundreds of users that have updated recently.

**Comment by eirik-vince** [comment]
@RuizhiSunMS From testing on our end, this issue is caused by some change from build 2506 and 2507, specifically with regards to chaching of web add-ins. From our testing a cache on <2506 doesn't work on >2507 and vice versa.
Meaning that a working cache on build 2507+, fails on 2506 and below.

For us: it did affect ~1000 user who where on Current Channel, all of which had to resolved by our customers. 
We're estimating approx 40k total affected users on Monthly Enterprise channel. Unknown for Semi-annual channel, but it's going to be a lot.

However, as this issue might "re-appear" in case of a roll-back of Office, the above numbers are not final; seeing as the issue occurs when crossing between build 2506 and 2507 regardles of direction.

Needless to say, build 2507 should not have been rolled out to Monthly Enterprise without fixing this issue, not put into the backlog. Can we at the very least expect a hold on the semi-annual channel?

**Comment by RuizhiSunMS** [comment]
Hi @tincann @ptrflk and @eirik-vince , thx for the confirmation. We have reached out to the owning team about the impact and severity. They are working on it.
Will update here if we made any progress. Thx

**Comment by miikka-laakso-dh** [comment]
@RuizhiSunMS it will potentially affect to thousands of end users in our case

**Comment by ptrflk** [comment]
We can only confirm customer that has reached out to us regarding this problem, too many for us to reach out to all. As yet confirmed over 20 000 users, 50 000 more users will get affected shortly.

**Comment by abril927** [comment]
Hi, experiencing this too. One easy workaround for users instead of clearing the web add-in cache that seems to work well too is:
1. "Add-ins" in Home ribbon
2. "More add-ins" button
3. Click the "Admin Managed" tab
4. Click "Refresh" button in top right
5. The add-in should reappear and you can double-click it

By the way this may need to be re-labelled as it's labelled "Area: Excel" but we are experiencing it in PowerPoint as well.

**Comment by eirik-vince** [comment]
@abril927 Glad you found a simpler workaround that works for you.
We tried that procedure during testing on our end, but with mixed results. In a lot of cases it didn't fix the problem. Clearing the cache however has so far always worked.

If this issue affects add-ins for other Office products, then I agree that the labels needs to be updated to reflect that.

**Comment by ptrflk** [comment]
> By the way this may need to be re-labelled as it's labelled "Area: Excel" but we are experiencing it in PowerPoint as well.

As well as Word, as confirmed by our customers.

Also, regarding the workarounds: anything that requires an action from end users is not viable for us, since each customer’s organisation has too many users.

So, Microsoft — fix this ASAP!

**Comment by SiruiSun-MSFT** [comment]
Hi everyone, 
Sorry for bringing into this issue and keep you waiting here! Now, the issue has been set to the highest priority one and our colleagues are now actively working on the investigation and fix! Will keep updating more progress and information here! We totally understand your situation, and will try our best to resolve it ASAP! Before the fix arriving, we'd be appreciate if you could use the workaround to unblock first. Thanks again!

**Comment by ptrflk** [comment]
> Before the fix arriving, we'd be appreciate if you could use the workaround to unblock first. Thanks again!

Thank you for addressing this issue. Any updates? 

Regarding your suggested workaround - as I stated earlier - this is not viable for large organisations and should not be seen as such. So please consider this a major issue!

**Comment by AmanDhally** [comment]
Hi, any updates on this? we are still having this issue at our Org and have to add add-in eveytime when an update is installed on the laptop.

**Comment by christerwahlund** [comment]
Dear MS, any updates on this issues is much appreciated. Workaround doesnt fix the issue for us.

**Comment by NealD85** [comment]
Also seeing this in 2507. Rolling back to previous versions for testing is not currently an option. Any updates or another proposed workaround would be greatly appreciated.

Edit: We're on Monthly Channel, and noticed the issue after updating from 2506 to 2507.

**Comment by edamlmmv** [comment]
Hi,

On my side,I am seeing this issue not only for Admin managed Add-in but also the ones installed via the AppSource store. This is troublesome because for publicly available add-in on the AppSource store, I cannot just change the manifest id or else the reviewer on the partner center refuse to publish my add-in.

In my case it is an Outlook office add-in. This is particularly blocking for Outlook since it doesn't support automatic cache clearing as written [here](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache). I think it would be a good idea if the MS team add a way in the Outlook application itself to refresh the add-ins cache without having to
1. Uninstall / Re-install the plugin
2. Log out / Log back in


Because, I was told by our client that this process is unacceptable. For the moment, this means no update to the manifest.xml and only updating the javascript packages but it may be blocking us from further development in the future...

This happens for Mac & Windows using an office add-in in the Outlook app (Legacy or new). For the browser, you can get around the issue by using an incognito browser which is less troublesome than uninstalling / reinstalling & logging out / back in.

**Comment by SiruiSun-MSFT** [comment]
Hi all, Sorry for letting you wait here for a long time! We've just got the response from our partner team that the issue has been fixed now. Here is the timeline for each version: 2506/2507 - 10/14,  2508 - 10/7. 2509+ already has the fix on initial release. Please help us verify on your version and feel free to reach us if you have more questions! Thanks for your patience here!

**Comment by gtutunaru-deepip** [comment]
We have reports of users on version 1509 (specifically build `19231.20194`) still experiencing this issue, the add-in keeps disappearing randomly
EDIT: this is on the Word client

**Comment by SiruiSun-MSFT** [comment]
Hi @gtutunaru-deepip, 
This GitHub thread is intended to track the yellow error bar issue with the message “You don't have permission to use this add-in”, not the add-in disappearing issue.
It would be better to create a new thread to track the problem you reported.
Thanks!

**Comment by gtutunaru-deepip** [comment]
Hi @SiruiSun-MSFT ,

Thank you for your answer, I wrote the comment in this thread since in another associated issue the two were related : https://github.com/OfficeDev/office-js/issues/5708 (See "Current behaviour" on the original issue description).

Could you confirm that the issues are not related ? Or at least that the fix in version 2509 does not concern the disappearing add-in ? 

Thanks !

**Comment by SiruiSun-MSFT** [comment]
Hi @gtutunaru-deepip, Thank you for your reply! The fix I mentioned earlier only addresses the permission error when switching Office versions, and it may not be related to the disappearing add-in issue.
I noticed that issue #5708 has been closed as completed. If you are still encountering this error and have solid repro steps, it would be better to create a new issue to track it.
Thanks for your support and patience!
