### ISSUE TITLE
In Outlook OnSend Add-in, iframe in Dialog sometimes has pointer-events set to none, making content unclickable.

### ISSUE THREAD

**Issue by t-miyake** [OfficeDev/office-js#5980]
# Provide required information needed to triage your issue
In the Outlook OnSend add-in, there are cases where the iframe within a Dialog has "pointer-events" set to "none".
As a result, all content displayed by the add-in within the Dialog becomes unresponsive to user interaction.
In normal situations, "pointer-events" is set to "auto".

When the issue occurs, the add-in becomes completely unusable, and **users cannot send emails!**

## Your Environment

* Platform/Host: Outlook on the web and Outlook (new)
* Office version number:  Issue frequently observed with 20250725003.04 and later.
* Operating System: Various
* Browser (if using Office on the web): Any browser
 
## Expected behavior

pointer-events is set to auto, and users should be able to interact with all content within the iframe of the Dialog as expected.

## Current behavior

pointer-events is set to none for the iframe in the Dialog, and users are unable to interact with any content within the Dialog.
In normal cases, pointer-events is set to auto.

## Steps to reproduce

Currently, the conditions to reproduce this issue are unknown.

Our product is an OnSend add-in for Outlook. When the user sends an email, a Dialog is displayed using the Dialog API (with displayInIframe set to true).

In some cases, the div surrounding the iframe has its pointer-events set to none, which causes the issue.

# Provide additional details

- The issue occurs for some users but not others, even within the same tenant.
- When the issue occurs, restarting Outlook or reopening the browser temporarily resolves the problem.
- At present, we have confirmed that this issue is affecting multiple users at 5 different customers (tenants).
- Since July 28, reports of this issue have been increasing.
- We considered the possibility of interference from antivirus or security products, but affected customers have different environments. Even customers using only Microsoft Defender experience the problem. Therefore, we do not believe it is related to such products.

## Context
Although currently only a small number of customers are affected, our product has over 200,000 users.
If this is a bug in Outlook, the potential impact in the future is significant.
When the issue occurs, the add-in becomes completely unusable, and **users cannot send emails!**

## Useful logs

Screenshots
- [x] Screenshots

Screenshot when the issue occurs
<img width="1772" height="996" alt="Image" src="https://github.com/user-attachments/assets/58fa922f-d14c-4ba4-a839-245a9c7d8541" />

Screenshot in the normal state
<img width="1561" height="1092" alt="Image" src="https://github.com/user-attachments/assets/1081b0b1-8dba-4a91-8763-b513f73a627f" />

**Comment by shane-dyer** [comment]
+1 on this, I also have users reporting a similar issue, although I am unable to replicate it myself yet.

**Comment by MrCeleryman** [comment]
+1 on this, Users reporting as well, have been able to replicate in the new outlook only by adding a category to an email through our add in and then moving that email to a folder -> upon opening the add in again on a different email it has the pointer-events: none on it

Possibly related to the add in context becoming invalid after moving or deleting a message in new outlook?

**Comment by mailchecktool-admin** [comment]
Our add-in is also experiencing the same issue.
Indeed, we can reproduce it using the same method.
@exextoc 
We are currently investigating whether this is a bug that occurs only in specific versions or not.
Is there a way to upgrade or roll back versions in OWA and the new Outlook?

**Comment by shighosh-msft** [comment]
Thanks for reporting this @t-miyake - without a clear repro it is difficult to debug the issue at our end. 

@MrCeleryman - thanks for sharing the steps to repro the issue, but from the description you shared it is not clear that if a display dialog is involved in your case like originally reported by @t-miyake. In case you have a consistent repro, could you please share a repro video of the same? This would greatly help us get to a resolution sooner.

**Comment by truchonh** [comment]
We are also experiencing the issue both on new Outlook for Windows and OWA with office365 subscription. 

My reproduction steps:
- Open the add-in on an existing item
- while the email is selected, drag it to a folder
- re-open that email from its new folder
-> Add-in renders and the code runs without errors, but it is un-clickable.
Note: It is possible to interact with the add-in webview with keyboard controls. Only mouse interactions are broken.
In our case, no dialog is involved. Just a regular add-in that read the currently selected email.

**Comment by t-miyake** [comment]
@shighosh-msft

Thanks for your response. We didn’t have a clear repro earlier, but based on others’ comments we were able to reproduce the issue.

It appears that **moving a message** is the trigger. After a move operation, any subsequently opened Dialog has its iframe’s `pointer-events` set to `none`.

To demonstrate, we prepared two very simple, minimal add-ins and reproduced the problem. Please see the videos (animated GIFs) below:

- **OnSend add-in**
![Image](https://github.com/user-attachments/assets/066697b2-f0c1-4f79-911f-335b5a0b6588)

- **Ribbon button add-in** (pressing the button only opens a Dialog)
![Image](https://github.com/user-attachments/assets/43e0e0ac-ab64-4ab0-a119-cf5a37c5d956)

In both cases, the Dialog ends up in the same broken state (`pointer-events: none` on the iframe).

**Reports from customers and users continue to increase. Because this completely blocks interaction inside the Dialog, it’s a severe issue. We would greatly appreciate a prompt fix.**

**Comment by sznorbert07** [comment]
Our customers also experience the following issue in Microsoft Edge browsers and Outlook PWA app. We can easily reproduce the issue with the steps from @truchonh.

For now we found a "stable" workaround. If the add-in sidebar stucks and cannot be interacted at all, just start dragging an email and drop it to the same location. This makes the sidebar interactable again.

**Comment by neprasad-microsoft** [comment]
Hi @t-miyake 
Thanks for the detailed repro steps. It helped us identify the cause. We've implemented a service configuration update that should resolve the issue.
Please check again after 3 hours. Before retrying, kindly clear your browser cache, and let us know whether the issue has been resolved on your end.

**Comment by t-miyake** [comment]
Hi @neprasad-microsoft

Thank you for promptly resolving the issue!
We have confirmed that the issue no longer occurs in our environment.

To be sure, we will have the customers who reported the problem test it as well, and once we confirm that the issue is resolved for them, we will close this issue.

**Comment by t-miyake** [comment]
Hi @neprasad-microsoft
We have confirmed that this issue has been resolved for all the customers who had reported it.
Thank you for the prompt fix. I am closing this issue with this comment.

**Comment by frankchen76** [comment]
Hi @t-miyake, I am a Microsoft FTE and run a dogfood version. I still see this issue showed up in the following version. is it expected?

<img width="996" height="830" alt="Image" src="https://github.com/user-attachments/assets/133438bc-0a4a-4585-b6f3-2025ae2ab9a9" />

**Comment by t-miyake** [comment]
Hi @frankchen76, Thank you for reporting this.  
With the version I’m using (Production version), I do not see this issue in either Outlook on the web or Outlook (new).  
However, it’s possible that the issue has reappeared in the dogfood version, so if you could report this to the product team, I would appreciate it.  

For reference, the Outlook versions I just checked are as follows:  
- **Outlook on the web**: 20250815005.20
- **Outlook (new)**: 1.2025.806.300 (Production)  
  Client version: 20250822005.09

**Comment by zhngx1** [comment]
@frankchen76 The issue should have been resolved on Dogfood ring. Do you have more detailed steps of the repro? Do you need to  drag the email or do other operation to repro?

**Comment by frankchen76** [comment]
Hi @zhngx1, please see below reproduction steps: 

- select an email
- bring up the outlook add-in panel
- drag & drop email to different folder. the issue came back. when use right click -> move or quick step (shortcut), it didn't generate the issue. 
please see below for debug html which indicated that "pointer-event" was set to "none"

<img width="1500" height="1309" alt="Image" src="https://github.com/user-attachments/assets/535d0474-d3bb-428a-b6b7-656bbed61681" />

**Comment by zhngx1** [comment]
@frankchen76 I do not repro the issue on a dogfood build. Can you refresh and see if you still repro on the latest build?

**Comment by aspantel** [comment]
Hello, our client experiences this issue after moving emails to another folder or the Other inbox.
This happens in Chrome and Edge, using Web Outlook. For them, this started happening last summer.
Thoughts?
