### ISSUE TITLE
Unexpected save triggered by read-only functions in PowerPoint for the Web

### ISSUE THREAD

**Issue by andreagasparin** [OfficeDev/office-js#6329]
# Provide required information needed to triage your issue
We're seeing a significant performance difference between using PowerPoint on the desktop and the web.
The slowness on the web is likely caused by any call to office-js functions causing the presentation to be saved.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: PowerPoint
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior

When using PowerPoint on the web, running office-js functions, which only read the presentation, should not cause the presentation to be saved.

## Current behavior

When using PowerPoint on the web, every call to office-js functions causes the presentation to be saved.

## Steps to reproduce

I attach a simple project to replicate the problem (performs a reading of the slides):

[Test_PowerPoint_Autosave.zip](https://github.com/user-attachments/files/23724273/Test_PowerPoint_Autosave.zip)

Using the program, you can see the significant performance difference between desktop:
<img width="341" height="431" alt="Image" src="https://github.com/user-attachments/assets/1c43dca8-a714-4d2d-a034-89e2805ba29d" />

and web:
<img width="334" height="457" alt="Image" src="https://github.com/user-attachments/assets/2d5b4fed-b427-4ba3-b31a-ec31ee42743f" />

You can see that each time you call:
    let slides: PowerPoint.SlideCollection = context.presentation.slides;
    slides.load("items");
	await context.sync();
	
saves the presentation:
https://github.com/user-attachments/assets/e93477ad-85a5-4982-a8d4-ab41d43cb67f

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by EsterBergen** [comment]
@andreagasparin - thanks for reporting this. We created a bug for the team to look into (10873876). They will respond here when more details are available.

**Comment by Faibbus** [comment]
Script Lab repro for the `context.sync()` → auto-save 
https://gist.github.com/Faibbus/e7077abc22bf129b513145871a5608bc

(This issue is relevant to me as I need to monitor the selection to update UI, but having autosave on a loop looks scary to the users.)

**Comment by jaiswalshubh1** [comment]
Hi @andreagasparin,

As per the internal tickets: 10558937 and 10873876, issue has been fixed, can you please verify from you side in latest version ? 

CC: @kustonaut 

Thanks!
Shubham Jaiswal

**Comment by andreagasparin** [comment]
Hi @jaiswalshubh1 ,
I just checked with the web version of PowerPoint, and the problem still appears!
I've attached the test video.

https://github.com/user-attachments/assets/65e77e70-7fa3-4e66-a49d-a342268c871f

**Comment by andreagasparin** [comment]
Hi @kustonaut,

I actually provided the requested feedback about a month ago, but unfortunately I never received a response after that.
So I guess the issue has now been marked as stale because there was no activity for 4 days… despite my feedback having been sitting there for about a month. 

Anyway, I'm happy to provide any additional information you may need. Hopefully this time my reply won't get lost in the mysterious depths of GitHub notifications.

Thanks!

**Comment by kustonaut** [comment]
@andreagasparin - I am checking with the owning team if this is rolled out and can be retested. tracking id: 10558937

cc: @JessehMSFT
