### ISSUE TITLE
Query regarding loading resources from Office JS (OTel not loaded)

### ISSUE THREAD

**Issue by topkoong** [OfficeDev/office-js#784]
Hi there!

I built an Excel task pane add-in using Angular from the given template and **didn't even write or modify any original code**. However, after uploading the manifest file, I got an error message regarding "**OTel not loaded!**" from excel-web-16.00.js file (a CDN from Microsoft). I don't think the problem is at my end. So, I was wondering if you guys could let me know how to fix this problem or help me out.

Attached is a screenshot of this error.
![Screen Shot 2562-10-15 at 17 36 17](https://user-images.githubusercontent.com/18175994/67062486-9db3cd80-f18d-11e9-8794-13a21fd2b074.png)

Thank you for your time and consideration!

**Comment by topkoong** [comment]
Do you guys have any update on this?

**Comment by sumurthy** [comment]
Able to repro. The error won't affect the API in any way. So, it is okay to ignore this error message if you can in your app. We'll look at why the error appears even though all resources are loaded.

**Comment by topkoong** [comment]
@sumurthy Thank you for the reply. Looking forward to hearing from you.

**Comment by topkoong** [comment]
@sumurthy  Any update?

**Comment by sumurthy** [comment]
This has been fixed. I don't see the issue anymore on our end. Could you please confirm?

**Comment by topkoong** [comment]
@sumurthy I think it is fixed cuz I no longer see an error message regarding OTel not loaded. By the way, I was wondering if you or your team could confirm that you have fixed the issue.

Thank you for your time and consideration!

**Comment by sumurthy** [comment]
This seems to have been addressed by an older fix (I'm unable to track down which exact patch addressed this issue). 
Knowing that the issue can't be reproduced, I'll close the issue.

**Comment by topkoong** [comment]
@sumurthy  I don't think it's fixed as long as this still happens.
