### ISSUE TITLE
addImage() not working in Excel online version

### ISSUE THREAD

**Issue by officeAddinDeveloper** [OfficeDev/office-js#841]
I'm trying to add a new image from an Excel adding using Office.js.

That's my code:

```
    image = activeWorkSheet.shapes.addImage(imageBase64);
    await context.sync();

    // set some image properties
```
This is failing with the error:
```
RichApi.Error: This operation is not implemented.
    at new c (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:24:287800)
    at a.e.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:24:348351)
    at https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:24:346456
```
I also tried using "Imagecoercion", but this seems to be unsupported, and in fact, I'm not able to use it: https://github.com/OfficeDev/office-js/issues/648.

Any suggestion would be appreciated!

## Expected Behavior
The possibility to use .addImage() to add a new image in a workbook from an Excel addin

## Current Behavior
The .addImage() method is not working in the online 365 version, an error is returned istead

## Steps to Reproduce, or Live Example
* Additional details:
see above

## Your Environment
* Platform: PC desktop/Office Online
* Host: Excel
* Office version number: 16.0.12311.37950
* Operating System: Windows 10
* Browser (if using Office Online): Chrome

## Useful logs
- [x] Console errors: see above

Let me know if you need something else...

**Comment by AbidRahman-MSFT** [comment]
Hey @officeAddinDeveloper, thank you for reporting this issue. 
Adding @lumine2008 for context and more information.

**Comment by donlvMSFT** [comment]
This issue has been fixed. @officeAddinDeveloper , could you try again? Thanks.

**Comment by officeAddinDeveloper** [comment]
Hi @donlvMSFT ,thank you for you feedback.
This is still not working
![image](https://user-images.githubusercontent.com/57702568/68835265-efca0f00-06b7-11ea-8576-d7c3a5cff211.png)

**Comment by LiJiang-msft** [comment]
hi @officeAddinDeveloper , if that possible to paste the base64 string you used, if there's no PII information. So that could help us run some local debug.

**Comment by officeAddinDeveloper** [comment]
Hi @LiJiang-msft, I have no doubt about the base64 string we used because we tested the addin using Excel desktop and it is working as expected, no issues, so the string is correct. Unfortunately I cannot share it.

I have this issue only when using Excel online.

**Comment by LiJiang-msft** [comment]
Thanks @officeAddinDeveloper , is that possible to share your very roughly location, for example to  country and city, that might help us to track to settings in data center.

**Comment by officeAddinDeveloper** [comment]
I'm in Italy.

**Comment by LiJiang-msft** [comment]
can you detail to city or province?

btw:// can you paste a full error log?

**Comment by officeAddinDeveloper** [comment]
North-east Italy, Venice area.

This is the error log as specified in the description: 
```
RichApi.Error: This operation is not implemented.
    at new c (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-web-16.00.js:24:287800)
    at a.e.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-web-16.00.js:24:348351)
    at https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-web-16.00.js:24:346456
```
This is what I get when I catch the result of context.sync() after using the addImage() API:
`await context.sync().catch(error => console.log(error) );`

**Comment by LiJiang-msft** [comment]
@officeAddinDeveloper , could you please try to print following properties?
console.error(error.debugInfo.code);
console.error(error.debugInfo.errorLocation);
console.error(error.debugInfo.statement);
console.error(error.debugInfo.surroundingStatements);
}

**Comment by officeAddinDeveloper** [comment]
Sure, that's the full chrome log when adding the code you suggested:

[my.sharepoint.com-1573723607033.log](https://github.com/OfficeDev/office-js/files/3845666/my.sharepoint.com-1573723607033.log)

**Comment by LiJiang-msft** [comment]
Thanks for providing that. We can't reproduce your issue in our side. That may need more time for us to figure out the root cause. 
We will collect more information from our side, and update this thread later.

**Comment by officeAddinDeveloper** [comment]
Ok, thanks, let me know as soon as you have updates.

**Comment by LiJiang-msft** [comment]
Hi @officeAddinDeveloper , I gave a lot try with machines located in vary places in europe, I'm pretty sure it covers almost all data centers our bit deployed to. Unfortunately I can't reproduce your issue in any of them, and not able to get much clue why that API not work for you.

I took some snapshoots below, you can see all images (jpg & png) successfully added to a document:
![Capture](https://user-images.githubusercontent.com/57741659/68918829-c3db8600-07aa-11ea-9d86-5331511c91f6.png)

We did some code changes which is on its way to deploy, which we hope that could help us get more knowledge healthy of our code, and to see if possible to get the root cause of your issue. The code could takes 1~2 weeks to world wide, we will contact to you in this thread after then.

**Comment by officeAddinDeveloper** [comment]
Hi @LiJiang-msf ,

Thanks for your investigation. I just want to let you know that I tried also from a Swedish IP 
![image](https://user-images.githubusercontent.com/57702568/68932007-08a6f300-0792-11ea-9088-6bfd53375161.png)

but with the same result.

Can you please share the code you used to perform the test? Just to make sure I'm not doing something wrong, even if everything works fine from Excel desktop...

**Comment by LiJiang-msft** [comment]
@officeAddinDeveloper , thanks for your feedback, that is a great idea that I will share my script to you, and could you please help us run very few steps verification? I took snapshots using win32, but steps are exactly same on excel online.
1. On you online environment, download and install "Script Lab" from office store, that will add an item to your ribbon.

2. Click on "Code", it will bring a taskpane
![image](https://user-images.githubusercontent.com/57741659/69018005-2324da80-09e5-11ea-98a9-7b18b99880f5.png)

3. Click on the "more" button at the top-left corner of the taskpane
![image](https://user-images.githubusercontent.com/57741659/69018041-61ba9500-09e5-11ea-8484-d47b1d81fe36.png)

4. Click on the "Import" tab
![image](https://user-images.githubusercontent.com/57741659/69018059-857ddb00-09e5-11ea-9b1c-f70f0a9885ec.png)

5. Fill in following url in the text area and click "Import" button.
https://gist.github.com/donlvMSFT/e9c6bdd9b2b8fb2f70e7d9685467be67

6. You may see something like this, and click on the "Trust" button.
![image](https://user-images.githubusercontent.com/57741659/69018361-08536580-09e7-11ea-901d-18c4b5a63ceb.png)

7. Click "Run" button under the "Script Lab" tab.

8. Click "Create a worksheet", it will create a new worksheet named as "Shapes".

9. Click "Write image as string", that will add an image to the new added worksheet.
![image](https://user-images.githubusercontent.com/57741659/69019209-882eff00-09ea-11ea-927f-e3f426f491b8.png)

We appreciate if you could try different pictures to see what will happen, you can just replace the value of variable BASE64IMGSTRING, using any valid in-base64-stringified JPG or PNG file (but make sure that is less than 5m).
![image](https://user-images.githubusercontent.com/57741659/69019262-c7f5e680-09ea-11ea-998a-4af4ae0f6072.png)

**Comment by officeAddinDeveloper** [comment]
Hi @LiJiang-msft,

Thank you for your feedback...
I tried follow the steps you provided but failed when clicked on the "Write image as string" button, the error seems to be the same as the one I get from my code ("This operation is not implemented")

![image](https://user-images.githubusercontent.com/57702568/69041220-6e43eb00-09ef-11ea-9867-8d48f0bf2c22.png)

**Comment by LiJiang-msft** [comment]
Thanks @officeAddinDeveloper , can you also try those steps in onedrive rather than your tenant?

**Comment by officeAddinDeveloper** [comment]
Hi, can you please specify what you mean by "try on onedrive"?

**Comment by LiJiang-msft** [comment]
You can create office document free on onedrive.live.com/ if you have windows account (somebody@live.com), so would you please try to create an excel document on onedrive.live.com/, and repeat the steps above to see what will happen there?

Thanks

**Comment by officeAddinDeveloper** [comment]
This is working on onedrive.live.com following the above steps. Does this means that our tenant is using a different version? How can we check the version on our tenant and keep it updated or know when an update is installed?

**Comment by LiJiang-msft** [comment]
Thanks to confirm that. I'm not familiar with O365 or tenant stuff, might you could ping you tenant admin to know if the bits is up-to-date (I assume you're not an on-prem user?).

I'm not sure, but if you give me some your tenant information , for example, tenant id/name, data center, I might could try to dig little bit more.

**Comment by AndreaFrancoQlik** [comment]
Hi @LiJiang-msft ,

It seems like some users in our tenants are configured in "Targeted release", while others are on "World wide standard release". Does this means that we need to be in the targeted mode to receive fix earlier? Or is there a particular mode to be used to receive fix earlier?

**Comment by officeAddinDeveloper** [comment]
hi @LiJiang-msft,

If I understand correctly, users can be configured to be on different update channels: https://docs.microsoft.com/en-us/deployoffice/overview-of-update-channels-for-office-365-proplus. It seems that in my organization we have some users in the targeted release and some in the default one. Is there a correlation between the cannel and the possibility to receive the patch? Or are those things independent?

**Comment by LiJiang-msft** [comment]
Sorry I'm not familiar with that, but from my understanding, you and your org should in the latest bits. We have a internal thread discuss some issues, might related to your problem, we will get more information and ping you back right here. Thanks for your patience.

**Comment by LiJiang-msft** [comment]
btw, @officeAddinDeveloper , is that possible you give another try on your tenant to see if the issue still persistent? That definitely will help us. Thanks.

**Comment by officeAddinDeveloper** [comment]
Hi @LiJiang-msft ,

After I moved to a targeted channel to receive updates earlier in our tenant the addImage() method is working, however this is still NOT working for my colleagues. So now the question is how can we discriminate between API versions for our customers? We need a way to understand if they are using a particular API version or another since it is possible that some functionalities are not working or working differently from one version to another. In that case, me and my colleagues are on the same build number and a call to "Office.context.requirements._setMap._sets" give exactly the same answer but addImage() is only working for me.

**Comment by LiJiang-msft** [comment]
I think we just figure out the root cause, that is a by design behavior, as some feature will only enable to some channel (For example, the target channel). 
We're working on make that feature available for all channels, but unfortunately it might need another few weeks.
We will ping you back in this thread once it available to all channels.

**Comment by officeAddinDeveloper** [comment]
@LiJiang-msft ,
Thanks for your feedback.
This issue was also opened on stackoverflow (https://stackoverflow.com/questions/58818783/office-js-addimage-not-working-in-excel-online-version) where Rick Kirkham answered that "The Shapes APIs require Excel.js version 1.9." This is also what the public documentation says. 

What you are saying here is different and not compatible with the public documentation.

By the way, this does not solve our problem. We need to programmatically discrimitate between different API versions to enable our customers to use our addin even if they are running it in different channels (targeted/non-targeted). If a particual API version does not support addImage, we need to block this functionality and ask our customer to upgrade. How can we know if a particular API method will work in the customer environment? How can we check and discriminate between API versions?

**Comment by LiJiang-msft** [comment]
That is true the AddImage api avaialbe in 1.9, and you can trust the version.
But the issue we found right here, is that it not available to all users, even the reference set to 1.9 or later.

**Comment by 9esuLuciano** [comment]
@officeAddinDeveloper , we made a change try to resolve the issue and should already ship to all tenant users, can you give another try, to check if it work for you?

**Comment by donlvMSFT** [comment]
Hi @officeAddinDeveloper , we made a change to resolve the issue, it should already ship to all tenant users.

Could you give another try to check? Thanks!

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
